{
 "title": "Purdue Tier-2 GPU Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align:center;\">USCMS Dedicated GPUs (Slurm)</h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align:center;\">T4 GPUs (AF + SONIC)</h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align:center;\">Analysis Facility GPUs</h1>"
   }
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "GPUs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(DCGM_FI_DEV_GPU_UTIL)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "GPUs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  DCGM_FI_DEV_GPU_UTIL{\n  kubernetes_node=~\"paf.*\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "GPUs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\ncount by (UUID) (\nDCGM_FI_PROF_GR_ENGINE_ACTIVE{\n  kubernetes_node=~\"(geddes-g000|geddes-g001|geddes-g002)\"\n}\n)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Multi-instance GPU (MIG) Splitting",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 2 },
   "targets": [
    {
     "expr": "count by (GPU_I_PROFILE) (\nDCGM_FI_PROF_GR_ENGINE_ACTIVE{\n  kubernetes_node=~\"(geddes-g000|geddes-g001|geddes-g002)\"\n}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "in use over selected period" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  max_over_time(\n    (DCGM_FI_DEV_GPU_UTIL > 0)[$__range:]\n  ) > 0\n)\nor on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "in use over selected period" } },
   "targets": [
    {
     "expr": "count(\n  max_over_time(\n    (DCGM_FI_DEV_GPU_UTIL{\n      kubernetes_node=~\"paf.*\"\n    } > 0)[$__range:]\n  ) > 0\n)\nor on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "in use over selected period" } },
   "targets": [
    {
     "expr": "count(\n  max_over_time(\n    (DCGM_FI_PROF_GR_ENGINE_ACTIVE{\n      kubernetes_node=~\"(geddes-g000|geddes-g001|geddes-g002)\"\n    } > 0)[$__range:]\n  ) > 0\n)\nor on() vector(0)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "GPU Utilization: Slurm (Hammer cluster)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "label_replace(\n  DCGM_FI_DEV_GPU_UTIL,\n  \"host\",\n  \"$1\",\n  \"Hostname\",\n  \"^(.*)\\\\.rcac\\\\.purdue\\\\.edu$\"\n)",
     "legendFormat": "{{host}} - {{modelName}} - #{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Utilization: T4 (AF + SONIC)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{\n  kubernetes_node=~\"paf.*\"\n}",
     "legendFormat": "{{kubernetes_node}} - {{modelName}} - #{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Utilization: Analysis Facility",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_GR_ENGINE_ACTIVE{\n  kubernetes_node=~\"(geddes-g000|geddes-g001|geddes-g002)\"\n}\n# DCGM_FI_DEV_GPU_UTIL{\n#   kubernetes_node=~\"(geddes-g000|geddes-g001|geddes-g002)\"\n# }",
     "legendFormat": "{{kubernetes_node}} - A100 - {{GPU_I_PROFILE}} - #{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU MemoryUtil.: Slurm (Hammer cluster)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "label_replace(\n  DCGM_FI_DEV_FB_USED,\n  \"host\",\n  \"$1\",\n  \"Hostname\",\n  \"^(.*)\\\\.rcac\\\\.purdue\\\\.edu$\"\n)",
     "legendFormat": "{{host}} - {{modelName}} - #{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization: T4 (AF + SONIC)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{\n  kubernetes_node=~\"paf.*\"\n}",
     "legendFormat": "{{kubernetes_node}} - {{modelName}} - #{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization: Analysis Facility",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{\n  kubernetes_node=~\"(geddes-g000|geddes-g001|geddes-g002)\"\n}",
     "legendFormat": "{{kubernetes_node}} - A100 - {{GPU_I_PROFILE}} - #{{gpu}}"
    }
   ]
  }
 ]
}