apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: purdue-af-flux
  namespace: cms
  annotations:
    cluster: geddes
spec:
  interval: 1m
  timeout: 1m
  path: "./deploy/core-production/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: purdue-af
  targetNamespace: cms
  postBuild:
    substitute:
      enable_ingresses: "true"
      namespace: "cms"
      jupyterhub_db_pv_selector: '{matchLabels: {purdue-af-db: "true"}}'
      jupyterhub_db_storage_class: '""'
      sonic_gpus_initial: "1"
      af_shared_storage_size: "40Ti"
      x509_secret_name: "af-x509-proxy"
  decryption:
    provider: sops
    secretRef:
      name: sops-age
