apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: purdue-af
  namespace: cms
  annotations:
    cluster: geddes
spec:
  interval: 30s
  timeout: 1m
  url: https://github.com/PurdueAF/purdue-af.git
  ref:
    semver: 2025.x
  secretRef:
    name: flux-github-token
