# Required configuration
# hubUrl should be a URL like http://hub:8081 or https://jupyter.example.org.
# Only HTTP(S) traffic will be sent to this URL.
hubUrl: https://cms.geddes.rcac.purdue.edu

# hostKey is a private SSH key used to encrypt outgoing communication from the
# jupyterhub-ssh and jupyterhub-sftp pods. If this value is blank, whatever was
# used previously will be used, but if nothing has been used previously a RSA
# 4086 key will be generated.
hostKey: ""

# nameOverride if set, will override the name of the chart in two contexts.
# 1. The label: app.kubernetes.io/name: <chart name>
# 2. The Helm template function: jupyterhub-ssh.fullname, if fullnameOverride
#    isn't set because then it takes precedence.
# nameOverride: "cmshub-ssh-test"

# fullnameOverride set to a truthy value will make all k8s resources be named
# <fullnameOverride> with an optional prefix. But if fullnameOverride is set to
# a falsy value will make all k8s resource names become either <release
# name>-<chart name> with an optional suffix, or <release name> with an optional
# suffix. The chart name part is excluded if release name is found to contain
# the chart name.
# fullnameOverride: "cmshub-ssh-test"

ssh:
  enabled: true
  replicaCount: 1

  config:
    JupyterHubSSH:
      debug: true
      host_key_path: /etc/jupyterhub-ssh/config/hostKey

  image:
    repository: quay.io/jupyterhub-ssh/ssh
    tag: "0.0.1-0.dev.git.149.he5107a4"
    pullPolicy: ""

  service:
    type: LoadBalancer
    port: 22

  podLabels:
    hub.jupyter.org/network-access-hub: "true"
    hub.jupyter.org/network-access-proxy-http: "true"
  podAnnotations: {}
  serviceLabels: {}
  serviceAnnotations: {}

  resources: {}
  imagePullSecrets: []
  nodeSelector: {'cms-af-prod': 'true'}
  tolerations:
    - key: "hub.jupyter.org/dedicated"
      operator: "Equal"
      value: "cms-af"
      effect: "NoSchedule"
  affinity: {}
  networkPolicy: {}

sftp:
  enabled: true
  replicaCount: 1

  pvc:
    enabled: true
    name: "af-shared-storage"

  image:
    repository: quay.io/jupyterhub-ssh/sftp
    tag: "0.0.1-0.dev.git.142.h402a3d6"
    pullPolicy: ""

  service:
    type: LoadBalancer
    port: 22

  podLabels:
    hub.jupyter.org/network-access-hub: "true"
    hub.jupyter.org/network-access-proxy-http: "true"
  podAnnotations: {}
  serviceLabels: {}
  serviceAnnotations: {}

  resources: {}
  imagePullSecrets: []
  nodeSelector: {'cms-af-prod': 'true'}
  tolerations:
    - key: "hub.jupyter.org/dedicated"
      operator: "Equal"
      value: "cms-af"
      effect: "NoSchedule"
  networkPolicy: {}

global: {}