apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: af-node-monitor
  namespace: cms
spec:
  selector:
    matchLabels:
      name: af-node-monitor
  template:
    metadata:
      labels:
        name: af-node-monitor
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cms-af-prod
                    operator: In
                    values:
                      - "true"
              - matchExpressions:
                  - key: cms-af-dev
                    operator: In
                    values:
                      - "true"
      # nodeSelector: {'cms-af-prod': 'true'}
      tolerations:
      - key: "hub.jupyter.org/dedicated"
        operator: "Equal"
        value: "cms-af"
        effect: "NoSchedule"
      containers:
      - name: af-node-monitor
        image: geddes-registry.rcac.purdue.edu/cms/af-node-monitor:latest
        ports:
        - containerPort: 8000
          name: metrics
        volumeMounts:
        - name: cvmfs
          mountPath: /cvmfs
          mountPropagation: HostToContainer
        - name: eos
          mountPath: /eos
          mountPropagation: HostToContainer
        - name: depot
          mountPath: /depot/cms
          mountPropagation: HostToContainer
        - name: work
          mountPath: /work/
          mountPropagation: HostToContainer
      volumes:
      - name: cvmfs
        persistentVolumeClaim:
          claimName: cvmfs
      - name: eos
        hostPath: 
          path: /eos
      - name: depot
        nfs:
          server: datadepot.rcac.purdue.edu
          path: /depot/cms
      - name: work
        persistentVolumeClaim:
          claimName: af-shared-storage
