apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - daemonset.yaml
configMapGenerator:
- name: af-node-monitor-config
  namespace: cms
  files:
  - node_healthcheck.py
  options:
    annotations:
      config-hash: "{sha256sum}"
    disableNameSuffixHash: true