apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - daemonset.yaml
configMapGenerator:
- name: af-node-monitor-config
  namespace: cms
  files:
  - node_healthcheck.py
  options:
    disableNameSuffixHash: false
vars:
  - name: CONFIGMAP_NAME
    objref:
      kind: ConfigMap
      name: af-node-monitor-config
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name