[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "genaistudio"
version = "0.0.0"
description = "Placeholder for editable install in purdue-af image"


