#!/bin/sh
#
# Task prolog is executed  on each node with credentials of job's owner user
# prior to initiation of each task.  Standard output from this program can
# be used to control the environment variables and output for the user job.
#
# See  https://slurm.schedmd.com/prolog_epilog.html
#      https://slurm.schedmd.com/slurm.conf.html
#      https://slurm.schedmd.com/faq.html#task_prolog
#
# Lev Gorenstein, 2020-03-19

# Prevent XDG_RUNTIME_DIR and SESSION_MANAGER variables from being exported
# into the jobs (these are defined locally by pam_systemd on front-ends,
# and they confuse a lot of GUI programs once exported onto the nodes where
# these local directories doon't exist).
echo "unset XDG_RUNTIME_DIR"
echo "unset SESSION_MANAGER"

# Unset these to properly launch Jupyter notebooks from interactive jobs
# (otherwise xdg-open tries to go for XFCE's /bin/exo-open and fails).
echo "unset XDG_CURRENT_DESKTOP"
echo "unset DESKTOP_SESSION"

# Unset original DBUS_* variables and replace them with a new dbus session
# on destination when appropriate.
# If not unset, GUI programs on nodes can not find non-existent session socket:
#    Failed to open connection to "session" message bus: Failed to connect to socket /tmp/dbus-ZQtWTBfwmJ: Connection refused
# If not recreated, GUI programs throw a different error:
#    Failed to open connection to "session" message bus: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
echo "unset DBUS_SESSION_BUS_ADDRESS"
echo "unset DBUS_SESSION_BUS_PID"
echo "unset DBUS_SESSION_BUS_WINDOWID"
if [ -n "$DISPLAY" ]; then
  /bin/dbus-launch | sed 's/^/export /' 		# Set!
  # Set this to silence the GSettings warning (may happen when Anaconda modules
  # override /bin/gsettings and replace it with their own one):
  #   GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
  # OTOH, it is but a warning, can just leave it.
  # echo "export GSETTINGS_BACKEND=memory"
fi

