apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flyte-minio
spec:
  storageClassName: ${singlenode_storage_class}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flyte-minio
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: flyte-minio
  template:
    metadata:
      labels:
        app: flyte-minio
    spec:
      nodeSelector:
        cms-af-prod: "true"
      tolerations:
        - key: hub.jupyter.org/dedicated
          operator: Equal
          value: cms-af
          effect: NoSchedule
      containers:
        - name: minio
          image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
          args: ["server", "/data"]
          env:
            - name: MINIO_ROOT_USER
              value: flyte
            - name: MINIO_ROOT_PASSWORD
              value: flyteflyte
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              memory: 2Gi
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: flyte-minio
---
apiVersion: v1
kind: Service
metadata:
  name: flyte-minio
spec:
  selector:
    app: flyte-minio
  ports:
    - port: 9000
