apiVersion: v1
kind: Secret
metadata:
  name: flyte-console-auth
type: Opaque
stringData:
  auth: ENC[AES256_GCM,data:5HIENwbNw4MDosuY8yCohFG1kg0b0zcXLE4u0LMxQb5E6McHqN9ZamDoyhe1cNH5qD8T09tY6VEaZ67L4Clw,iv:L5k5QLJ4TRe2tQdG+7DkQDFWGAEW0QIPGcDEUZYntRo=,tag:JebJ353i3i8oNL0+j8WAdw==,type:str]
sops:
  age:
    - recipient: age1pccfws6yghzqtg5v9228nrvs23w5thsxpr7w4kmmksn435ldev5sqkpj08
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eVExZHVyNzcwdW5wS2FV
        Z3IyeFYwMWNFb1hPcjA0Z1laOHZHNnM0NkdvClpCa0dzRUk5c2ZQcWR4SlFkZkRl
        VWI2MEJYc0pSSE1jUDNvbU1uZGp3YUUKLS0tIFBENEVBejB2ZjNMVGRTQWpHSkZU
        KzBTYWJYVUdqYldzL0J2RmJOalpwMFEK1UqGuGUVKBiV55kxIgxEibxmh47birSV
        tT3ATzhyIoObxkL94oQaJbn4wt5icAcqB5XZ5iCy/oSlHMygDcgNEg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-16T16:12:14Z"
  mac: ENC[AES256_GCM,data:AUxlyGjra8EL27/MsmRaW8r4Hz6DuZkHD9X3AdXsVvvMaC7omdPnRMdMU8cBgve5/IRs9Qel/hURtImJL20Gfmm3c+PEbR09+s7WgemGNa4ngVf4VDvAqfwc8HYCXgDFgDHrUBjN6q8ggcIwmTr6rmmz59ZBCpn8bq0J8cFRL2w=,iv:U01Ezb6roxMNw7R6B123rzBFqhBDqAMhNT3zm1/hG7M=,tag:AYVY8JpEnrmGIFKKM/PW9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
