apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonic-server
  namespace: cms
spec:
  # suspend: true
  interval: 1m
  chart:
    spec:
      # chart: helm/supersonic
      # sourceRef:
      #   kind: GitRepository
      #   name: supersonic
      #   namespace: cms
      chart: supersonic
      version: "0.2.1"
      sourceRef:
        kind: HelmRepository
        name: fastml
        namespace: cms
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: supersonic-config
      valuesKey: values.yaml
