apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supersonic
  namespace: cms
spec:
  interval: 1m
  chart:
    spec:
      chart: supersonic
      version: "0.2.1"
      sourceRef:
        kind: HelmRepository
        name: fastml
        namespace: cms
      interval: 1m
      timeout: 10m
  valuesFrom:
  - kind: ConfigMap
    name: supersonic-config
    valuesKey: values.yaml