#!/bin/sh

#Get time for logging purpose
start_time=$(date +%s%N)

#Clear the memory cache.
declare -a r s
eprocs=($(pgrep -f -u root epilog))
pprocs=($(pgrep -f -u root prolog))
logger -t epilog "$SLURM_JOB_ID $SLURM_JOB_USER ${#eprocs[*]} epilogs, ${#pprocs[*]} prologues running."
if [ ${#pprocs[*]} -lt 1 ] ; then
	if [ ${#eprocs[*]} -lt 2 ] ; then
		cache_time=$(date +%s%N)
		# Particular jobs on i nodes don't seem to like this.
		#if [[ ! "$(hostname)" =~ i[0-9]{3}\.gautschi\.rcac.purdue\.edu ]]; then
			## Disabling 4/2/2026 to address concerns about slurm
			#echo 3 > /proc/sys/vm/drop_caches
		#fi
		N=$(($(date +%s%N) - cache_time))
		logger -t epilog "$SLURM_JOB_ID $SLURM_JOB_USER Epilog Cache Drop: $(printf '%d.%03d\n' $((N/1000000000)) $(((N/1000000)%1000))) seconds."
	else
		logger -t epilog "$SLURM_JOB_ID $SLURM_JOB_USER Epilog Cache Drop deferred - epilog conflict."
	fi
else
	logger -t epilog "$SLURM_JOB_ID $SLURM_JOB_USER Epilog Cache Drop deferred - prologue conflict."
fi

#N=nano
N=$(($(date +%s%N) - start_time))
logger -t epilog "$SLURM_JOB_ID $SLURM_JOB_USER Epilog Run Time: $(printf '%d.%03d\n' $((N/1000000000)) $(((N/1000000)%1000))) seconds."

exit 0
