apiVersion: apps/v1
kind: Deployment
metadata:
   name: triton-pytorchtcv3
   labels:
     app: triton-pytorchtcv3
spec:
   replicas: 1
   selector:
     matchLabels:
       app: triton-pytorchtcv3
   template:
     metadata:
       labels:
         app: triton-pytorchtcv3
     spec:
       nodeSelector:
          eos: "true"
       volumes:
         - name: depot
           nfs:
             server: datadepot.rcac.purdue.edu
             path: /depot/cms
       containers:
         - name: triton-pytorchtcv3
           ports:
           - containerPort: 8000
             name: http-triton
           - containerPort: 8001
             name: grpc-triton
           - containerPort: 8002
             name: metrics-triton
           image: "yongbinfeng/tritonserver:pytorchTCv3"
           volumeMounts:
           - mountPath: /depot/cms
             name: depot
             #mountPropagation: HostToContainer
           command: ["/bin/sh", "-c"]
           args: ["cd /depot/cms/purdue-af/triton/models-onnx-fix/ &&\ /opt/tritonserver/bin/tritonserver --model-repository=/depot/cms/purdue-af/triton/models-onnx-fix/ --allow-gpu-metrics=true --log-verbose=1 --strict-model-config=false"]
           resources:
             limits:
               nvidia.com/mig-1g.5gb: 1
               cpu: 4
               memory: 16G
       tolerations:
         - key: hub.jupyter.org/dedicated
           operator: Equal
           value: cms-af
           effect: NoSchedule

---

apiVersion: v1
kind: Service
metadata:
   name: triton-pytorchtcv3
   labels:
     app: triton-pytorchtcv3
     scrape_metrics: "true"
   annotations:
     metallb.universe.tf/address-pool: geddes-private-pool
spec:
   selector:
     app: triton-pytorchtcv3
   ports:
     - protocol: TCP
       port: 8000
       name: http
       targetPort: 8000
     - protocol: TCP
       port: 8001
       name: grpc
       targetPort: 8001
     - protocol: TCP
       port: 8002
       name: metrics
       targetPort: 8002
   type: LoadBalancer 