apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps/sonic/helmrepo.yaml
  - ../../../apps/sonic/gitrepo-supersonic.yaml
  - ../../../apps/sonic/gitrepo-supersonic-dynamic.yaml
  - ../../../apps/sonic/supersonic/helmrelease.yaml
  - ../../../apps/sonic/supersonic-interlink/helmrelease.yaml
  - ../../../apps/sonic/supersonic-dynamic/helmrelease.yaml
configMapGenerator:
  - name: supersonic-config
    files:
      - values.yaml=../../../apps/sonic/supersonic/values.yaml
    options:
      disableNameSuffixHash: true
  - name: supersonic-interlink-config
    files:
      - values.yaml=../../../apps/sonic/supersonic-interlink/values.yaml
    options:
      disableNameSuffixHash: true
  - name: supersonic-dynamic-config
    files:
      - values.yaml=../../../apps/sonic/supersonic-dynamic/values.yaml
    options:
      disableNameSuffixHash: true
