apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps/monitoring/helmrepo-grafana.yaml
  - ../../../apps/monitoring/helmrepo-prometheus.yaml
  - ../../../apps/monitoring/af-monitoring/services.yaml
  - ../../../apps/monitoring/af-monitoring/deployment.yaml
  - ../../../apps/monitoring/af-monitoring/daemonset.yaml
  - ../../../apps/monitoring/grafana/helmrelease.yaml
  - ../../../apps/monitoring/prometheus/helmrelease.yaml
  - ../../../apps/monitoring/prometheus/servicemonitors.yaml
  - ../../../apps/monitoring/prometheus/pod-monitor-svc.yaml
  - ../../../apps/monitoring/prometheus/pvc.yaml
  - ../../../apps/monitoring/prometheus/rbac.yaml
  - ../../../apps/monitoring/pyroscope/helmrelease.yaml

configMapGenerator:
  - name: af-monitor-config
    files:
      - ../../../apps/monitoring/af-monitoring/metrics_server.py
    options:
      disableNameSuffixHash: true
  - name: af-node-monitor-config
    files:
      - ../../../apps/monitoring/af-monitoring/node_healthcheck.py
    options:
      disableNameSuffixHash: true
  - name: grafana-config
    files:
      - values.yaml=../../../apps/monitoring/grafana/values.yaml
    options:
      disableNameSuffixHash: true
  - name: grafana-public-dashboards
    files:
      - ../../../apps/monitoring/grafana/dashboards/default.json
      - ../../../apps/monitoring/grafana/dashboards/single-user.json
      - ../../../apps/monitoring/grafana/dashboards/sonic.json
      - ../../../apps/monitoring/grafana/dashboards/alerts.json
    options:
      disableNameSuffixHash: true
  - name: grafana-private-dashboards
    files:
      - ../../../apps/monitoring/grafana/dashboards/users-overview.json
      - ../../../apps/monitoring/grafana/dashboards/pyroscope.json
    options:
      disableNameSuffixHash: true
  - name: prometheus-config
    files:
      - values.yaml=../../../apps/monitoring/prometheus/values.yaml
    options:
      disableNameSuffixHash: true
  - name: pyroscope-config
    files:
      - values.yaml=../../../apps/monitoring/pyroscope/values.yaml
    options:
      disableNameSuffixHash: true
