apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: purdue-af-alert
  namespace: cms
spec:
  providerRef:
    name: github
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: purdue-af-flux
      namespace: cms 