{
 "title": "Purdue Analysis Facility Dashboard",
 "description": "Purdue Analysis Facility monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Purdue Analysis Facility metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (namespace)(kube_pod_labels{pod=~\"purdue-af-.*\", namespace=~\"cms(-dev)?\"}))",
     "legendFormat": "Current AF users"
    }
   ]
  },
  {
   "title": "Current users per node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "count by (node)(kube_pod_info{namespace=~\"cms(-dev)?\", node!=\"\", pod=~\"purdue-af-.*\"})",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Node CPU Request Quota Usage %",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node) (\n  kube_pod_container_resource_requests{\n    namespace=~\"cms(-dev)?\",\n    resource=\"cpu\"\n  }\n)\n  /\nsum(kube_node_status_capacity{resource=\"cpu\"}) by (node)\n",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Node CPU utilization %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (node)(\n  label_replace(\n    label_replace(\n      rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]),\n      \"node\", \"$1\", \"instance\", \"(.*).rcac.purdue.edu:9796\"\n    ),\n    \"node\", \"$1\", \"node\", \"(.*).cms\"\n  )\n)\n/\nsum(kube_node_status_capacity{resource=\"cpu\"}) by (node)\n",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jupyterhub_total_users{job=\"jupyterhub\"})",
     "legendFormat": "Total registered users"
    }
   ]
  },
  {
   "title": "Node Memory Request Quota Usage %",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node) (\n  kube_pod_container_resource_requests{\n    namespace=~\"cms(-dev)?\",\n    resource=\"memory\"\n  }\n)\n  /\nsum by (node) (\n  label_replace(\n      label_replace(\n      (\n        sum(node_memory_MemTotal_bytes{instance!=\"hammer-adm.rcac.purdue.edu:9100\"}) by (instance)\n      ),\n      \"node\", \"$1\", \"instance\", \"(.*).rcac.purdue.edu:9796\"\n    ),\n    \"node\", \"$1\", \"node\", \"(.*).cms\"\n  )\n)\n",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Node memory utilization %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\n  label_replace(\n    1 - (\n      sum (\n        # Memory that can be allocated to processes when they need\n        node_memory_MemFree_bytes + # Unused bytes\n        node_memory_Cached_bytes + # Shared memory + temporary disk cache\n        node_memory_Buffers_bytes # Very temporary buffer memory cache for disk i/o\n      ) by (instance)\n      /\n      sum(node_memory_MemTotal_bytes{instance!=\"hammer-osg.rcac.purdue.edu:9100\"}) by (instance)\n    ),\n    \"node\", \"$1\", \"instance\", \"(.*).rcac.purdue.edu:9796\"\n  ),\n  \"node\", \"$1\", \"node\", \"(.*).cms\"\n)\n",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Num. of pods quota",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (namespace) (kube_resourcequota{namespace=\"cms\", resource=\"pods\", type=\"used\"}) /\n  sum by (namespace) (kube_resourcequota{namespace=\"cms\", resource=\"pods\", type=\"hard\"})\n)\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 0, "w": 8, "x": 4, "y": 9 },
   "options": {
    "content": "# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
   }
  },
  {
   "title": "CPU requests quota",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (namespace) (kube_resourcequota{namespace=\"cms\", resource=\"requests.cpu\", type=\"used\"}) /\n  sum by (namespace) (kube_resourcequota{namespace=\"cms\", resource=\"requests.cpu\", type=\"hard\"})\n)\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "RAM requests quota",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (namespace) (kube_resourcequota{namespace=\"cms\", resource=\"requests.memory\", type=\"used\"}) /\n  sum by (namespace) (kube_resourcequota{namespace=\"cms\", resource=\"requests.memory\", type=\"hard\"})\n)\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "Storage mounts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 0, "w": 6, "x": 12, "y": 15 },
   "options": {
    "content": "# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
   }
  },
  {
   "title": "Depot mount",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (node) (af_node_mount_valid{mount_name=\"/depot/\"})",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "/work/ mount",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "sum by (node) (af_node_mount_valid{mount_name=\"/work/\"})",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "EOS mount",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (node) (af_node_mount_valid{mount_name=\"eos\"})",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "CVMFS mount",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "sum by (node) (af_node_mount_valid{mount_name=\"cvmfs\"})",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  { "title": "GPU metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "GPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (DCGM_FI_DEV_GPU_TEMP) by (gpu, kubernetes_node)",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage (Watts)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "avg by (gpu, kubernetes_node) (avg_over_time(DCGM_FI_DEV_POWER_USAGE[10m:1m]))",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 23 },
   "targets": [
    {
     "expr": "count (DCGM_FI_DEV_GPU_TEMP) by (modelName, GPU_I_PROFILE)",
     "legendFormat": "{{modelName}} {{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPUs requested by users",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by (resource) (\n  kube_pod_container_resource_requests{namespace=\"cms\",pod=~\"purdue-af-.*\",resource=~\"nvidia_.*\"}\n)\n",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "GPU Graphics Engine Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (gpu, GPU_I_ID, GPU_I_PROFILE, kubernetes_node) (DCGM_FI_PROF_GR_ENGINE_ACTIVE)",
     "legendFormat": "{{kubernetes_node}} {{GPU_I_PROFILE}}"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (gpu, GPU_I_ID, GPU_I_PROFILE, kubernetes_node) (\n  DCGM_FI_DEV_FB_USED /\n  ( DCGM_FI_DEV_FB_USED + DCGM_FI_DEV_FB_FREE )\n)\n",
     "legendFormat": "{{kubernetes_node}} {{GPU_I_PROFILE}}"
    }
   ]
  },
  { "title": "Slurm metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Slurm jobs (Hammer)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "targets": [
    { "expr": "slurm_info_job_user", "legendFormat": "{{user}}" }
   ]
  },
  { "title": "Dask metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Number of Dask Gateway / k8s schedulers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "count by (user) (sum by (user, instance) (dask_scheduler_workers))",
     "legendFormat": "{{ user }}"
    }
   ]
  },
  {
   "title": "Number of Dask Gateway / k8s workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
   "targets": [
    {
     "expr": "sum by (user) (dask_scheduler_workers)",
     "legendFormat": "{{ user }}"
    }
   ]
  },
  {
   "title": "Number of Dask Gateway / k8s clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
   "targets": [
    {
     "expr": "sum by (user) (dask_scheduler_clients)",
     "legendFormat": "{{ user }}"
    }
   ]
  },
  {
   "title": "Average worker memory utilization per Dask cluster",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (cluster_name) (\n  sum by (pod, cluster_name) (\n    label_replace(\n      container_memory_working_set_bytes{pod=~\"dask-worker-.*\", container=\"dask-worker\"},\n      \"cluster_name\",\n      \"$1\",\n      \"pod\",\n      \"dask-worker-([0-9a-f]{32})-.*\"\n    )\n  )\n  /\n  sum by (pod, cluster_name) (\n    label_replace(\n      kube_pod_container_resource_limits{pod=~\"dask-worker-.*\", resource=\"memory\"},\n      \"cluster_name\",\n      \"$1\",\n      \"pod\",\n      \"dask-worker-([0-9a-f]{32})-.*\"\n    )\n  )\n)\n",
     "legendFormat": "{{ cluster_name }}"
    }
   ]
  },
  {
   "title": "Maximum memory utilization among workers in each Dask cluster",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (cluster_name) (\n  sum by (pod, cluster_name) (\n    label_replace(\n      container_memory_working_set_bytes{pod=~\"dask-worker-.*\", container=\"dask-worker\"},\n      \"cluster_name\",\n      \"$1\",\n      \"pod\",\n      \"dask-worker-([0-9a-f]{32})-.*\"\n    )\n  )\n  /\n  sum by (pod, cluster_name) (\n    label_replace(\n      kube_pod_container_resource_limits{pod=~\"dask-worker-.*\", resource=\"memory\"},\n      \"cluster_name\",\n      \"$1\",\n      \"pod\",\n      \"dask-worker-([0-9a-f]{32})-.*\"\n    )\n  )\n)\n",
     "legendFormat": "{{ cluster_name }}"
    }
   ]
  },
  {
   "title": "Average CPU utilization per Dask cluster",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (cluster_name) (\n  sum by (pod, cluster_name) (\n    label_replace(\n      rate(container_cpu_usage_seconds_total{pod=~\"dask-worker-.*\", container=\"dask-worker\"}[5m]),\n      \"cluster_name\",\n      \"$1\",\n      \"pod\",\n      \"dask-worker-([0-9a-f]{32})-.*\"\n    )\n  )\n  /\n  sum by (pod, cluster_name) (\n    label_replace(\n      kube_pod_container_resource_limits{pod=~\"dask-worker-.*\", resource=\"cpu\"},\n      \"cluster_name\",\n      \"$1\",\n      \"pod\",\n      \"dask-worker-([0-9a-f]{32})-.*\"\n    )\n  )\n)\n",
     "legendFormat": "{{ cluster_name }}"
    }
   ]
  },
  {
   "title": "Maximum CPU utilization among workers in each Dask cluster",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (cluster_name) (\n  sum by (pod, cluster_name) (\n    label_replace(\n      rate(container_cpu_usage_seconds_total{pod=~\"dask-worker-.*\", container=\"dask-worker\"}[5m]),\n      \"cluster_name\",\n      \"$1\",\n      \"pod\",\n      \"dask-worker-([0-9a-f]{32})-.*\"\n    )\n  )\n  /\n  sum by (pod, cluster_name) (\n    label_replace(\n      kube_pod_container_resource_limits{pod=~\"dask-worker-.*\", resource=\"cpu\"},\n      \"cluster_name\",\n      \"$1\",\n      \"pod\",\n      \"dask-worker-([0-9a-f]{32})-.*\"\n    )\n  )\n)\n",
     "legendFormat": "{{ cluster_name }}"
    }
   ]
  },
  { "title": "JupyterHub diagnostics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "JupyterHub response status codes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    jupyterhub_request_duration_seconds_bucket{\n      job=\"jupyterhub\",\n      instance=\"cms.geddes.rcac.purdue.edu\",\n    }[2m]\n  )\n) by (code)\n",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "JupyterHub response latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum(\n    rate(\n      jupyterhub_request_duration_seconds_bucket{\n        job=\"jupyterhub\",\n        instance=\"cms.geddes.rcac.purdue.edu\",\n        handler!=\"jupyterhub.apihandlers.users.SpawnProgressAPIHandler\"\n      }[5m]\n    )\n  ) by (le))\n",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum(\n    rate(\n      jupyterhub_request_duration_seconds_bucket{\n        job=\"jupyterhub\",\n        instance=\"cms.geddes.rcac.purdue.edu\",\n        handler!=\"jupyterhub.apihandlers.users.SpawnProgressAPIHandler\"\n      }[5m]\n    )\n  ) by (le))\n",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(\n  0.25,\n  sum(\n    rate(\n      jupyterhub_request_duration_seconds_bucket{\n        job=\"jupyterhub\",\n        instance=\"cms.geddes.rcac.purdue.edu\",\n        handler!=\"jupyterhub.apihandlers.users.SpawnProgressAPIHandler\"\n      }[5m]\n    )\n  ) by (le))\n",
     "legendFormat": "25th percentile"
    }
   ]
  },
  {
   "title": "User pod start times",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(jupyterhub_server_spawn_duration_seconds_bucket{\njob=\"jupyterhub\",\ninstance=~\"cms(dev)?.geddes.rcac.purdue.edu\"\n}[5m])) by (le))\n"
    }
   ]
  },
  {
   "title": "Analysis Grand Challenge Event Rate per worker (1 file per dataset, 10 workers)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "kHz" } },
   "targets": [
    {
     "expr": "avg_over_time((sum(agc_event_rate_per_worker) > 0)[60m:])",
     "legendFormat": "Event rate"
    }
   ]
  }
 ]
}