{
 "title": "SuperSONIC Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "release_name",
    "label": "Release",
    "query": {
     "query": "label_values({app=\"supersonic\",namespace=\"sonic-server\"},release)"
    }
   },
   {
    "name": "server_load_metric",
    "label": "Server Load Metric",
    "query": "sum by (release) (    rate(nv_inference_queue_duration_us{release=~\"supersonic\"}[15s]))  /sum by (release) (    (rate(nv_inference_exec_count{release=~\"supersonic\"}[15s]) * 1000) + 0.001)"
   },
   { "name": "server_load_threshold", "label": "Server Load Threshold", "query": "<nil>" },
   { "name": "version", "label": "Version", "query": "0.2.0" },
   { "name": "version", "label": "Version", "query": "supersonic" },
   {
    "name": "prometheus_url_full",
    "label": "Prometheus URL",
    "query": "https://prometheus-cms.nrp-nautilus.io:443"
   },
   { "name": "namespace", "label": "Namespace", "query": "sonic-server" },
   { "name": "service", "label": "service", "query": { "query": "label_values(service)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center; background: transparent !important;\">  <img src=\"https://github.com/fastmachinelearning/SuperSONIC/blob/main/docs/img/SuperSONIC_small_light_256.png?raw=true\" alt=\"SONIC Logo\" style=\"width: 100px; margin-right: 15px; display: inline-block;\">  <div style=\"display: inline-block;\">    <h1 style=\"margin: 0; padding: 0;\">SuperSONIC Dashboard</h1>    <p style=\"margin: 5px 0;\">Release name: ${release_name}</p>    <p style=\"margin: 5px 0;\">Version: ${version}</p>    <div style=\"margin: 5px 0;\">      <a href=\"https://fastmachinelearning.org/SuperSONIC\" target=\"_blank\" style=\"margin-right: 15px; text-decoration: none;\">        <i class=\"fa fa-book\"></i> Documentation      </a>      <a href=\"https://github.com/fastmachinelearning/SuperSONIC/issues\" target=\"_blank\" style=\"margin-right: 15px; text-decoration: none;\">        <i class=\"fa fa-github\"></i> GitHub Issues      </a>      <a href=\"${prometheus_url_full}\" target=\"_blank\" style=\"text-decoration: none;\">        <i class=\"fa fa-link\"></i> Prometheus      </a>    </div>  </div></div> "
   }
  },
  {
   "title": "Server Map (all pods in time window)",
   "type": "nodeGraph",
   "gridPos": { "h": 32, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "f0a7f7ec", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "serviceMapQuery": "{client!=\"user\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Number of Triton Servers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(release)(nv_gpu_utilization{release=~\"${release_name}\", namespace=~\"${namespace}\"})",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "Server Load Metric",
   "type": "timeseries",
   "description": "Metric and threshold configured in `prometheus.serverLoadMetric` and `prometheus.serverLoadThreshold` parameters. Default metric: inference queue latency. Default threshold: 100ms.",
   "gridPos": { "h": 10, "w": 7, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "${server_load_metric}", "legendFormat": "{{release}}" }
   ]
  },
  {
   "title": "Latency Breakdown",
   "type": "timeseries",
   "description": "Latency components measured by Triton servers, as well as total latency measured at proxy.",
   "gridPos": { "h": 10, "w": 7, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum (rate(nv_inference_compute_infer_duration_us{release=~\"${release_name}\", namespace=~\"${namespace}\"}[15s])) / sum ((rate(nv_inference_exec_count{release=~\"${release_name}\", namespace=~\"${namespace}\"}[15s]) * 1000))",
     "legendFormat": "Inference"
    },
    {
     "expr": "sum (rate(nv_inference_queue_duration_us{release=~\"${release_name}\", namespace=~\"${namespace}\"}[15s])) / sum ((rate(nv_inference_exec_count{release=~\"${release_name}\", namespace=~\"${namespace}\"}[15s]) * 1000))",
     "legendFormat": "Queue"
    },
    {
     "expr": "sum (rate(nv_inference_compute_input_duration_us{release=~\"${release_name}\", namespace=~\"${namespace}\"}[15s])) / sum ((rate(nv_inference_exec_count{release=~\"${release_name}\", namespace=~\"${namespace}\"}[15s]) * 1000))",
     "legendFormat": "Input"
    },
    {
     "expr": "sum (rate(nv_inference_compute_output_duration_us{release=~\"${release_name}\", namespace=~\"${namespace}\"}[15s])) / sum ((rate(nv_inference_exec_count{release=~\"${release_name}\", namespace=~\"${namespace}\"}[15s]) * 1000))",
     "legendFormat": "Output"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_rq_time_sum{envoy_http_conn_manager_prefix=\"ingress_grpc\", release=~\"${release_name}\", namespace=~\"${namespace}\"}[15s])) / sum(rate(envoy_http_downstream_rq_time_count{envoy_http_conn_manager_prefix=\"ingress_grpc\", release=~\"${release_name}\", namespace=~\"${namespace}\"}[15s]))",
     "legendFormat": "Total (measured at proxy)"
    }
   ]
  },
  {
   "title": "Number of Triton Servers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "count by(release)(nv_gpu_utilization{release=~\"${release_name}\", namespace=~\"${namespace}\"})",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "GPU power usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(nv_gpu_power_usage{namespace=~\"${namespace}\"} / nv_gpu_power_limit{namespace=~\"${namespace}\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nv_gpu_utilization{namespace=~\"${namespace}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GPU memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nv_gpu_memory_used_bytes{namespace=~\"${namespace}\"}/nv_gpu_memory_total_bytes{namespace=~\"${namespace}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Inferences per second by server (all models)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate(nv_inference_count{release=~\"${release_name}\", namespace=~\"${namespace}\"}[15s])) by(pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Inferences per second by model (all servers)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate(nv_inference_count{release=~\"${release_name}\", namespace=~\"${namespace}\"}[15s])) by(model)",
     "legendFormat": "{{ model }}"
    }
   ]
  }
 ]
}