{
 "title": "SuperSONIC Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "type": "text", "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 }, "options": { "content": "%HEADER%" } },
  { "title": "SuperSONIC Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Number of Triton Servers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(release)(nv_gpu_utilization{release=~\"sonic-server\", namespace=~\"cms\"})",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "Server Load Metric",
   "type": "timeseries",
   "description": "Metric and threshold configured in `prometheus.serverLoadMetric` and `prometheus.serverLoadThreshold` parameters. Default metric: inference queue latency. Default threshold: 100ms.",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (release) (rate(nv_inference_queue_duration_us{release=~\"sonic-server\"}[30s]) / (rate(nv_inference_exec_count{release=~\"sonic-server\"}[30s]) * 1000 + 0.001))",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "Latency Breakdown",
   "type": "timeseries",
   "description": "Latency components measured by Triton servers, as well as total latency measured at proxy.",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum (rate(nv_inference_compute_infer_duration_us{release=~\"sonic-server\", namespace=~\"cms\"}[15s])) / sum ((rate(nv_inference_exec_count{release=~\"sonic-server\", namespace=~\"cms\"}[15s]) * 1000))",
     "legendFormat": "Inference"
    },
    {
     "expr": "sum (rate(nv_inference_queue_duration_us{release=~\"sonic-server\", namespace=~\"cms\"}[15s])) / sum ((rate(nv_inference_exec_count{release=~\"sonic-server\", namespace=~\"cms\"}[15s]) * 1000))",
     "legendFormat": "Queue"
    },
    {
     "expr": "sum (rate(nv_inference_compute_input_duration_us{release=~\"sonic-server\", namespace=~\"cms\"}[15s])) / sum ((rate(nv_inference_exec_count{release=~\"sonic-server\", namespace=~\"cms\"}[15s]) * 1000))",
     "legendFormat": "Input"
    },
    {
     "expr": "sum (rate(nv_inference_compute_output_duration_us{release=~\"sonic-server\", namespace=~\"cms\"}[15s])) / sum ((rate(nv_inference_exec_count{release=~\"sonic-server\", namespace=~\"cms\"}[15s]) * 1000))",
     "legendFormat": "Output"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_rq_time_sum{envoy_http_conn_manager_prefix=\"ingress_grpc\", release=~\"sonic-server\", namespace=~\"cms\"}[15s])) / sum(rate(envoy_http_downstream_rq_time_count{envoy_http_conn_manager_prefix=\"ingress_grpc\", release=~\"sonic-server\", namespace=~\"cms\"}[15s]))",
     "legendFormat": "Total (measured at proxy)"
    }
   ]
  },
  {
   "title": "Number of Triton Servers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "count by(release)(nv_gpu_utilization{release=~\"sonic-server\", namespace=~\"cms\"})",
     "legendFormat": "{{release}}"
    }
   ]
  },
  { "title": "GPU Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "GPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nv_gpu_utilization{namespace=~\"cms\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GPU power usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(nv_gpu_power_usage{namespace=~\"cms\"} / nv_gpu_power_limit{namespace=~\"cms\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GPU memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nv_gpu_memory_used_bytes{namespace=~\"cms\"}/nv_gpu_memory_total_bytes{namespace=~\"cms\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Inference Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Inferences per second (all servers, all models)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate(nv_inference_count{release=~\"sonic-server\", namespace=~\"cms\"}[15s])) by(release)",
     "legendFormat": "{{ release }}"
    }
   ]
  },
  {
   "title": "Inferences per second by server (all models)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate(nv_inference_count{release=~\"sonic-server\", namespace=~\"cms\"}[15s])) by(pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Inferences per second by model (all servers)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate(nv_inference_count{release=~\"sonic-server\", namespace=~\"cms\"}[15s])) by(model)",
     "legendFormat": "{{ model }}"
    }
   ]
  }
 ]
}