apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-thanos-metrics-reader
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-thanos-metrics-reader
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-thanos
