apiVersion: batch/v1
kind: CronJob
metadata:
  name: af-users-graph-updater
  namespace: cms
spec:
  schedule: "0 */6 * * *" # every 6 hours
  concurrencyPolicy: Forbid
  suspend: true
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          nodeSelector: { "cms-af-prod": "true" }
          tolerations:
            - key: "hub.jupyter.org/dedicated"
              operator: "Equal"
              value: "cms-af"
              effect: "NoSchedule"
          containers:
            - name: updater
              image: python:3.11-slim
              command: ["/bin/bash", "-c"]
              args:
                - |
                  pip install --no-cache-dir matplotlib mplhep pandas
                  python /scripts/plot-af-users.py
              resources:
                requests:
                  cpu: 500m
                  memory: 1Gi
                limits:
                  cpu: 1
                  memory: 2Gi
              volumeMounts:
                - name: img-vol
                  mountPath: /data
                - name: script
                  mountPath: /scripts
                - name: depot
                  mountPath: /depot/cms
                  mountPropagation: HostToContainer
          volumes:
            - name: img-vol
              persistentVolumeClaim:
                claimName: af-users-graph-pvc
            - name: script
              configMap:
                name: af-users-graph-script
            - name: depot
              nfs:
                server: datadepot.rcac.purdue.edu
                path: /depot/cms
