apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: af-users-graph
resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cronjob.yaml
configMapGenerator:
  - name: af-users-graph-script
    files:
      - plot-af-users.py
    options:
      disableNameSuffixHash: true
  - name: af-users-graph-nginx-config
    files:
      - nginx.conf
    options:
      disableNameSuffixHash: true
