apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub
spec:
  interval: 1m
  chart:
    spec:
      chart: jupyterhub
      version: "4.0.0"
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: jupyterhub-config
      valuesKey: values.yaml
  upgrade:
    remediation:
      retries: -1
  install:
    remediation:
      retries: -1
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: "hub"
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: hub
              spec:
                template:
                  spec:
                    enableServiceLinks: false
