apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: munge-key
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  storageClassName: ${multinode_storage_class}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
