apiVersion: v1
kind: Secret
metadata:
  name: servicex-rabbitmq-password
type: Opaque
stringData:
  rabbitmq-password: ENC[AES256_GCM,data:nW2ezRj0q6i1iFhP781KNoFvGi+LqHHQxXKz2kpp11E=,iv:7pbOUqphDRb19WSoUAQp77VKZMJ2UsSy1PzcXt4y95Y=,tag:7SO+/bes9aBAv/04Y47JBw==,type:str]
sops:
  age:
    - recipient: age1pccfws6yghzqtg5v9228nrvs23w5thsxpr7w4kmmksn435ldev5sqkpj08
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRURZenpsZ2VuOVhjaHQ5
        OTgyTHExVHp3ZnhOcWVTY0NCR0plYVRvUEQwClpoTDhiQ044T0lDRzRLQ1F0dHNt
        YktoZnIyYlhud0hSNE1GRDRZYUNCeGMKLS0tIHZ0SjMxeUM5bVBXOXJMNGhVaVlK
        ZkJlN1dHYVp3RWxCRzk4Ym9TMmEyWncKHZaNo2NX2oM0JE/H/OayBHdGj4OevAFU
        ar6KlfYVbwlBdwgxb4EZxllUJK878+ps9JE9wLcgNmW9bkfwxLcsbA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-24T20:18:12Z"
  mac: ENC[AES256_GCM,data:fodIE/g2IFY8P75YFi1qIpMEFfWCZPixopCy80KfdJ2AAlcakPX+IAysxX9Y7FW5l3CkPc4FbCbB7hxvMluz/XE/tPBfmp2dggjMT7BMQyuioz0m2/mmpdyou6RfjTwKJ5zIiSSvkwjGECDaHjFK36ZOalWGe3U5HAvKOW1d1LM=,iv:3jzXFZGYAoLOcD2Zd45qx6NkDimOw4l3b0wk8Qm0pVY=,tag:fwnvZTr+McApIcIP2P8wdw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
