apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: cms
spec:
  interval: 1m
  chart:
    spec:
      chart: jupyterhub
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
        namespace: cms
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: jupyterhub-config
      valuesKey: values.yaml
