apiVersion: v1
kind: Secret
metadata:
  name: servicex-secrets-anvil
  namespace: cms
type: Opaque
data:
  accesskey: ENC[AES256_GCM,data:r49tw1JmGlW4hGTKvHt3bfmhIO+aeec+0y1P4g==,iv:kDp4OxiipPW+L1eaMiwubN9H8KmIQfawJFuMKug5/60=,tag:zMPxL+iXK2OcRW0kg5jz0Q==,type:str]
  flaskSecretKey: ""
  jwtSecretKey: ""
  mailgunAPIKey: ""
  oauthClientID: ""
  oauthClientSecret: ""
  oauthMetadataURL: ""
  postgresql-password: ENC[AES256_GCM,data:QYMh2fYVhTveCmF7,iv:vPzP0qdIPLpb7/R+st8MqTEYB8MImFJUEk4Nv/s/xQQ=,tag:FduPToUUGpZKOkZqZdm8ZA==,type:str]
  rabbitmq-password: ENC[AES256_GCM,data:n/wp/zv1jyHI+Kib,iv:8QOL+grDapsw6N0dYVkTdLyE/Gr9wrGLBv1NEcQWLdc=,tag:MaFYHrcoxV0o+bRzyW1aUg==,type:str]
  secretkey: ENC[AES256_GCM,data:8dCCs7YQx6QfyXRupSxZH9eZ6hGkKWcNgA4D3bH3KgtKUYDKq3w4PrY0gGJiCMEmIchF6vSJm5g=,iv:2fqmxxrVCGVNpJRU2NpMx8AxPPCCtgqeqLz8NJPMoAs=,tag:4DeaWIyCml+/AyNicsKMew==,type:str]
  slackSigningSecret: ""
  slackSignupWebhook: ""
sops:
  age:
    - recipient: age1pccfws6yghzqtg5v9228nrvs23w5thsxpr7w4kmmksn435ldev5sqkpj08
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSVhBY2d4MkJkVThEdGFy
        QVdoTjZKbWhNb0hpNTJId0g0aEtxeWZJTFg4CkJoNlJSblNJb1JROUJXM1dlejd6
        UUxIbUNJRElCU0Q4ME9hOUdFQkhpNEEKLS0tIEFTZStQRXcxcmFacTdkWTJ5YWZJ
        Q2JwRXBncXBIQlBaeUY3RXJOM3FRbk0K8h05NYBH2H+JuUUxzzyniXltY65fcmz5
        +tv+SD80OMqA1M1jlcQViGmDePNVyQG6Q0p3HssDHmB9mfThgbiK6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-30T18:20:10Z"
  mac: ENC[AES256_GCM,data:xS5itSqCEo31u9KA2gvW2t2Gd/jQXOXuKqvh0Qy7Ea9V7tHW/xKoGcHkQaRqeYioIqwD4mBMOsmG77QmkADLdL5M7rSPba+lDWJddwIoqxNUMgy6AcD6zozONzh4XyZF+yzl/xUxjv/3VcuWBrvcXqOXlY/zwWSe55QwbPZvIqE=,iv:oj5LliapOWPXXICCENo03SJ8VsuOI9GwO76V3yGdgLE=,tag:OhjYC31/g0RBnUoI3qIsZQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
