apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: cms
spec:
  interval: 1m
  chart:
    spec:
      chart: alertmanager
      version: "1.23.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: cms
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-alerts-config
      valuesKey: values.yaml
