[realms]
 CERN.CH = {
  default_domain = cern.ch
  kpasswd_server = cerndc.cern.ch
  admin_server = cerndc.cern.ch
  kdc = cerndc.cern.ch
  dns_lookup_kdc = false

  v4_name_convert = {
     host = {
         rcmd = host
     }
  }
 }
