apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: cms-dev
data:
  grafana.ini: | 
    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Viewer
    hide_version = true
