namespace: cms

deployment:
  image: geddes-registry.rcac.purdue.edu/docker-hub-cache/grafana/grafana:latest
  replicas: 1
  nodeSelector:
    "cms-af-prod": "true"
  resources:
    requests:
      cpu: 2000m
      memory: 4Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  storagePath: /var/lib/grafana
  configPath: /etc/grafana
  tolerations:
    - key: "hub.jupyter.org/dedicated"
      operator: "Equal"
      value: "cms-af"
      effect: "NoSchedule"

networking:
  externalPort: 3000
  containerPort: 3000
  nodePort: 32000

pvc:
  storageClassName: geddes-standard-multinode
  storageRequest: 10Gi
  storageAccessModes: ["ReadWriteMany"]

config:
  useIngress: true
  hostname: cms.geddes.rcac.purdue.edu
  grafanaini: |
    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Viewer
    hide_version = true
    [server]
    domain = cms.geddes.rcac.purdue.edu
    root_url = https://cms.geddes.rcac.purdue.edu/grafana/
    serve_from_sub_path = true
  datasources: |
    {
        "apiVersion": 1,
        "datasources": [
            {
                "access":"proxy",
                "editable": true,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus-service.cms.geddes.rcac.purdue.edu:8080",
                "version": 1
            },
            {
                "access":"proxy",
                "editable": true,
                "name": "prometheus-rancher",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://rancher-monitoring-prometheus.cattle-monitoring-system:9090",
                "version": 1
            }
        ]
    }
