apiVersion: v1
kind: Service
metadata:
  name: slurm-probes
  labels:
    app: slurm-probes
spec:
  selector:
    app: slurm-probes
  ports:
    - name: metrics
      port: 9100
      targetPort: metrics
