apiVersion: batch/v1
kind: CronJob
metadata:
  name: af-userlist-sync-cern
spec:
  schedule: "*/30 * * * *" # Run every 30 minutes
  concurrencyPolicy: Forbid
  suspend: false
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          enableServiceLinks: false
          serviceAccountName: af-userlist-sync
          restartPolicy: Never
          nodeSelector: { "cms-af-prod": "true" }
          tolerations:
            - key: "hub.jupyter.org/dedicated"
              operator: "Equal"
              value: "cms-af"
              effect: "NoSchedule"
          containers:
            - name: af-userlist-sync-cern
              image: geddes-registry.rcac.purdue.edu/docker-hub-cache/library/rockylinux:8.9
              command: [/bin/bash, /scripts/sync-userlist.sh, cern]
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "100m"
                limits:
                  memory: "512Mi"
                  cpu: "500m"
              volumeMounts:
                - name: af-x509-proxy
                  mountPath: /etc/grid-security-ro
                  readOnly: true
                - name: scripts
                  mountPath: /scripts
                  readOnly: true
          volumes:
            - name: af-x509-proxy
              secret:
                secretName: ${x509_secret_name}
            - name: scripts
              configMap:
                name: af-userlist-sync-scripts
