apiVersion: v1
kind: ServiceAccount
metadata:
  name: af-userlist-sync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: af-userlist-sync-secret-manager
subjects:
  - kind: ServiceAccount
    name: af-userlist-sync
roleRef:
  kind: Role
  name: secret-manager
  apiGroup: rbac.authorization.k8s.io
