apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: interlink-cache
spec:
  storageClassName: geddes-standard-multinode
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 12Gi
