apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: interlink-cache
  namespace: cms
spec:
  storageClassName: depot-cloud-filesystem
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 12Gi
