apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: supersonic
  namespace: cms
spec:
  interval: 1m
  url: https://github.com/interlink-hq/interlink-helm-chart
  ref:
    branch: main
