apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: interlink
  namespace: cms
spec:
  interval: 1m
  chart:
    spec:
      # chart: interlink
      # version: "0.5.0"
      # sourceRef:
      #   kind: GitRepository
      #   name: interlink
      #   namespace: cms
      chart: interlink
      version: "0.5.0"
      sourceRef:
        kind: HelmRepository
        name: interlink
        namespace: cms
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: interlink-config
      valuesKey: values.yaml
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: "interlink-hammer-node"
            patch: |
              - op: add
                path: /spec/template/spec/initContainers
                value:
                  - name: chmod-var-run
                    image: busybox:1.35
                    command: ["sh", "-c", "chmod 777 /var/run"]
                    volumeMounts:
                      - name: sockets
                        mountPath: /var/run
                    securityContext:
                      runAsUser: 0
