apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: interlink
  namespace: cms
spec:
  interval: 1m
  chart:
    spec:
      # chart: interlink
      # version: "0.5.0"
      # sourceRef:
      #   kind: GitRepository
      #   name: interlink
      #   namespace: cms
      chart: interlink
      version: "0.5.2"
      sourceRef:
        kind: HelmRepository
        name: interlink
        namespace: cms
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: interlink-config
      valuesKey: values.yaml
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: "interlink-hammer-node"
            patch: |
              - op: add
                path: /spec/template/spec/volumes/-
                value:
                  name: munge-key
                  secret:
                    secretName: munge-key
              - op: add
                path: /spec/template/spec/containers/0/volumeMounts/-
                value:
                  name: munge-key
                  mountPath: /etc/munge
                  readOnly: true
