apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: interlink
  namespace: cms
spec:
  interval: 1m
  chart:
    spec:
      chart: interlink
      version: "0.5.0"
      sourceRef:
        kind: HelmRepository
        name: interlink
        namespace: cms
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: interlink-config
      valuesKey: values.yaml 