apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - cache-pvc.yaml
configMapGenerator:
  - name: interlink-config
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
