apiVersion: v1
kind: Pod
metadata:
  name: test-interlink-hammer
  annotations:
    slurm-job.vk.io/singularity-options: "--unsquash --bind /cvmfs"
    slurm-job.vk.io/flags: "--uid=616617 -A cms -p hammer-nodes"
spec:
  nodeSelector:
    kubernetes.io/hostname: interlink-hammer
  tolerations:
    - key: virtual-node.interlink/no-schedule
      operator: Exists
  volumes:
    - name: slurm-data
      nfs:
        server: datadepot.rcac.purdue.edu
        path: /depot/itap/interlink
  containers:
    - name: test
      image: busybox:1.35
      command: ["sh", "-c"]
      args:
        - |
          echo 'Hello from virtual node interlink-hammer!'
          sleep 300
      volumeMounts:
        - name: slurm-data
          mountPath: /depot/itap/interlink/
      resources:
        requests:
          memory: "100M"
          cpu: "250m"
        limits:
          memory: "200M"
          cpu: "1"
      readinessProbe:
        exec:
          command:
            - sh
            - -c
            - "true"
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 30
      startupProbe:
        exec:
          command:
            - sh
            - -c
            - "true"
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 30
      # livenessProbe:
      #   exec:
      #     command:
      #       - sh
      #       - -c
      #       - "true"
      #   initialDelaySeconds: 10
      #   periodSeconds: 10
      #   timeoutSeconds: 1
      #   successThreshold: 1
      #   failureThreshold: 30
  restartPolicy: Never
