apiVersion: v1
kind: Pod
metadata:
  name: test-interlink-hammer
  annotations:
    # slurm-job.vk.io/pre-exec:
    slurm-job.vk.io/singularity-options: "--unsquash --bind /cvmfs"
    slurm-job.vk.io/flags: "--uid=616617 -A cms -p hammer-nodes --gres=gpu:1"
spec:
  nodeSelector:
    kubernetes.io/hostname: interlink-hammer
  tolerations:
    - key: virtual-node.interlink/no-schedule
      operator: Exists
  volumes:
    - name: slurm-data
      nfs:
        server: datadepot.rcac.purdue.edu
        path: /depot/cms/purdue-af/interlink
  containers:
    - name: test
      image: busybox:1.35
      command: ["sh", "-c"]
      args:
        - |
          echo 'Hello from virtual node interlink-hammer!'
          ls -l /cvmfs/cms.cern.ch/el9_amd64_gcc12/cms/cmssw/CMSSW_14_1_0_pre7/external/el9_amd64_gcc12/data/RecoBTag/Combined/
          sleep 300
      volumeMounts:
        - name: slurm-data
          mountPath: /depot/cms/purdue-af/interlink/
      resources:
        requests:
          memory: "100M"
          cpu: "250m"
        limits:
          memory: "200M"
          cpu: "1"
  restartPolicy: Never
