apiVersion: v1                    
kind: Pod
metadata:
  name: test-interlink-hammer       
  namespace: cms                  
spec:   
  nodeSelector:                   
    kubernetes.io/hostname: interlink-hammer      
  containers:                     
  - name: test                    
    image: busybox:1.35           
    command: ["sh", "-c"]         
    args: ["echo 'Hello from virtual node interlink-incluster-node!' && sleep 300"]   
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "2Gi"
        cpu: "2"
  restartPolicy: Never  