apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub-ssh
spec:
  interval: 5m
  chart:
    spec:
      chart: jupyterhub-ssh
      version: "0.0.1-0.dev.git.142.h402a3d6"
      sourceRef:
        kind: HelmRepository
        name: jupyterhub-ssh
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: jupyterhub-ssh-config
      valuesKey: values.yaml
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: "jupyterhub-sftp.*"
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: doesNotMatter
              spec:
                selector:
                  matchLabels:
                    app.kubernetes.io/instance: cmshub-ssh
                    app.kubernetes.io/name: jupyterhub-ssh
                template:
                  spec:
                    volumes:
                    - name: cvmfs
                      persistentVolumeClaim:
                        claimName: cvmfs
                    - name: eos
                      hostPath: 
                        path: /eos
                    - name: depot
                      nfs:
                        server: datadepot.rcac.purdue.edu
                        path: /depot/cms
                    containers:
                    - name: server
                      securityContext:
                        privileged: false
                      volumeMounts:
                      - name: cvmfs
                        mountPath: /cvmfs
                        mountPropagation: HostToContainer
                      - name: eos
                        mountPath: /eos
                        mountPropagation: HostToContainer
                      - name: depot
                        mountPath: /depot/cms
                        mountPropagation: HostToContainer
