{{ if .Values.http_ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: nginx
  name: {{ .Release.Name }}-http
spec:
  rules:
  - host: {{ .Release.Name }}.{{ .Values.namespace }}.geddes.rcac.purdue.edu
    # host: {{ .Release.Name }}.{{ default .Values.frontendIP "127.0.0.1" }}.nip.io
    http:
      paths:
      - path: ''
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "triton.fullname" . }}-triton
            port:
              number: 8000
{{ end }}
