apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: nginx
  name: {{ .Release.Name }}-metrics
spec:
  rules:
  - host: {{ required "metrics.hostname is required!" .Values.metrics.hostname }}
    http:
      paths:
      - path: ''
        pathType: ImplementationSpecific
        backend:
          service:
            # name: {{ include "triton.fullname" . }}
            name: {{ .Release.Name }}-triton
            port:
              number: 8002
