apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "triton.fullname" . }}-models
  labels:
    {{- include "triton.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

