apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-triton
  labels:
    app: {{ .Release.Name }}-triton
    scrape_metrics: "true"
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-triton
  ports:
  - name: 8001-tcp
    port: 8001
    targetPort: 8001
  - name: 8000-tcp
    port: 8000
    targetPort: 8000
  - name: 8002-tcp
    port: 8002
    targetPort: 8002
