apiVersion: batch/v1
kind: CronJob
metadata:
  name: jupyterhub-database-backup
spec:
  schedule: "0 0,12 * * *" # Run at midnight and noon every day
  concurrencyPolicy: Forbid
  suspend: false
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          enableServiceLinks: false
          serviceAccountName: database-backup
          securityContext:
            runAsUser: 616617
          nodeSelector: { "cms-af-prod": "true" }
          tolerations:
            - key: "hub.jupyter.org/dedicated"
              operator: "Equal"
              value: "cms-af"
              effect: "NoSchedule"
          containers:
            - name: database-backup
              image: alpine/kubectl:1.34.1
              securityContext:
                runAsUser: 616617
              command: [/bin/sh, /scripts/backup-database.sh]
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "100m"
                limits:
                  memory: "256Mi"
                  cpu: "200m"
              volumeMounts:
                - name: depot
                  mountPath: /depot/cms
                  mountPropagation: HostToContainer
                - name: scripts
                  mountPath: /scripts
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: scripts
              configMap:
                name: database-backup-scripts
            - name: depot
              nfs:
                server: datadepot.rcac.purdue.edu
                path: /depot/cms
