apiVersion: batch/v1
kind: CronJob
metadata:
  name: jupyterhub-database-backup
spec:
  schedule: "0 0,12 * * *" # Run at midnight and noon every day
  suspend: false
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          enableServiceLinks: false
          serviceAccountName: database-backup
          securityContext:
            runAsUser: 616617
          nodeSelector: { "cms-af-prod": "true" }
          tolerations:
            - key: "hub.jupyter.org/dedicated"
              operator: "Equal"
              value: "cms-af"
              effect: "NoSchedule"
          containers:
            - name: database-backup
              image: alpine/kubectl:1.34.1
              securityContext:
                runAsUser: 616617
              command:
                - /bin/sh
                - -c
                - |
                  set -euo pipefail
                  
                  echo "Starting database backup at $$(date)"
                  
                  # List available pods for debugging
                  echo "Searching for JupyterHub hub pods..."
                  kubectl get pods -n cms -l app=jupyterhub,component=hub

                  # Find the JupyterHub hub pod
                  HUB_POD=$$(kubectl get pods -n cms -l app=jupyterhub,component=hub -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)

                  if [ -z "$$HUB_POD" ]; then
                    echo "ERROR: Could not find JupyterHub hub pod"
                    echo "Available pods in namespace cms:"
                    kubectl get pods -n cms | grep -i hub || echo "No hub pods found"
                    exit 1
                  fi

                  echo "Found hub pod: $$HUB_POD"

                  # Get current timestamp for filename
                  if [ "$$(date +%H)" -lt 12 ]; then
                    TIMESTAMP="midnight"
                  else
                    TIMESTAMP="noon"
                  fi

                  YEAR=$$(date +%Y)
                  MONTH=$$(date +%b | tr '[:upper:]' '[:lower:]')
                  DAY=$$(date +%d)
                  BACKUP_FILENAME="jupyterhub-$${YEAR}$${MONTH}$${DAY}-$${TIMESTAMP}.sqlite"
                  BACKUP_PATH="/depot/cms/purdue-af/backups/$${BACKUP_FILENAME}"

                  echo "Backup filename: $${BACKUP_FILENAME}"
                  echo "Backup path: $${BACKUP_PATH}"

                  # Create backup directory if it doesn't exist
                  mkdir -p /depot/cms/purdue-af/backups

                  # Verify the database file exists in the pod
                  echo "Checking if database file exists in pod..."
                  if ! kubectl exec -n cms "$$HUB_POD" -- test -f /srv/jupyterhub/jupyterhub.sqlite; then
                    echo "ERROR: Database file /srv/jupyterhub/jupyterhub.sqlite does not exist in pod $$HUB_POD"
                    echo "Checking for alternative database locations..."
                    kubectl exec -n cms "$$HUB_POD" -- find /srv -name "*.sqlite" -o -name "jupyterhub.db" 2>/dev/null || echo "No database files found"
                    exit 1
                  fi

                  # Copy the database file from the pod
                  echo "Copying database from pod $$HUB_POD to $${BACKUP_PATH}..."
                  if ! kubectl cp "cms/$$HUB_POD:/srv/jupyterhub/jupyterhub.sqlite" "$${BACKUP_PATH}"; then
                    echo "ERROR: Failed to copy database from pod"
                    exit 1
                  fi

                  # Check if the backup file exists and has content
                  if [ -f "$${BACKUP_PATH}" ] && [ -s "$${BACKUP_PATH}" ]; then
                    echo "Database backup completed successfully: $${BACKUP_PATH}"
                    
                    # Keep only the last 5 backups
                    echo "Cleaning up old backups (keeping last 5)..."
                    cd /depot/cms/purdue-af/backups
                    ls -t jupyterhub-*.sqlite | tail -n +6 | xargs -r rm -f
                    
                    echo "Backup cleanup completed"
                    echo "Current backups:"
                    ls -la jupyterhub-*.sqlite 2>/dev/null || echo "No backups found"
                  else
                    echo "WARNING: Database file is empty or does not exist, removing backup file"
                    rm -f "$${BACKUP_PATH}"
                    exit 1
                  fi

                  echo "Database backup job completed at $$(date)"
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "100m"
                limits:
                  memory: "256Mi"
                  cpu: "200m"
              volumeMounts:
                - name: depot
                  mountPath: /depot/cms
                  mountPropagation: HostToContainer
          restartPolicy: OnFailure
          volumes:
            - name: depot
              nfs:
                server: datadepot.rcac.purdue.edu
                path: /depot/cms
