FROM geddes-registry.rcac.purdue.edu/docker-hub-cache/sslhep/servicex_science_image_combined_root:5.7.2-6.38.04

USER root
RUN bash -lc 'python -m pip install --no-cache-dir coffea==2026.4.0'

USER output
