apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-conf
  namespace: cms
data:
  ldap.conf: |
    #
    # LDAP Defaults
    #

    # See ldap.conf(5) for details
    # This file should be world readable but not world writable.

    BASE dc=rcac,dc=purdue,dc=edu
    URI ldap://cms-aux.rcac.purdue.edu/ ldap://centralservices.rcac.purdue.edu/
    TLS_CACERT      /etc/certs/cacert.pem
    TLS_CACERTDIR /etc/openldap/cacerts 