apiVersion: batch/v1
kind: CronJob
metadata:
  name: af-userlist-sync
  namespace: cms
spec:
  schedule: "*/5 * * * *"  # Run every 5 minutes
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: af-userlist-sync
          restartPolicy: Never
          containers:
          - name: af-userlist-sync
            image: rockylinux:8.9
            command:
            - /bin/bash
            - -c
            - |
              SECRET_NAME=purdue-auth

              dnf install -y openldap-clients curl --nogpgcheck
              
              # Install kubectl directly from binary
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
              chmod +x kubectl
              mv kubectl /usr/local/bin/
              
              # Get Purdue users
              echo "Fetching Purdue users..."
              ldapsearch -x host=hammer.rcac.purdue.edu | grep uid: | cut -d " " -f2 > /tmp/purdue-auth.txt
              echo "Purdue users:"
              cat /tmp/purdue-auth.txt
              
              # Validate the data before updating secret
              if [ -s /tmp/purdue-auth.txt ]; then
                # Check if the data looks reasonable (at least 100 users, typical for Purdue)
                USER_COUNT=$(wc -l < /tmp/purdue-auth.txt)
                echo "Found $USER_COUNT users"
                
                if [ $USER_COUNT -lt 200 ]; then
                  echo "ERROR: Only $USER_COUNT users found - this seems too low for Purdue LDAP"
                  echo "This might indicate a problem with the LDAP query or server"
                  echo "Job will fail to prevent data loss"
                  exit 1
                fi
                
                # Validate that each line looks like a valid username (no spaces, reasonable length)
                if grep -q " " /tmp/purdue-auth.txt || grep -q "^$" /tmp/purdue-auth.txt; then
                  echo "ERROR: Invalid data format detected in user list"
                  echo "Job will fail to prevent data loss"
                  exit 1
                fi
                
                echo "Purdue users list validation passed, updating $SECRET_NAME secret..."
                
                # Check if secret already exists
                if kubectl get secret $SECRET_NAME >/dev/null 2>&1; then
                  echo "Secret exists, updating it..."
                  # Update existing secret
                  if ! kubectl patch secret $SECRET_NAME \
                    --type='merge' \
                    -p="{\"data\":{\"purdue-users\":\"$(base64 -w0 /tmp/purdue-auth.txt)\"}}"; then
                    echo "ERROR: Failed to update secret"
                    exit 1
                  fi
                else
                  echo "Secret does not exist, creating it..."
                  # Create new secret
                  if ! kubectl create secret generic $SECRET_NAME \
                    --from-file=purdue-users=/tmp/purdue-auth.txt; then
                    echo "ERROR: Failed to create secret"
                    exit 1
                  fi
                fi
                
                echo "Secret $SECRET_NAME updated successfully"
              else
                echo "ERROR: Purdue users list is empty - this indicates a problem with LDAP connection or data retrieval"
                echo "Job will fail to prevent data loss"
                exit 1
              fi
              
              # Get CERN CMS users
              # echo "Fetching CERN CMS users..."
              # wget --no-check-certificate \
              #   --certificate=/etc/grid-security-ro/x509up \
              #   --private-key=/etc/grid-security-ro/x509up \
              #   https://voms2.cern.ch:8443/voms/cms/services/VOMSCompatibility?method=getGridmapUsers \
              #   -O /tmp/grid-mapfile.xml
              # sleep 60
              # xmllint --format /tmp/grid-mapfile.xml | \
              #   grep 'getGridmapUsersReturn xsi:type' | \
              #   cut -d '>' -f2 | \
              #   cut -d '<' -f1 | \
              #   grep "OU=Users" | \
              #   cut -d "=" -f6 | \
              #   cut -d "/" -f1 > /tmp/cern-auth.txt
              # echo "CERN users:"
              # cat /tmp/cern-auth.txt
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "500m"
            volumeMounts:
            # - name: x509-proxy
            #   mountPath: /etc/grid-security-ro
            #   readOnly: true
            - name: ldap-conf
              mountPath: /etc/openldap/ldap.conf
              subPath: ldap.conf
            # - name: ldap-conf
            #   mountPath: /etc/pki
            #   subPath: pki
          volumes:
          # - name: x509-proxy
          #   secret:
          #     secretName: x509-proxy# In your CronJob spec:
          - name: ldap-conf
            configMap:
              name: ldap-conf