apiVersion: batch/v1
kind: CronJob
metadata:
  name: af-userlist-sync
  namespace: cms
spec:
  schedule: "*/5 * * * *"  # Run every 5 minutes
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: af-userlist-sync
            image: ubuntu:22.04
            command:
            - /bin/bash
            - -c
            - |
              apt-get update && apt-get install -y ldap-utils wget libxml2-utils
              
              # Get Purdue users
              echo "Fetching Purdue users..."
              ldapsearch -x host=hammer.rcac.purdue.edu | grep uid: | cut -d " " -f2 > /tmp/purdue-auth.txt
              echo "Purdue users:"
              cat /tmp/purdue-auth.txt
              
              # Get CERN CMS users
              echo "Fetching CERN CMS users..."
              wget --no-check-certificate \
                --certificate=/etc/grid-security-ro/x509up \
                --private-key=/etc/grid-security-ro/x509up \
                https://voms2.cern.ch:8443/voms/cms/services/VOMSCompatibility?method=getGridmapUsers \
                -O /tmp/grid-mapfile.xml
              sleep 60
              xmllint --format /tmp/grid-mapfile.xml | \
                grep 'getGridmapUsersReturn xsi:type' | \
                cut -d '>' -f2 | \
                cut -d '<' -f1 | \
                grep "OU=Users" | \
                cut -d "=" -f6 | \
                cut -d "/" -f1 > /tmp/cern-auth.txt
              echo "CERN users:"
              cat /tmp/cern-auth.txt
            volumeMounts:
            # - name: x509-proxy
            #   mountPath: /etc/grid-security-ro
            #   readOnly: true
            - name: ldap-conf
              mountPath: /mnt/data/openldap
              subPath: openldap
            - name: ldap-conf
              mountPath: /mnt/data/pki
              subPath: pki
          volumes:
          # - name: x509-proxy
          #   secret:
          #     secretName: x509-proxy# In your CronJob spec:
          - name: ldap-conf
            persistentVolumeClaim:
              claimName: ldap-conf