apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build-job
  namespace: cms
spec:
  backoffLimit: 0
  completions: 1
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
          - "--context=git://github.com/PurdueAF/purdue-af.git"
          - "--context-sub-path=docker/cmsaf-alma8/"
          - "--dockerfile=Dockerfile"
          - "--destination=geddes-registry.rcac.purdue.edu/cms/cmsaf-alma8:0.10.4"
          - "--cache=true"
          # - "--no-push"
        resources:
          requests:
            memory: "256Gi"
            cpu: "16"
            # nvidia.com/mig-7g.40gb: 1
          limits:
            memory: "256Gi"
            cpu: "16"
            # nvidia.com/mig-/7g.40gb: 1
        volumeMounts:
          - name: docker-config
            mountPath: /kaniko/.docker/
      restartPolicy: Never
      volumes:
        - name: docker-config
          secret:
            secretName: docker-config
      nodeSelector:
        cms-af-prod: 'true'
      tolerations:
        - key: "hub.jupyter.org/dedicated"
          operator: "Equal"
          value: "cms-af"
          effect: "NoSchedule"
