{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "modelManager.authSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "modelManager.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.auth.username | quote }}
  password: {{ .Values.auth.password | quote }}
{{- end }}
