# Chart source for supersonic, supersonic-af and supersonic-interlink.
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: supersonic
spec:
  interval: 1m
  url: https://github.com/fastmachinelearning/SuperSONIC
  ref:
    branch: main
