apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-af-pod-monitor
  labels:
    app: {{ .Release.Name }}-af-pod-monitor
    scrape_metrics: "true"
spec:
  type: ClusterIP
  selector:
    app: jupyterhub
  ports:
  - name: pod-metrics
    port: 9090
    targetPort: 9090
