apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-rb
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-service-account
  apiGroup: rbac.authorization.k8s.io
