apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-metrics
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      scrape-metrics: "true"
  endpoints:
    - port: "metrics"
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-metrics-dask-gateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dask-gateway
  endpoints:
    - port: "dashboard"