apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: conda-store
spec:
  suspend: false
  interval: 1m
  chart:
    spec:
      chart: conda-store-server/install/conda-store
      sourceRef:
        kind: GitRepository
        name: conda-store
      interval: 1m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  valuesFrom:
    - kind: ConfigMap
      name: conda-store-config
      valuesKey: values.yaml
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: PersistentVolumeClaim
              name: conda-store-worker-claim
            patch: |
              - op: add
                path: /spec/storageClassName
                value: geddes-standard-multinode
