#!/bin/bash

#Start time for run time
start_time="$(date +%s%N)"

#Where are the active job files kept?
active_dir=${active_dir:-/var/spool/slurm/active}

#Start time for active file distributing
active_time="$(date +%s%N)"

#clean up active jobs files, delete files from jobs that are not active
#get current jobs on the node
nodejobs=$(/usr/bin/squeue -w $(hostname -s) -o %U-%u-%A.active)

if [[ "$nodejobs" == "" ]]; then
    #there are no other jobs on this node, delete all .active files
    rm -f $active_dir/*
else
    active_files=$(cd $active_dir;echo *active)
    for file in $active_files; do
        jobcheck=$(echo $nodejobs | grep "$file")
        if [[ "$jobcheck" ==  "" ]]; then
            rm -f $active_dir/$file
        fi
    done
fi

# Convert user_name to user_id and generate name and file for procman exemption file
active_file=''
set -- $(id -u $SLURM_JOB_USER)
if [[ $# = 1 ]]; then
    active_file=$active_dir/$1-$SLURM_JOB_USER-$SLURM_JOB_ID.active
    touch $active_file
fi

#end time for active files
#N=nano
N=$(($(date +%s%N) - active_time))
logger -t prolog "$SLURM_JOB_ID $SLURM_JOB_USER Prolog Distribute Active Files: $(printf '%d.%03d\n' $((N/1000000000)) $(((N/1000000)%1000))) seconds."

exit 0
