apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-db
  namespace: cms
spec:
  interval: 1m
  chart:
    spec:
      chart: postgresql
      version: "12.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: cms
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: postgres-db-config
      valuesKey: values.yaml
