apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: postgres-db-config
    namespace: cms
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
