# CloudNative PG Operator Configuration
config:
  clusterWide: true

# Resource limits and requests
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Monitoring configuration
monitoring:
  enabled: true

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000
