apiVersion: v1
kind: ServiceAccount
metadata:
  name: update-knowledge
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: update-knowledge-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: update-knowledge-rolebinding
subjects:
  - kind: ServiceAccount
    name: update-knowledge
roleRef:
  kind: Role
  name: update-knowledge-role
  apiGroup: rbac.authorization.k8s.io
