apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-knowledge-trigger
  namespace: cms
spec:
  schedule: "0 * * * *" # Run every hour
  concurrencyPolicy: Forbid
  suspend: true
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: update-knowledge
          restartPolicy: OnFailure
          nodeSelector: { "cms-af-prod": "true" }
          tolerations:
            - key: "hub.jupyter.org/dedicated"
              operator: "Equal"
              value: "cms-af"
              effect: "NoSchedule"
          containers:
            - name: update-knowledge
              image: python:3.11-slim
              command: ["/bin/bash", "-c"]
              args:
                - |
                  apt-get update && apt-get install -y git
                  pip install --no-cache-dir requests python-dotenv gitpython
                  git clone https://github.com/PurdueAF/purdue-af.git /workspace/repo
                  cd /workspace/repo
                  python /scripts/update_knowledge.py
              resources:
                requests:
                  cpu: 500m
                  memory: 1Gi
                limits:
                  cpu: 1
                  memory: 2Gi
              volumeMounts:
                - name: script
                  mountPath: /scripts
                  readOnly: true
              workingDir: /workspace
              env:
                - name: OPENWEBUI_API_URL
                  value: "https://genai.rcac.purdue.edu/api/" # Update this URL
                - name: KNOWLEDGE_ID
                  value: "2ffc2559-006b-4b1a-bcea-7e3e62243f7c" # Update this ID
                - name: OPENWEBUI_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: update-knowledge-secret
                      key: api-token
          volumes:
            - name: script
              configMap:
                name: update-knowledge-script
