apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: interlink-hammer
spec:
  interval: 1m
  chart:
    spec:
      chart: interlink
      version: "0.6.1"
      sourceRef:
        kind: HelmRepository
        name: interlink
      interval: 1m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  valuesFrom:
    - kind: ConfigMap
      name: interlink-hammer-config
      valuesKey: values.yaml
