apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs
  namespace: cms
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1
  storageClassName: cvmfs
