apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cmshub-ssh
  namespace: cms
spec:
  interval: 5m
  chart:
    spec:
      chart: jupyterhub-ssh
      version: "0.0.1-0.dev.git.142.h402a3d6"
      sourceRef:
        kind: HelmRepository
        name: jupyterhub-ssh
        namespace: cms
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: jupyterhub-ssh-config
    valuesKey: values.yaml
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: "jupyterhub-sftp.*"
            patch: |
              {}