apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
configMapGenerator:
- name: jupyterhub-ssh-config
  namespace: cms
  files:
  - values.yaml
  options:
    disableNameSuffixHash: true
patches:
  - path: patch-sftp-deployment.yaml
    target:
      kind: Deployment
      name: "jupyterhub-sftp.*"