apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
configMapGenerator:
- name: jupyterhub-ssh-config
  namespace: cms
  files:
  - values.yaml
  options:
    disableNameSuffixHash: true
patches:
  - target:
      kind: HelmRelease
      name: cmshub-ssh
    patch: |-
      - op: replace
        path: /spec/postRenderers/0/kustomize/patchesStrategicMerge/0/patch
        value: |
          $(cat patch-sftp-deployment.yaml)