apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonic-interlink
spec:
  interval: 1m
  chart:
    spec:
      chart: supersonic
      version: "0.3.0"
      sourceRef:
        kind: HelmRepository
        name: fastml
      interval: 1m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  valuesFrom:
    - kind: ConfigMap
      name: supersonic-interlink-config
      valuesKey: values.yaml
