apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonic-interlink
spec:
  # suspend: true
  interval: 1m
  chart:
    spec:
      # chart: helm/supersonic
      # sourceRef:
      #   kind: GitRepository
      #   name: supersonic
      chart: supersonic
      version: "0.3.0"
      sourceRef:
        kind: HelmRepository
        name: fastml
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: supersonic-interlink-config
      valuesKey: values.yaml
