apiVersion: batch/v1
kind: Job
metadata:
  name: perf-analyzer-job
  namespace: cms
spec:
  parallelism: 10
  completions: 10
  backoffLimit: 0
  template:
    spec:
      enableServiceLinks: false
      restartPolicy: OnFailure
      containers:
        - name: perf-analyzer
          image: nvcr.io/nvidia/tritonserver:24.11-py3-sdk
          command: ["/bin/bash"]
          args:
            - "-c"
            - |
              echo "Running perf_analyzer..."
              perf_analyzer -m particlenet_AK4_PT -i grpc -u  sonic-interlink:8001 \
                --async -p 1 -b 100 --concurrency-range=1:1  \
                --shape pf_points__0:2,100 --shape pf_features__1:20,100 --shape pf_mask__2:1,100 --shape sv_points__3:2,10 --shape sv_features__4:11,10 --shape sv_mask__5:1,10 \
                --request-count=10000

          resources:
            requests:
              cpu: 1
              memory: "16G"
            limits:
              cpu: 1
              memory: "16G"
