apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: af-users-graph-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: geddes-standard-multinode
