# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
ARG OWNER=jupyter
ARG ROOT_CONTAINER=gitlab-registry.cern.ch/linuxsupport/alma8-base:latest
FROM $ROOT_CONTAINER

LABEL maintainer="Dmitry Kondratyev <dkondra@purdue.edu>"
ARG NB_USER="jovyan"
ARG NB_UID="1000"
ARG NB_GID="100"

# Fix: https://github.com/hadolint/hadolint/wiki/DL4006
# Fix: https://github.com/koalaman/shellcheck/wiki/SC3014
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

USER root

# Install OS dependencies
RUN dnf -y update && \
    dnf -y install epel-release dnf-plugins-core && \
    dnf config-manager --set-enabled powertools && \
    # Install OSG repository
    dnf -y install https://repo.opensciencegrid.org/osg/3.6/osg-3.6-el8-release-latest.rpm && \
    # Install other repositories
    dnf -y install https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/t/tini-0.19.0-1.el8.x86_64.rpm && \
    # Install packages
    dnf -y install \
        'dnf-command(config-manager)' \
        sudo wget perl which git bzip2 \
        openssh-server openssh-clients openssl-devel \
        emacs vim-enhanced jq xterm-resize \
        libXft libXpm libXext libSM mesa-libGL libnsl.x86_64 \
        glibc-locale-source glibc-langpack-en \
        stress apptainer compat-openssl10 \
        s3cmd htop \
        boost-devel diffutils ncurses-compat-libs cmake \
        glibc-static \
        python3-gfal2 && \
    # Add CUDA repository
    dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo && \
    dnf -y install cuda-toolkit-12-2 libcudnn8-8.9.7.29-1+cuda12.2 && \
    dnf clean all && \
    rm -rf /var/cache/dnf && \
    rm /usr/bin/vi && \
    ln -s /usr/bin/vim /usr/bin/vi && \
    localedef -c -f UTF-8 -i en_US en_US.UTF-8

RUN yum install -y vo-client voms-clients vo-client myproxy

# Configure environment
ENV CONDA_DIR=/opt/conda \
    SHELL=/bin/bash \
    NB_USER="${NB_USER}" \
    NB_UID=${NB_UID} \
    NB_GID=${NB_GID} \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8 \
    PATH="/opt/conda/bin:${PATH}" \
    HOME="/home/${NB_USER}"

# Copy a script that we will use to correct permissions after running certain commands
COPY --chown=root:root fix-permissions /usr/local/bin/fix-permissions
RUN chmod a+rx /usr/local/bin/fix-permissions

# Enable prompt color in the skeleton .bashrc before creating the default NB_USER
RUN sed -i 's/^#force_color_prompt=yes/force_color_prompt=yes/' /etc/skel/.bashrc && \
    echo 'eval "$(command conda shell.bash hook 2> /dev/null)"' >> /etc/skel/.bashrc

# Create NB_USER with UID=1000 and GID=100, and set permissions
RUN echo "auth requisite pam_deny.so" >> /etc/pam.d/su && \
    sed -i.bak -e 's/^%admin/#%admin/' /etc/sudoers && \
    sed -i.bak -e 's/^%sudo/#%sudo/' /etc/sudoers && \
    useradd -l -m -s /bin/bash -N -u "${NB_UID}" "${NB_USER}" && \
    mkdir -p "${CONDA_DIR}" && \
    chown "${NB_USER}:${NB_GID}" "${CONDA_DIR}" && \
    chmod g+w /etc/passwd && \
    fix-permissions "${HOME}" && \
    fix-permissions "${CONDA_DIR}"

USER ${NB_USER}

# Pin python version here, or set it to "default"
ARG PYTHON_VERSION=3.10

# Setup work directory for backward-compatibility
RUN mkdir -p "/home/${NB_USER}/work" && \
    fix-permissions "/home/${NB_USER}"

# Download and install Micromamba, and initialize Conda prefix
COPY --chown="${NB_USER}:${NB_GID}" initial-condarc "${CONDA_DIR}/.condarc"
WORKDIR /tmp
RUN set -x  && \
    wget -qO /tmp/micromamba.tar.bz2 "https://micromamba.snakepit.net/api/micromamba/linux-64/latest" && \
    tar -xvjf /tmp/micromamba.tar.bz2 --strip-components=1 bin/micromamba && \
    rm /tmp/micromamba.tar.bz2 && \
    PYTHON_SPECIFIER="python=${PYTHON_VERSION}" && \
    if [[ "${PYTHON_VERSION}" == "default" ]]; then PYTHON_SPECIFIER="python"; fi && \
    ./micromamba install \
        --root-prefix="${CONDA_DIR}" \
        --prefix="${CONDA_DIR}" \
        --yes \
        "${PYTHON_SPECIFIER}" \
        'mamba' \
        'jupyter_core' && \
    rm micromamba && \
    mamba list python | grep '^python ' | tr -s ' ' | cut -d ' ' -f 1,2 >> "${CONDA_DIR}/conda-meta/pinned" && \
    mamba clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

# Configure container startup
ENTRYPOINT ["/usr/bin/tini", "--"]

# Copy local files as late as possible to avoid cache busting
COPY jupyter/start.sh /usr/local/bin/

WORKDIR /tmp
RUN mamba install --quiet --yes \
        notebook jupyterhub jupyterlab=4.2.5 nodejs==18.11.0 \
        nb_conda_kernels metakernel rucio-clients pytest lz4 ipywidgets ipympl bokeh==2.4.2 &&\
    jupyter notebook --generate-config && \
    mamba clean --all -f -y && \
    npm cache clean --force && \
    jupyter lab clean && \
    rm -rf "/home/${NB_USER}/.cache/yarn" && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

ENV JUPYTER_PORT=8888
EXPOSE $JUPYTER_PORT

# Configure container startup
CMD ["start-notebook.sh"]

# Copy local files as late as possible to avoid cache busting
COPY jupyter/start-notebook.sh jupyter/start-singleuser.sh /usr/local/bin/

# Copy Jupyter configuration files
COPY jupyter/jupyter_server_config.py jupyter/docker_healthcheck.py /etc/jupyter/

# Fix permissions on /etc/jupyter as root
USER root
RUN sed -re "s/c.ServerApp/c.NotebookApp/g" \
    /etc/jupyter/jupyter_server_config.py > /etc/jupyter/jupyter_notebook_config.py && \
    fix-permissions /etc/jupyter/

# Healthcheck configuration
HEALTHCHECK --interval=5s --timeout=3s --start-period=5s --retries=3 \
    CMD /etc/jupyter/docker_healthcheck.py || exit 1

# Install ROOT
RUN dnf install -y libX11-devel libXpm-devel libXft-devel libXext-devel fftw-devel
RUN mkdir /opt/root_build /opt/root && cd /opt/root_build/  &&\
    git clone --branch latest-stable --depth=1 https://github.com/root-project/root.git root_src &&\
    mkdir root_build && cd root_build &&\
    cmake -DCMAKE_INSTALL_PREFIX=../../root \
        -Dcuda=ON -Dcudnn=ON -Dtmva-gpu=ON \
        -DCMAKE_CUDA_HOST_COMPILER=/usr/bin/g++ \
        -DCMAKE_CUDA_COMPILER=/usr/local/cuda-12.2/bin/nvcc \
        -DCMAKE_CUDA_ARCHITECTURES=80 \
        -DCMAKE_CUDA_STANDARD=17 \
        ../root_src &&\
    cmake --build . -- install -j4 &&\
    source ../../root/bin/thisroot.sh

RUN jupyter kernelspec install /opt/root/etc/notebook/kernels/root/ --user

# Install Slurm
COPY rpms/slurm/slurm-24.05.1-1.el8.x86_64.rpm /etc/
COPY slurm /etc/slurm
RUN dnf localinstall -y /etc/slurm-24.05.1-1.el8.x86_64.rpm && \
    rm -rf /etc/slurm-24.05.1-1.el8.x86_64.rpm && \
    groupadd -g 1033 slurm && \
    adduser -u 2000 -g 1033 slurm && \
    chown -R slurm:slurm /etc/slurm/ && \
    mkdir -p /var/log/slurm && \
    chown -R slurm:slurm /var/log/slurm

# Configure XrootD, grid certificates, VOMS
RUN mkdir -p /etc/cvmfs /etc/cvmfs/SITECONF/JobConfig/ /etc/cvmfs/SITECONF/PhEDEx
COPY xml/site-local-config.xml /etc/cvmfs/SITECONF/JobConfig/
COPY xml/storage.xml /etc/cvmfs/SITECONF/PhEDEx/
COPY vomses /etc
RUN mkdir -p /home/${NB_USER}/.globus /home/${NB_USER}/.rnd && \
    chown -R ${NB_USER}:${NB_GID} /home/${NB_USER}/.globus /home/${NB_USER}/.rnd && \
    chmod 700 /home/${NB_USER}/.globus

ENV X509_CERT_DIR=/cvmfs/cms.cern.ch/grid/etc/grid-security/certificates

# Install JupyterLab extensions
RUN pip install --upgrade \
    jupyterlab-git \
    jupyter-resource-usage \
    jupyterlab_iframe \
    purdue-af-shutdown-button \
    purdue-af-grafana-iframe \
    "git+https://github.com/jupyterlab-contrib/jupyterlab-topbar.git#egg=jupyterlab-topbar-text&subdirectory=packages/topbar-text-extension" \
    "git+https://github.com/jupyterlab-contrib/jupyterlab-topbar.git#egg=jupyterlab-theme-toggler&subdirectory=packages/theme-toggler-extension"

# Install Dask packages
RUN pip install dask-gateway
RUN git clone https://github.com/kondratyevd/dask-labextension.git   && \
    cd dask-labextension && \
    pip install . && \
    cd .. && \
    rm -rf dask-labextension

# Configure JupyterLab extensions
RUN jupyter labextension disable "@jupyterlab/apputils-extension:announcements"
# RUN jupyter nbextension enable --py --sys-prefix ipympl

# Scripts that run before session start
COPY --chown=root:root scripts/run-as-root.sh \
    scripts/init-conda-kernels.sh \
    scripts/config-extensions.sh \
    scripts/create-symlinks.sh \
    /usr/local/bin/before-notebook.d/
RUN chmod +x /usr/local/bin/before-notebook.d/*

# Custom scripts and configurations
COPY scripts/eos-connect.sh jupyter/jupyter_config.json /etc/jupyter/
RUN mkdir -p /etc/cvmfs/
COPY default.local /etc/cvmfs/

# Switch back to NB_USER
USER ${NB_USER}
WORKDIR "${HOME}"