apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.pvc.storageClassName }}
  accessModes: {{ .Values.pvc.storageAccessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.storageRequest }}