apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '{{ .Values.networking.containerPort }}'
spec:
  selector: 
    app: {{ .Release.Name }}
  type: LoadBalancer  
  ports:
    - port: {{ .Values.networking.externalPort }}
      targetPort: {{ .Values.networking.containerPort }}
      nodePort: {{ .Values.networking.nodePort }}
