#!/bin/bash

#Get time for logging purpose
start_time=$(date +%s%N)

export PATH="/usr/sbin:$PATH"

#Where is the active dir
active_dir=${active_dir:-/var/spool/slurm/active}

#Cleanup the active files directory
#Report elapsed time if file removed.
active_file=''
set -- $(id -u $SLURM_JOB_USER)
if [[ $# = 1 ]]
then
	active_time=$(date +%s%N)
	active_file=$active_dir/$1-$SLURM_JOB_USER-$SLURM_JOB_ID.active
	rm -f $active_file
	N=$(($(date +%s%N) - active_time))
	logger -t epilog "$SLURM_JOB_ID $SLURM_JOB_USER Epilog Remove Active Files: $(printf '%d.%03d\n' $((N/1000000000)) $(((N/1000000)%1000))) seconds."
fi

#log time taken
N=$(($(date +%s%N) - start_time))
logger -t epilog "$short_rqid $user_name Epilog Run Time: $(printf '%d.%03d\n' $((N/1000000000)) $(((N/1000000)%1000))) seconds."

exit 0