apiVersion: apps/v1
kind: Deployment
metadata:
  name: af-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: af-monitor
  template:
    metadata:
      labels:
        app: af-monitor
    spec:
      nodeSelector: {'cms-af-prod': 'true'}
      tolerations:
      - key: "hub.jupyter.org/dedicated"
        operator: "Equal"
        value: "cms-af"
        effect: "NoSchedule"
      containers:
      - name: af-monitor
        image: geddes-registry.rcac.purdue.edu/cms/af-monitor:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: work
          mountPath: /work/
          mountPropagation: HostToContainer
      volumes:
      - name: work
        persistentVolumeClaim:
          claimName: af-shared-storage

---

apiVersion: v1
kind: Service
metadata:
  name: af-monitor-service
  labels:
    scrape-metrics: "true"
spec:
  selector:
    app: af-monitor
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000