# Chart: grafana/loki 6.44.0
deploymentMode: SingleBinary

singleBinary:
  enabled: true
  replicas: 1
  service:
    type: ClusterIP
    port: 3100
    annotations: {}
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  nodeSelector: { "cms-af-prod": "true" }
  tolerations:
    - key: "hub.jupyter.org/dedicated"
      operator: "Equal"
      value: "cms-af"
      effect: "NoSchedule"
  securityContext:
    runAsNonRoot: true
    runAsUser: 10001
    fsGroup: 10001
  persistence:
    enabled: true
    accessModes: ["ReadWriteOnce"]
    size: 50Gi
    storageClassName: ${multinode_storage_class}
    annotations: {}
    mountPath: /var/loki

# IMPORTANT: keep config as empty string so the legacy templated path is inert
loki:
  config: ""
  auth_enabled: false
  commonConfig: null

  # Satisfy the new validator even for filesystem installs
  storage:
    bucketNames:
      chunks: loki-chunks-placeholder
      ruler: loki-ruler-placeholder
      admin: loki-admin-placeholder
    type: filesystem
    filesystem: {} # nothing needed; just present

  # Quiet optional subsystems some helpers read
  pattern_ingester:
    enabled: false
  tracing:
    enabled: false
  ui:
    enabled: true

  # REAL Loki runtime config goes here
  structuredConfig:
    auth_enabled: false

    ui:
      enabled: true

    server:
      http_listen_port: 3100
      grpc_listen_port: 9096

    # Use memberlist for ring instead of Consul
    common:
      ring:
        kvstore:
          store: memberlist

    memberlist:
      abort_if_cluster_join_fails: false
      join_members: []

    schema_config:
      configs:
        - from: "2024-01-01"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    storage_config:
      tsdb_shipper:
        active_index_directory: /var/loki/tsdb-index
        cache_location: /var/loki/tsdb-cache
        cache_ttl: 24h
        query_ready_num_days: 0
      filesystem:
        directory: /var/loki/chunks

    # Ensure WAL is placed on the writable PVC
    ingester:
      wal:
        dir: /var/loki/wal

    limits_config:
      allow_structured_metadata: true
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 20
      max_query_length: 0h
      max_query_parallelism: 32
      max_streams_per_user: 0
      max_line_size: 256KB
      max_line_size_truncate: false
      per_stream_rate_limit: 3MB
      per_stream_rate_limit_burst: 15MB
      volume_enabled: false

    compactor:
      working_directory: /var/loki/compactor
      compaction_interval: 10m
      retention_enabled: true
      delete_request_store: filesystem
      retention_delete_delay: 2h
      retention_delete_worker_count: 150

gateway:
  enabled: false

ingress:
  enabled: ${enable_ingresses}
  ingressClassName: public
  path: /
  pathType: Prefix
  hosts:
    - loki-cms.geddes.rcac.purdue.edu
  tls:
    - hosts:
        - loki-cms.geddes.rcac.purdue.edu

# Turn off the ruler so those placeholder buckets are never used
ruler:
  enabled: false

# Hard-disable simple-scalable targets
read:
  enabled: false
  replicas: 0
write:
  enabled: false
  replicas: 0
backend:
  enabled: false
  replicas: 0
