apiVersion: batch/v1
kind: Job
metadata:
  name: perf-analyzer
spec:
  completions: 100  # Number of consecutive pods to run
  parallelism: 2  # Number of pods to run in parallel
  template:
    metadata:
      labels:
        app: perf-analyzer
    spec:
      nodeSelector:
        cms-af-prod: "true"
      tolerations:
      - key: "hub.jupyter.org/dedicated"
        operator: "Equal"
        value: "cms-af"
        effect: "NoSchedule"
      restartPolicy: OnFailure
      containers:
      - name: perf-analyzer
        image: nvcr.io/nvidia/tritonserver:21.10-py3-sdk
        command:
          - "/bin/bash"
          - "-c"
          - |
            perf_analyzer \
            -m deepmet \
            -u triton-20gb.cms.geddes.rcac.purdue.edu:8001 \
            -i grpc \
            --percentile=95 \
            --async \
            -p 10000 \
            --concurrency-range 4:4 \
            -b 100 \
            --model-repository=/depot/cms/purdue-af/triton/models/ \
            --input-data "random" 
        resources:
          limits:
            cpu: "1"     
            memory: "2Gi"
          requests:
            cpu: "1"     
            memory: "2Gi"
  backoffLimit: 2  # Number of retries before considering the Job as failed
