apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: supersonic-dynamic-config
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
