apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: purdue-af-alert-experimental
spec:
  providerRef:
    # deployed by the core-production environment into the same namespace
    name: github
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: purdue-af-flux-experimental
      namespace: ${namespace}
