apiVersion: batch/v1
kind: CronJob
metadata:
  name: af-node-monitor-work
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 180
      template:
        spec:
          restartPolicy: Never
          enableServiceLinks: false
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: cms-af-prod
                        operator: In
                        values:
                          - "true"
                  - matchExpressions:
                      - key: cms-af-dev
                        operator: In
                        values:
                          - "true"
          tolerations:
            - key: "hub.jupyter.org/dedicated"
              operator: "Equal"
              value: "cms-af"
              effect: "NoSchedule"
          containers:
            - name: work-check
              image: geddes-registry.rcac.purdue.edu/cms/af-node-monitor:0.1.0
              command: ["python", "/opt/af-node-monitor/job_runner.py"]
              resources:
                requests:
                  cpu: 10m
                  memory: 64Mi
                limits:
                  cpu: 200m
                  memory: 256Mi
              env:
                - name: MOUNT_NAME
                  value: "/work/"
                - name: CHECK_FILE
                  value: "/work/projects/purdue-af/validate-mount.txt"
                - name: CHECKSUM
                  value: "f4cb7f2740ba3e87edfbda6c70fa94c2"
                - name: METADATA_DIR
                  value: "/work/users/"
                - name: FIO_FILE
                  value: "/work/projects/purdue-af/.storage-monitoring-probe-1gb"
                - name: ENABLE_FIO
                  value: "true"
                - name: RESULTS_DIR
                  value: "/work/af-node-monitor/results"
              volumeMounts:
                - name: results
                  mountPath: /work
          volumes:
            - name: results
              persistentVolumeClaim:
                claimName: af-shared-storage

