apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonic-interlink
  namespace: cms
spec:
  # suspend: true
  interval: 1m
  chart:
    spec:
      # chart: helm/supersonic
      # sourceRef:
      #   kind: GitRepository
      #   name: supersonic
      #   namespace: cms
      chart: supersonic
      version: "0.2.1"
      sourceRef:
        kind: HelmRepository
        name: fastml
        namespace: cms
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: supersonic-config
      valuesKey: values.yaml
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: "sonic-interlink"
            patch: |
              - op: add
                path: /spec/template/spec/nodeSelector
                value:
                  kubernetes.io/hostname: interlink-hammer
              - op: add
                path: /spec/template/spec/tolerations/-
                value:
                  key: virtual-node.interlink/no-schedule
                  operator: Exists
              - op: add
                path: /spec/template/spec/annotations
                value:
                  slurm-job.vk.io/singularity-options: "--unsquash --bind /cvmfs"
                  slurm-job.vk.io/flags: "--uid=616617 -A cms -p hammer-nodes --gres=gpu:1"