apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps/jupyter/jupyterhub/helmrelease.yaml
  - ../../../apps/jupyter/jupyterhub/secret-auth.yaml
  - ../../../apps/jupyter/jupyterhub/secret-munge-key.yaml
  - ../../../apps/jupyter/jupyterhub/helmrepo.yaml
  - ../../../apps/jupyter/jupyterhub-database-backup/cronjob.yaml
  - ../../../apps/jupyter/jupyterhub-database-backup/rbac.yaml
  - ../../../apps/jupyter/jupyterhub-ssh/helmrelease.yaml

configMapGenerator:
  - name: jupyterhub-config
    files:
      - values.yaml=values-jupyterhub-dev.yaml
    options:
      disableNameSuffixHash: true
  - name: jupyterhub-extra-config
    files:
      - 00-custom-spawner.py=../../../apps/jupyter/jupyterhub/extraFiles/custom-spawner.py
      - 01-set-user-info.py=../../../apps/jupyter/jupyterhub/extraFiles/set-user-info.py
    options:
      disableNameSuffixHash: true
  - name: jupyterhub-ssh-config
    files:
      - values.yaml=../../production/jupyter/values-jupyterhub-ssh.yaml
    options:
      disableNameSuffixHash: true

patches:
  - target:
      group: batch
      version: v1
      kind: CronJob
    patch: |
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: suspend-all-cronjobs # dummy
      spec:
        suspend: true
