apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - deployment.yaml
configMapGenerator:
- name: af-monitor-config
  namespace: cms
  files:
  - metrics_server.py
  options:
    disableNameSuffixHash: true