apiVersion: v1
kind: Service
metadata:
  name: af-monitor-service
  namespace: cms
  labels:
    scrape-metrics: "true"
spec:
  selector:
    app: af-monitor
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000