apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cmshub
  namespace: cms
spec:
  interval: 5m
  chart:
    spec:
      chart: jupyterhub
      version: "3.2.1"
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
        namespace: cms
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: jupyterhub-config
    valuesKey: values.yaml