apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepo.yaml
configMapGenerator:
  - name: jupyterhub-config
    namespace: cms
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
