apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: af-node-monitor-cvmfs-worker
spec:
  selector:
    matchLabels:
      name: af-node-monitor-cvmfs-worker
  template:
    metadata:
      labels:
        name: af-node-monitor-cvmfs-worker
    spec:
      enableServiceLinks: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cms-af-prod
                    operator: In
                    values:
                      - "true"
              - matchExpressions:
                  - key: cms-af-dev
                    operator: In
                    values:
                      - "true"
      tolerations:
        - key: "hub.jupyter.org/dedicated"
          operator: "Equal"
          value: "cms-af"
          effect: "NoSchedule"
      containers:
        - name: mount-worker
          image: geddes-registry.rcac.purdue.edu/cms/af-node-monitor:0.1.0
          command: ["python", "/scripts/mount_worker.py"]
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 256Mi
          env:
            - name: MOUNT_NAME
              value: "cvmfs"
            - name: CHECK_FILE
              value: "/cvmfs/cms.cern.ch/SITECONF/T2_US_Purdue/Purdue-Hadoop/JobConfig/site-local-config.xml"
            - name: CHECKSUM
              value: "3b570d80272b7188c13cef51e58b7151"
            - name: METADATA_DIR
              value: "/cvmfs/cms.cern.ch/"
            - name: ENABLE_FIO
              value: "false"
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: cvmfs
              mountPath: /cvmfs
              mountPropagation: HostToContainer
      volumes:
        - name: scripts
          configMap:
            name: af-node-monitor-worker-config
        - name: cvmfs
          persistentVolumeClaim:
            claimName: cvmfs
---
apiVersion: v1
kind: Service
metadata:
  name: af-node-monitor-cvmfs-worker
spec:
  selector:
    name: af-node-monitor-cvmfs-worker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
