apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: af-node-monitor-eos-worker
spec:
  selector:
    matchLabels:
      name: af-node-monitor-eos-worker
  template:
    metadata:
      labels:
        name: af-node-monitor-eos-worker
    spec:
      enableServiceLinks: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cms-af-prod
                    operator: In
                    values:
                      - "true"
              - matchExpressions:
                  - key: cms-af-dev
                    operator: In
                    values:
                      - "true"
      tolerations:
        - key: "hub.jupyter.org/dedicated"
          operator: "Equal"
          value: "cms-af"
          effect: "NoSchedule"
      containers:
        - name: mount-worker
          image: geddes-registry.rcac.purdue.edu/cms/af-node-monitor:0.1.0
          command: ["python", "/scripts/mount_worker.py"]
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 256Mi
          env:
            - name: MOUNT_NAME
              value: "eos"
            - name: CHECK_FILE
              value: "/eos/purdue/store/user/dkondrat/test.root"
            - name: CHECKSUM
              value: "18864b0de8ae5a6a8d3b459a7999b431"
            - name: METADATA_DIR
              value: "/eos/purdue/store/user/"
            - name: FIO_FILE
              value: "/eos/purdue/store/user/dkondrat/.storage-monitoring-probe-1gb"
            - name: ENABLE_FIO
              value: "true"
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: eos
              mountPath: /eos
              mountPropagation: HostToContainer
      volumes:
        - name: scripts
          configMap:
            name: af-node-monitor-worker-config
        - name: eos
          hostPath:
            path: /eos
---
apiVersion: v1
kind: Service
metadata:
  name: af-node-monitor-eos-worker
spec:
  selector:
    name: af-node-monitor-eos-worker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
