apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: af-node-monitor-work-worker
spec:
  selector:
    matchLabels:
      name: af-node-monitor-work-worker
  template:
    metadata:
      labels:
        name: af-node-monitor-work-worker
    spec:
      enableServiceLinks: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cms-af-prod
                    operator: In
                    values:
                      - "true"
              - matchExpressions:
                  - key: cms-af-dev
                    operator: In
                    values:
                      - "true"
      tolerations:
        - key: "hub.jupyter.org/dedicated"
          operator: "Equal"
          value: "cms-af"
          effect: "NoSchedule"
      containers:
        - name: mount-worker
          image: geddes-registry.rcac.purdue.edu/cms/af-node-monitor:0.1.0
          command: ["python", "/scripts/mount_worker.py"]
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 256Mi
          env:
            - name: MOUNT_NAME
              value: "/work/"
            - name: CHECK_FILE
              value: "/work/projects/purdue-af/validate-mount.txt"
            - name: CHECKSUM
              value: "f4cb7f2740ba3e87edfbda6c70fa94c2"
            - name: METADATA_DIR
              value: "/work/users/"
            - name: FIO_FILE
              value: "/work/projects/purdue-af/.storage-monitoring-probe-1gb"
            - name: ENABLE_FIO
              value: "true"
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: work
              mountPath: /work/
              mountPropagation: HostToContainer
      volumes:
        - name: scripts
          configMap:
            name: af-node-monitor-worker-config
        - name: work
          persistentVolumeClaim:
            claimName: af-shared-storage
---
apiVersion: v1
kind: Service
metadata:
  name: af-node-monitor-work-worker
spec:
  selector:
    name: af-node-monitor-work-worker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

