apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: purdue-af-flux
  namespace: cms
  annotations:
    cluster: geddes2
spec:
  interval: 1m
  timeout: 1m
  path: "./deploy/core-geddes2/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: purdue-af-geddes
  targetNamespace: cms
  postBuild:
    substitute:
      enable_ingresses: "false"
      namespace: "cms"
      jupyterhub_db_pv_selector: ""
      jupyterhub_db_storage_class: "depot-cloud-block"
      jupyterhub_enable_ingress: "true"
      jupyterhub_logout_redirect_url: "https://cmsdev.geddes.rcac.purdue.edu/hub"
      jupyterhub_oauth_callback_url: "https://cmsdev.geddes.rcac.purdue.edu/hub/oauth_callback"
      jupyterhub_host: "cmsdev.geddes.rcac.purdue.edu"
      sonic_gpus_initial: "0"
      af_shared_storage_size: "1Gi"
      multinode_storage_class: "depot-cloud-filesystem"
      singlenode_storage_class: "depot-cloud-block"
      x509_secret_name: "af-x509-proxy"
  decryption:
    provider: sops
    secretRef:
      name: sops-age
