apiVersion: v1
kind: ServiceAccount
metadata:
  name: af-x509-secrets
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: af-x509-secrets-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: af-x509-secrets-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: af-x509-secrets-role
subjects:
- kind: ServiceAccount
  name: af-x509-secrets
  namespace: default
