apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supersonic-dev
spec:
  # suspend: true
  interval: 1m
  chart:
    spec:
      chart: helm/supersonic
      sourceRef:
        kind: GitRepository
        name: supersonic-dev
      # chart: supersonic
      # version: "0.2.1"
      # sourceRef:
      #   kind: HelmRepository
      #   name: fastml
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: supersonic-dev-config
      valuesKey: values.yaml
