apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: af-node-monitor
spec:
  selector:
    matchLabels:
      name: af-node-monitor
  template:
    metadata:
      labels:
        name: af-node-monitor
    spec:
      serviceAccountName: af-node-monitor
      enableServiceLinks: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cms-af-prod
                    operator: In
                    values:
                      - "true"
              - matchExpressions:
                  - key: cms-af-dev
                    operator: In
                    values:
                      - "true"
      tolerations:
        - key: "hub.jupyter.org/dedicated"
          operator: "Equal"
          value: "cms-af"
          effect: "NoSchedule"
      containers:
        - name: af-node-monitor
          image: geddes-registry.rcac.purdue.edu/cms/af-node-monitor:0.1.0
          command: ["python", "/scripts/node_healthcheck.py"]
          env:
            - name: RESULTS_DIR
              value: "/work/af-node-monitor/results"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8000
              name: metrics
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: cvmfs
              mountPath: /cvmfs
              mountPropagation: HostToContainer
            - name: eos
              mountPath: /eos
              mountPropagation: HostToContainer
            - name: depot
              mountPath: /depot/cms
              mountPropagation: HostToContainer
            - name: work
              mountPath: /work/
              mountPropagation: HostToContainer
      volumes:
        - name: scripts
          configMap:
            name: af-node-monitor-config
        - name: cvmfs
          persistentVolumeClaim:
            claimName: cvmfs
        - name: eos
          hostPath:
            path: /eos
        - name: depot
          nfs:
            server: datadepot.rcac.purdue.edu
            path: /depot/cms
        - name: work
          persistentVolumeClaim:
            claimName: af-shared-storage
