apiVersion: apps/v1
kind: Deployment
metadata:
  name: af-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: af-monitor
  template:
    metadata:
      labels:
        app: af-monitor
    spec:
      nodeSelector: { "cms-af-prod": "true" }
      tolerations:
        - key: "hub.jupyter.org/dedicated"
          operator: "Equal"
          value: "cms-af"
          effect: "NoSchedule"
      containers:
        - name: af-monitor
          image: python:3.11-slim
          command: ["/bin/bash", "-c"]
          args:
            - |
              pip install prometheus_client
              python /scripts/metrics_server.py
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: scripts
              mountPath: /scripts
              configMap:
                name: af-monitor-config
            - name: work
              mountPath: /work/
              mountPropagation: HostToContainer
      volumes:
        - name: scripts
          configMap:
            name: af-monitor-config
        - name: work
          persistentVolumeClaim:
            claimName: af-shared-storage
