apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build-purdue-af
  namespace: cms
  labels:
    ci.purdue.af/revision: ""
  annotations:
    kustomize.toolkit.fluxcd.io/force: "true"
    ci.purdue.af/revision: edfd942c4028d40a776afb1443f6ea5fa3b68672
spec:
  backoffLimit: 0
  completions: 1
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        ci.purdue.af/revision: ""
    spec:
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            - "--context=git://github.com/PurdueAF/purdue-af.git"
            - "--dockerfile=docker/purdue-af/Dockerfile"
            - "--destination=geddes-registry.rcac.purdue.edu/cms/purdue-af:canary"
            - "--cache=true"
            - "--cache-repo=geddes-registry.rcac.purdue.edu/cms/purdue-af-cache"
            # - "--no-push"
          resources:
            requests:
              memory: "256Gi"
              cpu: "16"
            limits:
              memory: "256Gi"
              cpu: "16"
          volumeMounts:
            - name: docker-config
              mountPath: /kaniko/.docker/
      restartPolicy: Never
      volumes:
        - name: docker-config
          secret:
            secretName: docker-config
      nodeSelector:
        cms-af-prod: "true"
      tolerations:
        - key: "hub.jupyter.org/dedicated"
          operator: "Equal"
          value: "cms-af"
          effect: "NoSchedule"
