apiVersion: v1
kind: Secret
metadata:
  name: docker-config
  namespace: cms
type: Opaque
data:
    config.json: ENC[AES256_GCM,data:YvetNUQnejLObX7kpV0Q1DmK2/ms8SgiSmtQIgsSrVFpx3YQwr0pJ2EtrqIFOrG9ArpiannKFLqXJEFeJ6mlzAeu7OxM/O6pZLBCnKeLRFwVbaNpOpgToLw9qs/SxibWFirg6zmWehu29i9cwOb7RxXHQkat53kpNsMlQRDjGHaDzA010SOwZM9ULgP04TXPA3bkoaaYqPvf1JiGUqbeNg4nakGzHE3p4uOSPLy+OVTBL7Ni70ZT4lNOIt8=,iv:3HYW1fbg9fgPWt1rTKqZUmUgJuXBXVJwp08FEpf2KOI=,tag:bKzEkFqjl1Y4fPoRgCx4aQ==,type:str]
# cat ~/.docker/config.json | base64 -w 0
# kubectl create secret generic docker-config --from-file=config.json=$HOME/.docker/config-geddes.json -n cms
sops:
    age:
        - recipient: age1pccfws6yghzqtg5v9228nrvs23w5thsxpr7w4kmmksn435ldev5sqkpj08
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZc3hUN2FqZHZiV2FBYWd2
            VDFNdHRyZHN4Q0dsRmdCMFNUNlJjelIrU1hjCkU0MzNRbmZ0Z0J2R1pRSlU4aG5S
            bGlKSU9lV1F1RjVra1BCaU1uY25SbmMKLS0tIHRNZmVTbGtLWWEvbVRXWEF0cnZY
            WXJJVDc1MzhaNk9SNlNQOFpqWDJYWmcKKpnOHTgT6nsX8OWR1eNDBeGNCjtl6Vu7
            cx283urpdRjrHn+evETt3JiF5FfCBQIEqs6NFoKLerkZl9d7Ah5hwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-07T21:31:09Z"
    mac: ENC[AES256_GCM,data:8jEAYlsXdprT7VIYj55f3sHb9edV/RKlMDoaarnIx497BEXKvnjFLpvtSqaY8Jya1zCd6mxeG/cqsYwTMtUJ8Ofjlx3g0oDNLKz+7WsDOZSlD8p/QNdmGqTMBEIWglrfUG2viD4SoonmEmNyyqmO/uOLNO/y4uk+BP9CiIom3n0=,iv:wVcB0y0NU8ldAQ3OWf5VyeKbwNpCbqwopP5SiWRV/Dw=,tag:nqJzZreozHgmVVReb/6UPw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
