apiVersion: v1
kind: Secret
metadata:
    name: docker-config
    namespace: cms
type: Opaque
data:
    config.json: ENC[AES256_GCM,data:a3M/jHq1OyDjGwEUWapYKLAcecMzQYb2CZzF7GpSerzHJtRjOyntVdbdZcnxy4yKHnXrC9Ewd+87A5qMa6SKPjK/q+QWQgkNRsXzFWbPRdOZSFNP6hdc0ngHosupOAG3HKdv1wVjg6cclC6aO0zbTPCt+WTQTCHLiB7vLzcZe8cvfNIT2WL4aR2TjCrrgmD7Av322ftnXhzDtjaYFfSCqu51+F3NluS2RrsW+kT11kGWX7VrfNsZHQ4bAYehkr/M5QScgRtvykHQ+EgKB00yOwJoWSdRXs7jyc7nf9OMuOsJ14QPCSQO5jcFv2ytwe93j94C6HwSdebhFfSXEEQdEyRUgg9UxRkAhL3cyJ2QuwIZLr3++gW89i8EohEagztbbwcpIIa0R5OquGelek8xeTjaeslgyV3D90Egp10QJ+Az6Te/LHbnzzyx6RiXuu1BRJIa2+NYWt+wMCfXQGF9CdCFgY5wYGoyZST6w8X20Enfhc3XM5u1DNuoDG/Egj62/lChaiBW0nOTW9JcnfH/BQ==,iv:pEFvl3ZGfrDyl3UKdw054HHaEmb/eh2sZsXfGtTqCco=,tag:wuoWLwyZdbAHCC73lmJvtQ==,type:str]
# # cat ~/.docker/config.json | base64 -w 0
sops:
    age:
        - recipient: age1pccfws6yghzqtg5v9228nrvs23w5thsxpr7w4kmmksn435ldev5sqkpj08
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmaGxKNGdJb3dkMnVxMmMr
            VW1CZitWaUFSQVNjYkdwVHNFSkZMUStTQkZnCmFhckkwSlh2Z3BVSHVUR0kySkp5
            cnF5TGR0YkhpZWlQdlJ6SFo0UGVoak0KLS0tIHlTVXNnR3Nsc1dnRlRYVzlCNmpE
            ZEFLdk0wNzBLbmFLVVZuMFhlSTNFWWcKT6rrHGPm2/LD3N0B5yKbxieMN4JQakCL
            Yoit3pj+lmWhbWDSEzc9wRMGtYnikvkO8IuS6GB+KwIz4YVQgRcEyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-07T21:27:27Z"
    mac: ENC[AES256_GCM,data:uxyiuaSAGLMmwDxU7uRMw67SV9CY9wjv7A09yGGksme61xfR8Ivsz+SZxiIF3iCb5LPbG2ZfBA9GvfrAlEhxOj2qyLJ3h28CfuZKurFDVueyJDztoFvBJsFI7Mfu2jMwDpNzIm+SFNTZaIqfOBKo914PK0/QjZrXpGJFCi0bjlM=,iv:7zE2OGsr57+qOBgMibamx+n0+dOaVTnBYWe/+elqOgE=,tag:Ld0LSqIqgbRU4HUsKzZdcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
