apiVersion: v1
kind: Secret
metadata:
  name: docker-config
  namespace: cms
type: Opaque
data:
  config.json: ENC[AES256_GCM,data:a3M/jHq1OyDjGwEUWapYKLAcecMzQYb2CZzF7GpSerzHJtRjOyntVdbdZcnxy4yKHnXrC9Ewd+87A5qMa6SKPjK/q+QWQgkNRsXzFWbPRdOZSFNP6hdc0ngHosupOAG3HKdv1wVjg6cclC6aO0zbTPCt+WTQTCHLiB7vLzcZe8cvfNIT2WL4aR2TjCrrgmD7Av322ftnXhzDtjaYFfSCqu51+F3NluS2RrsW+kT11kGWX7VrfNsZHQ4bAYehkr/M5QScgRtvykHQ+EgKB00yOwJoWSdRXs7jyc7nf9OMuOsJ14QPCSQO5jcFv2ytwe93j94C6HwSdebhFfSXEEQdEyRUgg9UxRkAhL3cyJ2QuwIZLr3++gW89i8EohEagztbbwcpIIa0R5OquGelek8xeTjaeslgyV3D90Egp10QJ+Az6Te/LHbnzzyx6RiXuu1BRJIa2+NYWt+wMCfXQGF9CdCFgY5wYGoyZST6w8X20Enfhc3XM5u1DNuoDG/Egj62/lChaiBW0nOTW9JcnfH/BQ==,iv:pEFvl3ZGfrDyl3UKdw054HHaEmb/eh2sZsXfGtTqCco=,tag:wuoWLwyZdbAHCC73lmJvtQ==,type:str]
# # cat ~/.docker/config.json | base64 -w 0
sops:
  age:
    - recipient: age1pccfws6yghzqtg5v9228nrvs23w5thsxpr7w4kmmksn435ldev5sqkpj08
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWmJDazNVL0pwSjhIWk42
        NW04N0hrRzVJMkJEcW9QUXNkNlNobWZNZjNFCm9FeFZ3RzZLdzdvNW1iTlFBTm9q
        TnBSNzJ2UXZUSHJ0Nksva1plVmh4NWcKLS0tIGpsTTgrK2RrdGNKR0VqZ01Jck4v
        MlZIOFhCMjZZcWp1VkFSTWl3S2RqWFUKKzd60XRXHxcvP+iTjQ7l+RcLbGTx/RtH
        31X1zZtYjHHzO2uXTK4TOHbFJVn0AZ4k4nMGiEiShliqYN0PDzPLmA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-07T21:25:34Z"
  mac: ENC[AES256_GCM,data:WHQKaAa2bIujVeZzgxNw3ztfdgrsJakzt7PEtHGX0p4egUXoQA6NIAgpTpMykRb5NVJJQvRx5S7WemkiVgclZ2Ud9SqgdoBwILQ/vqm0YHFM6O8KZtQKrJhO6obIZuGzHxtz9dexnvn8YWOO38NU6Yo2jK7thU4jWtZl4cW71Qg=,iv:EFrKmMAaisyoWE5znz+fnuSni3o1gAb1yIVabEVQIDI=,tag:0/PAo2BgWJTFw6q6VzUgQQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
