apiVersion: v1
kind: Secret
metadata:
  name: docker-config
  namespace: cms
type: Opaque
data:
  config.json: ENC[AES256_GCM,data:JuOTQ7hKFYQiVuzO1OyayFHMAvdyaUWd+bU3LuTMGhTl9o+q7WhUw6+VAZP9OKoVqQma0VGwIG+6mvBTJldbNXdbfWIZLI/yk3EhpjjDpqb8ntJDGEwAcoSEIyE7F3IKeoG+VoDvRCyc1ji336tc4SCAXTIXbv1psbX9g+SBA95S2Jq8HXcMJu9XusZJx6u8hthf1nU=,iv:M0aSwsjOgStE0HGfBjcFOlf0GoW1jOG6JoFmaWQD2o0=,tag:tLKdNnRC5fZmHn/X9c6QVg==,type:str]
sops:
  age:
    - recipient: age1pccfws6yghzqtg5v9228nrvs23w5thsxpr7w4kmmksn435ldev5sqkpj08
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWmJDazNVL0pwSjhIWk42
        NW04N0hrRzVJMkJEcW9QUXNkNlNobWZNZjNFCm9FeFZ3RzZLdzdvNW1iTlFBTm9q
        TnBSNzJ2UXZUSHJ0Nksva1plVmh4NWcKLS0tIGpsTTgrK2RrdGNKR0VqZ01Jck4v
        MlZIOFhCMjZZcWp1VkFSTWl3S2RqWFUKKzd60XRXHxcvP+iTjQ7l+RcLbGTx/RtH
        31X1zZtYjHHzO2uXTK4TOHbFJVn0AZ4k4nMGiEiShliqYN0PDzPLmA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-07T21:25:34Z"
  mac: ENC[AES256_GCM,data:WHQKaAa2bIujVeZzgxNw3ztfdgrsJakzt7PEtHGX0p4egUXoQA6NIAgpTpMykRb5NVJJQvRx5S7WemkiVgclZ2Ud9SqgdoBwILQ/vqm0YHFM6O8KZtQKrJhO6obIZuGzHxtz9dexnvn8YWOO38NU6Yo2jK7thU4jWtZl4cW71Qg=,iv:EFrKmMAaisyoWE5znz+fnuSni3o1gAb1yIVabEVQIDI=,tag:0/PAo2BgWJTFw6q6VzUgQQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
