apiVersion: v1
kind: Secret
metadata:
    name: docker-config
    namespace: cms
type: Opaque
data:
    config.json: ENC[AES256_GCM,data:7Wq8keA0fP7WUyGs4wR3/QbmmuOGH5bVMw/CVYGZXzFqITcdPtT3xhNnpnnhsxquROngDm4GktN4pn/3Lj8YlvaZu/Uryo1v99aKh7YW+C3NwVut5mVkQ/xg4FmvBg4aSoFIosNFqpc87D+ZrthYfWFPNMXDix0JxUQONZlPxxNEppS2TUVGeTsDGofrGSmO0xtbZ/iqdkJBhbBAm1w77Hzv5OVMTVxqisHy3t6gyGYe8FMo1CFakh6wYl0=,iv:9KvAYbulIFYItBD7DwcwtjIkTN5/6VvSRpUAsQ2PhS0=,tag:vjYZD9qM9CjGTh7UVwUVBw==,type:str]
# cat ~/.docker/config.json | base64 -w 0
# kubectl create secret generic docker-config --from-file=config.json=$HOME/.docker/config-geddes.json -n cms
sops:
    age:
        - recipient: age1pccfws6yghzqtg5v9228nrvs23w5thsxpr7w4kmmksn435ldev5sqkpj08
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNHM2L3NINzcwWmhDY0hV
            dG9WMkFTS21zUmtObC8yTDZ0NnVHRDkvSFM0CnpGU1VGTFNBUVNRUm9LWXd3U3pu
            bHF4Yk5rT2psY1o1bUV6alVWSlJyRHcKLS0tIEFpMmVDaEhJdE12NWpWaHYxZjZ0
            WGhhWW5wOEo2cndjZ2lEVXRNTXpnbG8KG9GNChMBVgozyKIId37iu4m+wSxZk1eg
            ZGDYoE28gWWfgcvDlTKpJsxjzPDMNaM+zX3xYeqQ03/nVEhDrlJ+kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-07T21:35:45Z"
    mac: ENC[AES256_GCM,data:gvuraZgLzATFTC/X654qE8EWeCUSDljrmyapgJqh+djk9XNrqfO16zNoTyftuoa60GdRPfcmJQoQvBq543QfZOq46FvqN2gUfsPct5jb9KTcyUFfPTqPbU1PJtorrta4EhWoCCUajVaDBsQClQ4UI+gF0R6P9MIi1GLcweC5ioo=,iv:8LegnfLuaHvPAwSJiPDfAekEWNSTIU3h97HUXioBb9U=,tag:+mwAtqnX1G9NRd6nqoO3aA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
