apiVersion: v1
kind: Secret
metadata:
    name: docker-config
    namespace: cms
type: Opaque
data:
    config.json: ENC[AES256_GCM,data:AWrlTt3tCg+qiR+OJpUCs1wtCF1xXp/NN5pIpE0KayTHW+O8USkAJyVXyzizGVBfWjvr3UgRDPPu1flvru4NVZG4OWxpeRZtOnQEY1XESD8jLeYdzXjlR4dBlVc/R44z6kvXEpNL5O/3tgB11ll/5C+v13cwl3RGHS7V2Bdj8d3a/eRkQNCApkMzYxZcKB/4YuSOdRsXGedI8iW9OVHlJ80gnKzj137Y6V5BaVVxtse0/OrUpWgHxBqeX6NWLlZcQhQXv5szlAFEdvnAQVvvVCQ/dCE4u396QlJWrsL2XubTJjriAksHgbcDUZ4CqB1RCxlFJJkIYz8S8Y9V7L8uegx/Gs0SwYEWtIg4UvWVRj3a6PoTRfgjjEHu46TV11cNeluBXUa0ghpH0HOV7MDXTC4rWdSDklgxRLgwE8NnQdQxZVMHk8LfKb/rhqYDfBY4BVFN50BiuJjdvFrwcGvBL9Mq/AkPeaFgwzsPMVwoW8BPzBvcVdueuPyiBcguRlLgicITgSsXMZXYZnLnmGDdngzk,iv:YEHKTjmhJbOy7QGqfAGzTpu+qVvvIAaWEHMTTiRxoAE=,tag:4jmZDq4YonX9vkvcpUF55A==,type:str]
# # cat ~/.docker/config.json | base64 -w 0
sops:
    age:
        - recipient: age1pccfws6yghzqtg5v9228nrvs23w5thsxpr7w4kmmksn435ldev5sqkpj08
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZc3hUN2FqZHZiV2FBYWd2
            VDFNdHRyZHN4Q0dsRmdCMFNUNlJjelIrU1hjCkU0MzNRbmZ0Z0J2R1pRSlU4aG5S
            bGlKSU9lV1F1RjVra1BCaU1uY25SbmMKLS0tIHRNZmVTbGtLWWEvbVRXWEF0cnZY
            WXJJVDc1MzhaNk9SNlNQOFpqWDJYWmcKKpnOHTgT6nsX8OWR1eNDBeGNCjtl6Vu7
            cx283urpdRjrHn+evETt3JiF5FfCBQIEqs6NFoKLerkZl9d7Ah5hwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-07T21:31:09Z"
    mac: ENC[AES256_GCM,data:8jEAYlsXdprT7VIYj55f3sHb9edV/RKlMDoaarnIx497BEXKvnjFLpvtSqaY8Jya1zCd6mxeG/cqsYwTMtUJ8Ofjlx3g0oDNLKz+7WsDOZSlD8p/QNdmGqTMBEIWglrfUG2viD4SoonmEmNyyqmO/uOLNO/y4uk+BP9CiIom3n0=,iv:wVcB0y0NU8ldAQ3OWf5VyeKbwNpCbqwopP5SiWRV/Dw=,tag:nqJzZreozHgmVVReb/6UPw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
