apiVersion: v1
kind: Secret
metadata:
  name: docker-config
  namespace: cms
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson:
# cat ~/.docker/config.json | base64 -w 0
# kubectl create secret generic docker-config --from-file=config.json=$HOME/.docker/config-geddes.json -n cms
