apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: dask-gateway-k8s-slurm-config
    namespace: cms
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
