apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - repository.yaml
  - helmrelease.yaml
patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: "api-.*"
  - path: patch-service.yaml
    target:
      kind: Service
      name: "api-.*"
configMapGenerator:
- name: dask-gateway-k8s-slurm-config
  namespace: cms
  files:
  - values.yaml
  options:
    disableNameSuffixHash: true