apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build-a2rchi
  labels:
    ci.purdue.af/revision: ""
  annotations:
    kustomize.toolkit.fluxcd.io/force: "true"
spec:
  backoffLimit: 0
  completions: 1
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        ci.purdue.af/revision: ""
    spec:
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            - "--context=git://github.com/PurdueAF/purdue-af.git"
            - "--dockerfile=docker/a2rchi/Dockerfile"
            - "--destination=geddes-registry.rcac.purdue.edu/cms/a2rchi:latest"
            - "--cache=true"
            - "--cache-repo=geddes-registry.rcac.purdue.edu/cms/a2rchi-cache"
          resources:
            requests:
              memory: "8Gi"
              cpu: "2"
            limits:
              memory: "16Gi"
              cpu: "4"
          volumeMounts:
            - name: docker-config
              mountPath: /kaniko/.docker/
      restartPolicy: Never
      volumes:
        - name: docker-config
          secret:
            secretName: docker-config
      nodeSelector:
        cms-af-prod: "true"
      tolerations:
        - key: "hub.jupyter.org/dedicated"
          operator: "Equal"
          value: "cms-af"
          effect: "NoSchedule"

