apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build-a2rchi
spec:
  backoffLimit: 0
  completions: 1
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            - "--context=git://github.com/PurdueAF/purdue-af.git"
            - "--dockerfile=docker/a2rchi/Dockerfile"
            - "--destination=geddes-registry.rcac.purdue.edu/cms/a2rchi:latest"
            - "--cache=true"
            - "--cache-repo=geddes-registry.rcac.purdue.edu/cms/a2rchi-cache"
            # - "--no-push"
          resources:
            requests:
              memory: "32Gi"
              cpu: "16"
            limits:
              memory: "64Gi"
              cpu: "32"
          volumeMounts:
            - name: docker-config
              mountPath: /kaniko/.docker/
      restartPolicy: Never
      volumes:
        - name: docker-config
          secret:
            secretName: docker-config
      nodeSelector:
        cms-af-prod: "true"
      tolerations:
        - key: "hub.jupyter.org/dedicated"
          operator: "Equal"
          value: "cms-af"
          effect: "NoSchedule"
