apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build-conda-store-ui
spec:
  backoffLimit: 0
  completions: 1
  template:
    spec:
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            - "--context=git://github.com/conda-incubator/conda-store-ui"
            - "--dockerfile=Dockerfile"
            - "--destination=geddes-registry.rcac.purdue.edu/cms/conda-store-ui:latest"
            - "--cache=true"
            # - "--no-push"
          resources:
            requests:
              memory: "4Gi"
              cpu: "4"
            limits:
              memory: "8Gi"
              cpu: "8"
          volumeMounts:
            - name: docker-config
              mountPath: /kaniko/.docker/
      restartPolicy: Never
      volumes:
        - name: docker-config
          secret:
            secretName: docker-config
      nodeSelector:
        cms-af-prod: "true"
      tolerations:
        - key: "hub.jupyter.org/dedicated"
          operator: "Equal"
          value: "cms-af"
          effect: "NoSchedule"
