apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build-interlink
spec:
  backoffLimit: 0
  completions: 1
  template:
    spec:
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            - "--context=git://github.com/PurdueAF/purdue-af.git"
            - "--dockerfile=docker/interlink-slurm-plugin/Dockerfile.alma8"
            - "--destination=geddes-registry.rcac.purdue.edu/cms/interlink-slurm-plugin:0.5.2"
            - "--cache=true"
            # - "--no-push"
          resources:
            requests:
              memory: "4Gi"
              cpu: "4"
            limits:
              memory: "8Gi"
              cpu: "8"
          volumeMounts:
            - name: docker-config
              mountPath: /kaniko/.docker/
      restartPolicy: Never
      volumes:
        - name: docker-config
          secret:
            secretName: docker-config
      nodeSelector:
        cms-af-prod: "true"
      tolerations:
        - key: "hub.jupyter.org/dedicated"
          operator: "Equal"
          value: "cms-af"
          effect: "NoSchedule"
