apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - build-af.yaml
  - build-purdue-af.yaml
  - build-dask.yaml
  - build-interlink.yaml
  - build-a2rchi.yaml
  - secret.yaml
