apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prometheus-data
  namespace: cms-dev
  labels:
    app: prometheus-deployment
spec:
  storageClassName: geddes-standard-multinode
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi