apiVersion: v1
kind: Service
metadata:
    name: prometheus-service
    namespace: cms-dev
    annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port:   '9090'
spec:
    selector:
        app: prometheus
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 9090 
      nodePort: 30000