namespace: cms

deployment:
  image: geddes-registry.rcac.purdue.edu/docker-hub-cache/prom/prometheus
  replicas: 1
  nodeSelector:
    "cms-af-prod": "true"
  resources:
    requests:
      cpu: 4
      memory: 8Gi
    limits:
      cpu: 4
      memory: 8Gi
  tsdbRetention: 10d
  storagePath: /prometheus
  configPath: /etc/prometheus
  tolerations:
    - key: "hub.jupyter.org/dedicated"
      operator: "Equal"
      value: "cms-af"
      effect: "NoSchedule"

networking:
  externalPort: 8080
  containerPort: 9090
  nodePort: 30000

pvc:
  storageClassName: geddes-standard-multinode
  storageRequest: 10Gi
  storageAccessModes: ["ReadWriteMany"]

prometheusConfig: |
  # my global config
  global:
    scrape_interval: 60s
    evaluation_interval: 60s
  alerting:
    alertmanagers:
    - static_configs:
      - targets:
  rule_files:
  scrape_configs:
    - job_name: 'jupyterhub'
      metrics_path: '/hub/metrics'
      static_configs:
        - targets:
          - 'cms.geddes.rcac.purdue.edu'
          - 'cmsdev.geddes.rcac.purdue.edu'
    - job_name: 'kube-state-metrics'
      static_configs:
        - targets: 
          - 'rancher-monitoring-kube-state-metrics.cattle-monitoring-system.svc.cluster.local:8080'
    - job_name: 'slurm-metrics'
      static_configs:
        - targets: 
          - 'hammer-adm.rcac.purdue.edu:9100'
    - job_name: 'node-exporter'
      static_configs:
        - targets:
          - 'geddes-b013.rcac.purdue.edu:9796'
          - 'geddes-b014.rcac.purdue.edu:9796'
          - 'geddes-b015.rcac.purdue.edu:9796'
          - 'geddes-g000.rcac.purdue.edu:9796'
          - 'geddes-g001.rcac.purdue.edu:9796'
          - 'af-a01.cms.rcac.purdue.edu:9796'
          - 'af-a02.cms.rcac.purdue.edu:9796'
          - 'cms-fe01.rcac.purdue.edu:9796'
          - 'cms-fe00.rcac.purdue.edu:9796'
          - 'vm-hammer-g000.rcac.purdue.edu:9796'
          - 'vm-hammer-g001.rcac.purdue.edu:9796'
          - 'vm-hammer-g002.rcac.purdue.edu:9796'
          - 'vm-hammer-g003.rcac.purdue.edu:9796'
          - 'vm-hammer-g004.rcac.purdue.edu:9796'
          - 'vm-hammer-g005.rcac.purdue.edu:9796'
          - 'vm-hammer-f000.rcac.purdue.edu:9796'
          - 'vm-hammer-f001.rcac.purdue.edu:9796'
          - 'vm-hammer-f002.rcac.purdue.edu:9796'
          - 'vm-hammer-f003.rcac.purdue.edu:9796'
          - 'vm-hammer-f004.rcac.purdue.edu:9796'
          - 'vm-hammer-f005.rcac.purdue.edu:9796'
    - job_name: 'af-pod-monitor'
      kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
              - 'cms'
      relabel_configs:
        - source_labels: [__meta_kubernetes_service_label_app]
          target_label: 'app'
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: 'pod'
        - source_labels: [__meta_kubernetes_pod_label_username_unescaped]
          target_label: 'username'
        - source_labels: [__meta_kubernetes_pod_label_docker_image_tag]
          target_label: 'docker_image_tag'
        - source_labels: [__meta_kubernetes_namespace]
          target_label: 'namespace'
          replacement: '$1'
        - source_labels: [__meta_kubernetes_pod_node_name]
          target_label: 'node'
        - source_labels: [__meta_kubernetes_service_label_scrape_metrics]
          action: keep
          regex: 'true'


