namespace: cms

deployment:
  image: prom/prometheus
  replicas: 1
  nodeSelector:
    "cms-af-prod": "true"
  resources:
    requests:
      cpu: 2000m
      memory: 4Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  tsdbRetention: 10d
  storagePath: /prometheus
  configPath: /etc/prometheus
  tolerations:
    - key: "hub.jupyter.org/dedicated"
      operator: "Equal"
      value: "cms-af"
      effect: "NoSchedule"

networking:
  externalPort: 8080
  containerPort: 9090
  nodePort: 30000

pvc:
  storageClassName: geddes-standard-multinode
  storageRequest: 10Gi
  storageAccessModes: ["ReadWriteMany"]

prometheusConfig: |
  # my global config
  global:
    scrape_interval: 15s
    evaluation_interval: 15s
  alerting:
    alertmanagers:
    - static_configs:
      - targets:
  rule_files:
  scrape_configs:
    - job_name: 'jupyterhub'
      metrics_path: '/hub/metrics'
      static_configs:
        - targets:
          - 'cms.geddes.rcac.purdue.edu'
          - 'cmsdev.geddes.rcac.purdue.edu'
    - job_name: 'kube-state-metrics'
      static_configs:
        - targets: 
          - 'rancher-monitoring-kube-state-metrics.cattle-monitoring-system.svc.cluster.local:8080'
    - job_name: 'kubelet-metrics'
      metrics_path: "/metrics"
      static_configs:
        - targets: 
          - 'geddes-b014.rcac.purdue.edu:10250'
          - 'geddes-b015.rcac.purdue.edu:10250'
          - 'geddes-g000.rcac.purdue.edu:10250'
          - 'af-a01.cms.rcac.purdue.edu:10250'
          - 'af-a02.cms.rcac.purdue.edu:10250'
          - 'cms-fe01.rcac.purdue.edu:10250'
          - 'hammer-f013.rcac.purdue.edu:10250'
    - job_name: 'kubelet-metrics-cadvisor'
      metrics_path: "/metrics/cadvisor"
      static_configs:
        - targets: 
          - 'geddes-b014.rcac.purdue.edu:10250'
          - 'geddes-b015.rcac.purdue.edu:10250'
          - 'geddes-g000.rcac.purdue.edu:10250'
          - 'af-a01.cms.rcac.purdue.edu:10250'
          - 'af-a02.cms.rcac.purdue.edu:10250'
          - 'cms-fe01.rcac.purdue.edu:10250'
          - 'hammer-f013.rcac.purdue.edu:10250'
    - job_name: 'kubelet-metrics-probes'
      metrics_path: "/metrics/probes"
      static_configs:
        - targets: 
          - 'geddes-b014.rcac.purdue.edu:10250'
          - 'geddes-b015.rcac.purdue.edu:10250'
          - 'geddes-g000.rcac.purdue.edu:10250'
          - 'af-a01.cms.rcac.purdue.edu:10250'
          - 'af-a02.cms.rcac.purdue.edu:10250'
          - 'cms-fe01.rcac.purdue.edu:10250'
          - 'hammer-f013.rcac.purdue.edu:10250'
    - job_name: 'node-exporter'
      static_configs:
        - targets:
          - 'geddes-b014.rcac.purdue.edu:9796'
          - 'geddes-b015.rcac.purdue.edu:9796'
          - 'geddes-g000.rcac.purdue.edu:9796'
          - 'af-a01.cms.rcac.purdue.edu:9796'
          - 'af-a02.cms.rcac.purdue.edu:9796'
          - 'cms-fe01.rcac.purdue.edu:9796'
          - 'hammer-f013.rcac.purdue.edu:9796'
    - job_name: 'triton-service-monitor'
      kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
              - 'cms'
      relabel_configs:
        - source_labels: [__meta_kubernetes_service_label_app]
          target_label: 'app'
        - source_labels: [__meta_kubernetes_service_label_scrape_metrics]
          action: keep
          regex: 'true'
    - job_name: 'dask'
      file_sd_configs:
      - files:
        - '/prometheus/dask_targets.json'
    - job_name: 'gpu-metrics'
      static_configs:
        - targets:
          - '10.5.15.174:9400'



