apiVersion: batch/v1
kind: CronJob
metadata:
  name: conda-env-builder-generator
  namespace: cms
spec:
  schedule: "0 * * * *" # every hour
  concurrencyPolicy: Forbid
  suspend: false
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: conda-env-builder
          restartPolicy: Never
          containers:
            - name: job-generator
              image: rockylinux:8.9
              command:
                - /bin/bash
                - -c
                - |
                  # Copy the generator script and execute it
                  cp /scripts/generate-conda-env-jobs.sh /tmp/generate-conda-env-jobs.sh
                  chmod +x /tmp/generate-conda-env-jobs.sh
                  /tmp/generate-conda-env-jobs.sh
              resources:
                requests:
                  memory: "1Gi"
                  cpu: "0.5"
                limits:
                  memory: "2Gi"
                  cpu: "1"
              volumeMounts:
                - name: scripts
                  mountPath: /scripts/
                  readOnly: true
          volumes:
            - name: scripts
              configMap:
                name: conda-env-builder-scripts
          nodeSelector:
            cms-af-prod: "true"
          tolerations:
            - key: "hub.jupyter.org/dedicated"
              operator: "Equal"
              value: "cms-af"
              effect: "NoSchedule"
