apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cronjob.yaml
  - rbac.yaml

configMapGenerator:
  - name: conda-env-builder-scripts
    namespace: cms
    files:
      - generate-conda-env-jobs.sh
      - build-single-conda-env.sh
    options:
      disableNameSuffixHash: true

namespace: cms
