######################################
# This file is maintained with
# RCAC configuration management.
# Your changes will be clobbered.
######################################

###
# Slurm cgroup support configuration file
###
#CgroupAutomount=yes
ConstrainCores=yes
ConstrainRAMSpace=yes
ConstrainSwapSpace=yes
ConstrainDevices=yes
