######################################
## This file is maintained with
## RCAC configuration management.
## Your changes will be clobbered.
#######################################

# The nodenames here can be compressed, but I opted to define them all.
NodeName=g000 Name=gpu Type=l40 Count=2 File=/dev/nvidia[0-1]
NodeName=g001 Name=gpu Type=l40 Count=2 File=/dev/nvidia[0-1]
NodeName=g002 Name=gpu Type=l40 Count=2 File=/dev/nvidia[0-1]
NodeName=g003 Name=gpu Type=l40 Count=2 File=/dev/nvidia[0-1]
NodeName=g004 Name=gpu Type=l40 Count=2 File=/dev/nvidia[0-1]
NodeName=g005 Name=gpu Type=l40 Count=2 File=/dev/nvidia[0-1]
NodeName=h[000-019] Name=gpu Type=h100 Count=8 File=/dev/nvidia[0-7]
NodeName=i[000-002] Name=gpu Type=h200 Count=8 File=/dev/nvidia[0-7]
NodeName=a[000-338] Name=hp_cpu Count=192 Flags=CountOnly
