######################################
# This file is maintained with
# RCAC configuration management.
# Your changes will be clobbered.
######################################

NodeName=a[000-337] AutoBasePath=true BasePath=/localscratch/slurmjobs Shared=true
NodeName=b[000-005] AutoBasePath=true BasePath=/localscratch/slurmjobs Shared=true
NodeName=g[000-005] AutoBasePath=true BasePath=/localscratch/slurmjobs Shared=true
NodeName=h[000-019] AutoBasePath=true BasePath=/localscratch/slurmjobs Shared=true
NodeName=i[000-002] AutoBasePath=true BasePath=/localscratch/slurmjobs Shared=true
