apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-knowledge-trigger
  namespace: cms
spec:
  schedule: "*/5 * * * *" # Run every 5 minutes
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: update-knowledge
          restartPolicy: OnFailure
          nodeSelector: { "cms-af-prod": "true" }
          tolerations:
            - key: "hub.jupyter.org/dedicated"
              operator: "Equal"
              value: "cms-af"
              effect: "NoSchedule"
          containers:
            - name: update-knowledge
              image: python:3.11-slim
              command: ["/bin/bash", "-c"]
              args:
                - |
                  pip install --no-cache-dir requests python-dotenv gitpython
                  python /scripts/update_knowledge.py
              resources:
                requests:
                  cpu: 500m
                  memory: 1Gi
                limits:
                  cpu: 1
                  memory: 2Gi
              volumeMounts:
                - name: script
                  mountPath: /scripts
                  readOnly: true
                - name: docs
                  mountPath: /workspace/docs
                  readOnly: true
              workingDir: /workspace
              env:
                - name: OPENWEBUI_API_URL
                  value: "https://genai.rcac.purdue.edu/api/" # Update this URL
                - name: KNOWLEDGE_ID
                  value: "866d52ed-332a-4703-934a-96022729d080" # Update this ID
                - name: OPENWEBUI_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: update-knowledge-secret
                      key: api-token
          volumes:
            - name: script
              configMap:
                name: update-knowledge-script
            - name: docs
              gitRepo:
                repository: https://github.com/PurdueAF/purdue-af.git
                revision: main
                directory: docs
