apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alloy
spec:
  interval: 1m
  chart:
    spec:
      chart: alloy
      # Keep version flexible; can be pinned later if desired
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 1m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  valuesFrom:
    - kind: ConfigMap
      name: alloy-config
      valuesKey: values.yaml
