# Chart: grafana/alloy

controller:
  type: daemonset
  replicas: 1
  service:
    enabled: false
  tolerations:
    - key: "hub.jupyter.org/dedicated"
      operator: "Equal"
      value: "cms-af"
      effect: "NoSchedule"
  nodeSelector:
    cms-af-prod: "true"
  extraVolumes:
    - name: varlog
      hostPath:
        path: /var/log
    - name: dockercontainers
      hostPath:
        path: /var/lib/docker/containers
        # If you use containerd only, you can omit this
  extraVolumeMounts:
    - name: varlog
      mountPath: /var/log
      readOnly: true
    - name: dockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true

serviceAccount:
  create: true

rbac:
  create: true

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

alloy:
  # River configuration: collect Kubernetes pod logs and send to Loki
  config: |
    logging {
      level = "info"
      format = "logfmt"
    }

    discovery.kubernetes "pods" {
      role = "pod"
    }

    loki.source.kubernetes "pods" {
      targets    = discovery.kubernetes.pods.targets
      forward_to = [loki.process.pods.receiver]
    }

    loki.process "pods" {
      forward_to = [loki.write.default.receiver]
    }

    loki.write "default" {
      endpoint {
        url = "http://loki.cms.svc.cluster.local:3100/loki/api/v1/push"
      }
    }

    // eBPF profiling removed due to cluster policy; Alloy is used only for logs
