apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cms
  name: doesNotMatter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: cmshub-ssh
      app.kubernetes.io/name: jupyterhub-ssh
  template:
    spec:
      volumes:
      - name: cvmfs
        persistentVolumeClaim:
          claimName: cvmfs
      - name: eos
        hostPath: 
          path: /eos
      - name: depot
        nfs:
          server: datadepot.rcac.purdue.edu
          path: /depot/cms
      # - name: work
      #   persistentVolumeClaim:
      #     claimName: af-shared-storage
      containers:
      - name: server
        securityContext:
          privileged: false
        volumeMounts:
        - name: cvmfs
          mountPath: /cvmfs
          mountPropagation: HostToContainer
        - name: eos
          mountPath: /eos
          mountPropagation: HostToContainer
        - name: depot
          mountPath: /depot/cms
          mountPropagation: HostToContainer
        # - name: work
        #   mountPath: /work/
        #   mountPropagation: HostToContainer

