apiVersion: v1
kind: ConfigMap
metadata:
  name: a2rchi-config
data:
  a2rchi-config.yaml: |
{{ .Values.config.a2rchiConfigYaml | indent 4 }}
  main.prompt: |
{{ .Values.config.mainPrompt | indent 4 }}
  condense.prompt: |
{{ .Values.config.condensePrompt | indent 4 }}

