apiVersion: v1
kind: ConfigMap
metadata:
  name: a2rchi-config
data:
  # Upstream expects configs under /root/A2rchi/configs and prompts at /root/A2rchi/*.prompt
  purdue-af.yaml: |
    name: purdue-af
    global:
      DATA_PATH: "/root/A2rchi/data/"
      ACCOUNTS_PATH: "/root/A2rchi/accounts/"
      ACCEPTED_FILES: [".txt", ".html", ".pdf"]
      LOGGING:
        input_output_filename: "chain_input_output.log"
      verbosity: 3
    services:
      benchmarking:
        out_dir: "."
        queries_path: "queries"
        modes: ["LINKS", "RAGAS"]
        mode_settings:
          sources_settings:
            default_match_field: "display_name"
          ragas_settings:
            enabled_metrics: ["answer_relevancy", "faithfulness", "context_precision", "context_recall"]
            provider: "OpenAI"
            evaluation_model_settings:
              model_name: "gpt-4"
              base_url: ""
            embedding_model: "OpenAI"
            timeout: 180
            batch_size: false
      piazza:
        network_id: ""
        update_time: 60
      mattermost:
        update_time: 60
      chat_app:
        trained_on: "Purdue AF"
        port: 7861
        external_port: 80
        host: "0.0.0.0"
        hostname: "{{ .Values.ingress.host }}"
        template_folder: "/opt/A2rchi/src/interfaces/chat_app/templates/"
        static_folder: "/opt/A2rchi/src/interfaces/chat_app/static/"
        num_responses_until_feedback: 3
        include_copy_button: true
        enable_debug_chroma_endpoints: false
        flask_debug_mode: false
      uploader_app:
        port: 5001
        external_port: 5003
        host: "0.0.0.0"
        template_folder: "/opt/A2rchi/src/interfaces/uploader_app/templates/"
        verify_urls: true
        flask_debug_mode: false
      grader_app:
        port: 7861
        external_port: 7862
        host: "0.0.0.0"
        hostname: "localhost"
        template_folder: "/opt/A2rchi/src/interfaces/grader_app/templates/"
        num_problems: 1
        local_rubric_dir: ""
        local_users_csv_dir: ""
        flask_debug_mode: false
      chromadb:
        use_HTTP_chromadb_client: true
        chromadb_host: "chromadb"
        chromadb_port: 8000
        chromadb_external_port: 8000
        local_vstore_path: "/root/A2rchi/vstore/"
      grafana:
        external_port: 3000
      postgres:
        port: 5432
        user: "postgres"
        database: "postgres"
        host: "postgres"
      redmine_mailbox:
        url: ""
        project: ""
        redmine_update_time: 10
        answer_tag: "-- A2rchi -- Resolving email was sent"
        imap4_port: 143
        mailbox_update_time: 10
    data_manager:
      collection_name: purdue-af
      embedding_name: HuggingFaceEmbeddings
      embedding_class_map:
        OpenAIEmbeddings:
          class: OpenAIEmbeddings
          kwargs:
            model: text-embedding-3-small
          similarity_score_reference: 10
        HuggingFaceEmbeddings:
          class: HuggingFaceEmbeddings
          kwargs:
            model_name: sentence-transformers/all-MiniLM-L6-v2
            model_kwargs:
              device: cpu
            encode_kwargs:
              normalize_embeddings: true
          similarity_score_reference: 10
          query_embedding_instructions: null
      chunk_size: 1000
      chunk_overlap: 0
      reset_collection: true
      num_documents_to_retrieve: 5
      stemming:
        enabled: false
      distance_metric: cosine
      use_hybrid_search: false
      bm25_weight: 0.6
      semantic_weight: 0.4
      bm25:
        k1: 0.5
        b: 0.75
      sources:
        links:
          enabled: false
          visible: true
          input_lists: []
          scraper:
            reset_data: true
            verify_urls: false
            enable_warnings: false
        git:
          enabled: false
          visible: true
        sso:
          enabled: false
          visible: true
          sso_class: CERNSSOScraper
          sso_class_map:
            CERNSSOScraper:
              class: CERNSSOScraper
              kwargs:
                headless: true
                max_depth: 2
        jira:
          enabled: false
          url: ""
          visible: false
          projects: []
          anonymize_data: true
          max_tickets: 1e10
        redmine:
          enabled: false
          url: ""
          project: ""
          visible: false
          anonymize_data: true
      utils:
        anonymizer:
          nlp_model: en_core_web_sm
          excluded_words: ["John", "Jane", "Doe"]
          greeting_patterns: ["^(hi|hello|hey|greetings|dear)\\b", "^\\w+,\\s*"]
          signoff_patterns: ["\\b(regards|sincerely|best regards|cheers|thank you)\\b", "^\\s*[-~]+\\s*$"]
          email_pattern: "[\\w\\.-]+@[\\w\\.-]+\\.\\w+"
          username_pattern: "\\[~[^\\]]+\\]"
    a2rchi:
      pipelines: [QAPipeline]
      pipeline_map:
        QAPipeline:
          max_tokens: 10000
          prompts:
            required:
              condense_prompt: "/root/A2rchi/condense.prompt"
              chat_prompt: "/root/A2rchi/main.prompt"
          models:
            required:
              condense_model: {{- if eq .Values.model.backend "ollama" }} OllamaInterface {{- else if eq .Values.model.backend "openai" }} OpenAIGPT4 {{- else if eq .Values.model.backend "anthropic" }} AnthropicLLM {{- else }} HuggingFaceOpenLLM {{- end }}
              chat_model: {{- if eq .Values.model.backend "ollama" }} OllamaInterface {{- else if eq .Values.model.backend "openai" }} OpenAIGPT4 {{- else if eq .Values.model.backend "anthropic" }} AnthropicLLM {{- else }} HuggingFaceOpenLLM {{- end }}
        GradingPipeline:
          max_tokens: 10000
          prompts:
            required:
              final_grade_prompt: null
            optional:
              summary_prompt: null
              analysis_prompt: null
          models:
            required:
              final_grade_model: HuggingFaceOpenLLM
            optional:
              summary_model: HuggingFaceOpenLLM
              analysis_model: HuggingFaceOpenLLM
        ImageProcessingPipeline:
          max_tokens: 10000
          prompts:
            required:
              image_processing_prompt: null
          models:
            required:
              image_processing_model: HuggingFaceImageLLM
      model_class_map:
        OllamaInterface:
          class: OllamaInterface
          kwargs:
            base_model: {{ .Values.model.ollama.model }}
            temperature: 1
            max_tokens: 1000
            url: {{ .Values.model.ollama.baseUrl | quote }}
      chain_update_time: 10
    utils:
      sso:
        enabled: false
        sso_class: CERNSSOScraper
        sso_class_map:
          CERNSSOScraper:
            class: CERNSSOScraper
            kwargs:
              headless: true
              max_depth: 2
      git:
        enabled: false
      jira:
        enabled: false
        url: ""
        projects: []
        anonymize_data: true
  main.prompt: |
    # Prompt used to query LLM with appropriate context and question.
    # This prompt is specific to subMIT and likely will not perform well for other applications, where it is recommended to write your own prompt and change it in the config
    # 
    # All final prompts must have the following tags in them, which will be filled with the appropriate information:
    #      Question: {question}
    #      Context: {context}
    #
    You are a conversational chatbot named A2rchi who helps people navigate a computing cluster named SubMIT.
    You will be provided context in the form of relevant documents, such as previous communication between sys admins and Guides, a summary of the problem that the user is trying to solve and the important elements of the conversation, and the most recent chat history between you and the user to help you answer their questions. 
    Using your Linux and computing knowledge, answer the question at the end.
    Unless otherwise indicated, assume the users are not well versed in computing.
    Please do not assume that SubMIT machines have anything installed on top of native Linux except if the context mentions it.
    If you don't know, say "I don't know", if you need to ask a follow up question, please do.

    Context: {retriever_output}
    Question: {question}
    Chat History: {history}
    Helpful Answer:
  condense.prompt: |
    # Prompt used to condense a chat history and a follow up question into a stand alone question. 
    # This is a very general prompt for condensing histories, so for base installs it will not need to be modified
    # 
    # All condensing prompts must have the following tags in them, which will be filled with the appropriate information:
    #      {chat_history}
    #      {question}
    #
    Given the following conversation between you (the AI named A2rchi), a human user who needs help, and an expert, and a follow up question, rephrase the follow up question to be a standalone question, in its original language.

    Chat History: {history}
    Follow Up Input: {question}
    Standalone question:

