apiVersion: apps/v1
kind: Deployment
metadata:
  name: a2rchi-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a2rchi-chatbot
  template:
    metadata:
      labels:
        app: a2rchi-chatbot
    spec:
      containers:
        - name: chatbot
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: PG_PASSWORD_FILE
              value: /secrets/pg_password
            {{- if .Values.model.huggingface.secretName }}
            - name: HUGGINGFACEHUB_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.model.huggingface.secretName }}
                  key: HUGGINGFACEHUB_API_TOKEN
            - name: HUGGINGFACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.model.huggingface.secretName }}
                  key: HUGGINGFACEHUB_API_TOKEN
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.model.huggingface.secretName }}
                  key: HUGGINGFACEHUB_API_TOKEN
            {{- end }}  
            {{- if .Values.model.openai.secretName }}
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.model.openai.secretName }}
                  key: OPENAI_API_KEY
            - name: OPENAI_API_KEY_FILE
              value: /secrets/OPENAI_API_KEY
            - name: OPENAI_API_KEY_FILE
              value: /secrets/OPENAI_API_KEY
            {{- end }}
            {{- if .Values.model.huggingface.secretName }}
            - name: HUGGING_FACE_HUB_TOKEN_FILE
              value: /secrets/HUGGINGFACEHUB_API_TOKEN
            {{- end }}
            {{- if .Values.model.anthropic.secretName }}
            - name: ANTHROPIC_API_KEY_FILE
              value: /secrets/ANTHROPIC_API_KEY
            {{- end }}
            - name: PGHOST
              value: postgres
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            # - name:  OPENAI_LOG
            #   value: debug
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: a2rchi-prompts
              mountPath: /root/A2rchi
              readOnly: true
            - name: configs-dir
              mountPath: /root/A2rchi/configs
            - name: a2rchi-config
              mountPath: /root/A2rchi/configs/a2rchi-config.yaml
              subPath: a2rchi-config.yaml
              readOnly: true
            - name: a2rchi-data
              mountPath: /root/A2rchi/data
            - name: secrets
              mountPath: /secrets
      volumes:
        - name: a2rchi-prompts
          configMap:
            name: a2rchi-config
            items:
              - key: main.prompt
                path: main.prompt
              - key: condense.prompt
                path: condense.prompt
        - name: a2rchi-config
          configMap:
            name: a2rchi-config
            items:
              - key: a2rchi-config.yaml
                path: a2rchi-config.yaml
        - name: configs-dir
          emptyDir: {}
        - name: a2rchi-data
          emptyDir: {}
        - name: secrets
          projected:
            sources:
              - secret:
                  name: a2rchi-postgres
                  items:
                    - key: POSTGRES_PASSWORD
                      path: pg_password
              {{- if .Values.model.openai.secretName }}
              - secret:
                  name: {{ .Values.model.openai.secretName }}
                  items:
                    - key: OPENAI_API_KEY
                      path: OPENAI_API_KEY
              {{- end }}
              {{- if .Values.model.huggingface.secretName }}
              - secret:
                  name: {{ .Values.model.huggingface.secretName }}
                  items:
                    - key: HUGGINGFACEHUB_API_TOKEN
                      path: HUGGINGFACEHUB_API_TOKEN
              {{- end }}
              {{- if .Values.model.anthropic.secretName }}
              - secret:
                  name: {{ .Values.model.anthropic.secretName }}
                  items:
                    - key: ANTHROPIC_API_KEY
                      path: ANTHROPIC_API_KEY
              {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: a2rchi
spec:
  selector:
    app: a2rchi-chatbot
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}

