{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: a2rchi-postgres-init
data:
  01-init.sql: |
    -- create tables
    CREATE TABLE IF NOT EXISTS configs (
        config_id SERIAL,
        config TEXT NOT NULL,
        config_name TEXT NOT NULL,
        PRIMARY KEY (config_id)
    );
    CREATE TABLE IF NOT EXISTS conversation_metadata (
        conversation_id SERIAL,
        title TEXT,
        created_at TIMESTAMP NOT NULL DEFAULT NOW(),
        last_message_at TIMESTAMP NOT NULL DEFAULT NOW(),
        PRIMARY KEY (conversation_id)
    );
    CREATE TABLE IF NOT EXISTS conversations (
        a2rchi_service TEXT NOT NULL,
        conversation_id INTEGER NOT NULL,
        message_id SERIAL,
        sender TEXT NOT NULL,
        content TEXT NOT NULL,
        link TEXT NOT NULL,
        context TEXT NOT NULL,
        ts TIMESTAMP NOT NULL,
        conf_id INTEGER NOT NULL,
        PRIMARY KEY (message_id),
        FOREIGN KEY (conf_id) REFERENCES configs(config_id),
        FOREIGN KEY (conversation_id) REFERENCES conversation_metadata(conversation_id) ON DELETE CASCADE
    );
    CREATE TABLE IF NOT EXISTS feedback (
        mid INTEGER NOT NULL,
        feedback_ts TIMESTAMP NOT NULL,
        feedback TEXT NOT NULL,
        feedback_msg TEXT,
        incorrect BOOLEAN,
        unhelpful BOOLEAN,
        inappropriate BOOLEAN,
        PRIMARY KEY (mid, feedback_ts),
        FOREIGN KEY (mid) REFERENCES conversations(message_id) ON DELETE CASCADE
    );
    CREATE TABLE IF NOT EXISTS timing (
        mid INTEGER NOT NULL,
        client_sent_msg_ts TIMESTAMP NOT NULL,
        server_received_msg_ts TIMESTAMP NOT NULL,
        lock_acquisition_ts TIMESTAMP NOT NULL,
        vectorstore_update_ts TIMESTAMP NOT NULL,
        query_convo_history_ts TIMESTAMP NOT NULL,
        chain_finished_ts TIMESTAMP NOT NULL,
        a2rchi_message_ts TIMESTAMP NOT NULL,
        insert_convo_ts TIMESTAMP NOT NULL,
        finish_call_ts TIMESTAMP NOT NULL,
        server_response_msg_ts TIMESTAMP NOT NULL,
        msg_duration INTERVAL SECOND NOT NULL,
        PRIMARY KEY (mid),
        FOREIGN KEY (mid) REFERENCES conversations(message_id) ON DELETE CASCADE
    );
---
apiVersion: v1
kind: Secret
metadata:
  name: a2rchi-postgres
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ (index .Values.envSecret.keys "PG_PASSWORD") | default "changeme" | quote }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: a2rchi-postgres
spec:
  selector:
    matchLabels:
      app: a2rchi-postgres
  serviceName: a2rchi-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: a2rchi-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: a2rchi-postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: postgres
          ports:
            - containerPort: 5432
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
            {{- if .Values.postgres.persistence.enabled }}
            - name: data
              mountPath: /bitnami/postgresql
            {{- end }}
      volumes:
        - name: init-sql
          configMap:
            name: a2rchi-postgres-init
  {{- if .Values.postgres.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteMany" ]
        storageClassName: {{ .Values.postgres.persistence.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.postgres.persistence.size }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: a2rchi-postgres
  ports:
    - name: db
      port: 5432
      targetPort: 5432
{{- end }}

