apiVersion: v1
kind: Secret
metadata:
    name: munge-key
    namespace: cms
type: Opaque
stringData:
    munge.key: ENC[AES256_GCM,data:cBQFNEXPQ2Q5aHKVLb8XyS86n6uhpaKVqCjN266FoVzaAtEd6lovvH6ZcPJ51BiTJ+OafOke+2cfW0PNl+AjSQ==,iv:bgWkHStSRbv1xo1owCSL2zGCUI1YVjzIEtnk3WpLGyI=,tag:BZ68xSn+iQme2ba9UcLIdg==,type:str]
sops:
    age:
        - recipient: age1pccfws6yghzqtg5v9228nrvs23w5thsxpr7w4kmmksn435ldev5sqkpj08
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZDF3ckVyanFZRGQ3Mjk2
            THNtSnpZaWR5L3o5SitBczgyS0t4enFsY1hVCkpJR2JwYit2cVNKbzFiT3lRWDFQ
            eWJ3UUFMK2hSODlaaE5RNk1rUFBQTE0KLS0tIGUxYjNLOXZaMFVLeFhCT2Y2a1Rr
            STNGZjJPeUZmMGNTNmJmQ1V4Ym5BNkEKgxTTj27Ymk0C+RdKx00EQUz+8qtzn0Yy
            +sUE/1HbLAUSxdYwO7XQgg8ATKpYU1Ohdvyno2LQ4k06P1x1Eebv/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-08T17:04:05Z"
    mac: ENC[AES256_GCM,data:iLZEOlnoVE+zC2F+tvT1PHtpByv+dCB91t523nh/07olUwX+SjJOcGwYxxPU49qF48Vr9VCOChzAHfdBvDh666H0ioeSJUODc5iq9zZMiLzMnPz9quK3hVhUtNXMsCOCM0HFY4fTEcOfzee/3Ict/e0XjukNizUoWSuzgLHzTlk=,iv:RMcVwT2oc2WvsqeAmPq33IaOsw3pSaTSwcRogMqbNZ4=,tag:8A4rHHDCx8v2EyuL2GPwXA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
