#!/usr/bin/env bash
#
# Validate everything Flux consumes, the same way Flux consumes it:
#
#   1. `kustomize build` each kustomize root under deploy/ (and standalone roots)
#   2. apply that environment's postBuild.substitute variables, parsed straight
#      from its flux-kustomization.yaml (no duplicated values — single source
#      of truth), via `flux envsubst`
#   3. validate the rendered manifests with kubeconform against upstream
#      Kubernetes schemas + the CRDs-catalog (Flux CRDs, monitoring CRDs, ...)
#   4. `helm template` every HelmRelease found in the rendered stream, with
#      the chart version, HelmRepository URL and valuesFrom-ConfigMap values
#      resolved from that same stream — this is what catches breaking chart
#      schema changes when a chart version is bumped (e.g. by Renovate).
#
# Bootstrap objects (flux-kustomization.yaml / git-repository.yaml) are
# validated directly, since they are applied out-of-band.
#
# Requirements: kustomize, flux, yq (v4), kubeconform, helm
# Run locally:  ./scripts/validate-manifests.sh
#
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

# Rough match for the cluster's Kubernetes version (helm .Capabilities).
KUBE_VERSION="${KUBE_VERSION:-1.30.0}"

KUBECONFORM=(
	kubeconform
	-summary
	-schema-location default
	-schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json'
	# kagent CRDs have no published JSON schema (not in CRDs-catalog).
	-skip Agent,ModelConfig
)

workdir=$(mktemp -d)
trap 'rm -rf "$workdir"' EXIT
failed=0

# Render one Flux environment exactly like kustomize-controller does:
# LoadRestrictionsNone + non-strict postBuild substitution.
render_env() {
	local env_dir=$1
	(
		while IFS='=' read -r key value; do
			export "${key}=${value}"
		done < <(yq -r '.spec.postBuild.substitute // {} | to_entries[] | .key + "=" + .value' \
			"${env_dir}flux-kustomization.yaml")
		kustomize build --load-restrictor LoadRestrictionsNone "$env_dir" | flux envsubst
	)
}

# helm-template every HelmRelease in a rendered stream. Identical
# (repo, chart, version, values) combinations are rendered only once.
# (newline-joined list, not an assoc array: macOS ships bash 3.2)
seen_releases=""
validate_helmreleases() {
	local rendered=$1
	local repo_lookup=$2 # union of all rendered envs: HelmRepositories may be
	# created by a sibling Flux Kustomization on the same cluster
	local name chart version src_name src_kind repo_url repo_type values_args cm key i
	while IFS= read -r name; do
		chart=$(yq ea "select(.kind==\"HelmRelease\" and .metadata.name==\"$name\") | .spec.chart.spec.chart" "$rendered")
		version=$(yq ea "select(.kind==\"HelmRelease\" and .metadata.name==\"$name\") | .spec.chart.spec.version" "$rendered")
		src_name=$(yq ea "select(.kind==\"HelmRelease\" and .metadata.name==\"$name\") | .spec.chart.spec.sourceRef.name" "$rendered")
		src_kind=$(yq ea "select(.kind==\"HelmRelease\" and .metadata.name==\"$name\") | .spec.chart.spec.sourceRef.kind" "$rendered")

		if [[ "$src_kind" != "HelmRepository" ]]; then
			echo "  skip ${name}: chart sourced from ${src_kind} '${src_name}' (no registry version to validate)"
			continue
		fi

		repo_url=$(yq ea "select(.kind==\"HelmRepository\" and .metadata.name==\"$src_name\") | .spec.url" "$repo_lookup" | head -1)
		repo_type=$(yq ea "select(.kind==\"HelmRepository\" and .metadata.name==\"$src_name\") | .spec.type // \"default\"" "$repo_lookup" | head -1)

		if [[ -z "$repo_url" || "$repo_url" == "null" ]]; then
			echo "✗ ${name}: HelmRepository '${src_name}' not found in any rendered environment" >&2
			failed=1
			continue
		fi

		# Resolve valuesFrom ConfigMaps (generated by kustomize from values.yaml
		# files) into temp files, in order.
		values_args=()
		i=0
		while IFS='|' read -r cm key; do
			[[ -z "$cm" ]] && continue
			yq ea "select(.kind==\"ConfigMap\" and .metadata.name==\"$cm\") | .data[\"$key\"]" \
				"$rendered" >"$workdir/${name}-values-${i}.yaml"
			if [[ ! -s "$workdir/${name}-values-${i}.yaml" ]]; then
				echo "✗ ${name}: valuesFrom ConfigMap '${cm}' (key ${key}) not found" >&2
				failed=1
				continue 2
			fi
			values_args+=(-f "$workdir/${name}-values-${i}.yaml")
			i=$((i + 1))
		done < <(yq ea "select(.kind==\"HelmRelease\" and .metadata.name==\"$name\") | .spec.valuesFrom[]? | .name + \"|\" + (.valuesKey // \"values.yaml\")" "$rendered")

		# Inline .spec.values, if any.
		if [[ $(yq ea "select(.kind==\"HelmRelease\" and .metadata.name==\"$name\") | has(\"spec\") and .spec | has(\"values\")" "$rendered" | head -1) == "true" ]]; then
			yq ea "select(.kind==\"HelmRelease\" and .metadata.name==\"$name\") | .spec.values" \
				"$rendered" >"$workdir/${name}-values-inline.yaml"
			values_args+=(-f "$workdir/${name}-values-inline.yaml")
		fi

		local fingerprint
		fingerprint="${repo_url}|${chart}|${version}|$(cat "${values_args[@]:1}" 2>/dev/null | shasum | cut -d' ' -f1)"
		if [[ "$seen_releases" == *"$fingerprint"* ]]; then
			continue
		fi
		seen_releases="${seen_releases}${fingerprint}"$'\n'

		echo "  helm template ${name} (${chart}@${version} from ${repo_url})"
		local helm_src
		if [[ "$repo_type" == "oci" ]]; then
			helm_src=("${repo_url}/${chart}")
		else
			helm_src=("$chart" --repo "$repo_url")
		fi
		if ! helm template "$name" "${helm_src[@]}" \
			--version "$version" \
			--kube-version "$KUBE_VERSION" \
			--namespace cms \
			"${values_args[@]}" >/dev/null; then
			echo "✗ ${name}: helm template failed" >&2
			failed=1
		fi
	done < <(yq ea -N 'select(.kind=="HelmRelease") | .metadata.name' "$rendered")
}

# --- Flux-managed environments -------------------------------------------
# Pass 1: render everything (also builds the cross-env HelmRepository lookup).
for env_dir in deploy/*/; do
	[[ -f "${env_dir}kustomization.yaml" ]] || continue
	name=$(basename "$env_dir")
	rendered="$workdir/rendered-${name}.yaml"
	if ! render_env "$env_dir" >"$rendered"; then
		echo "✗ ${name}: kustomize build failed" >&2
		failed=1
	fi
done
for f in "$workdir"/rendered-*.yaml; do
	cat "$f"
	echo "---"
done >"$workdir/rendered-union.yaml"

# Pass 2: validate.
for rendered in "$workdir"/rendered-*.yaml; do
	[[ "$rendered" == *rendered-union.yaml ]] && continue
	name=$(basename "$rendered" .yaml)
	echo "──── ${name#rendered-} ────"
	"${KUBECONFORM[@]}" <"$rendered" || failed=1
	validate_helmreleases "$rendered" "$workdir/rendered-union.yaml"
done

# --- Standalone kustomize roots (applied out-of-band) --------------------
for root in docker/kaniko-build-jobs; do
	echo "──── ${root} ────"
	if ! kustomize build "$root" | "${KUBECONFORM[@]}"; then
		failed=1
	fi
done

# --- Flux bootstrap objects ----------------------------------------------
echo "──── flux bootstrap objects ────"
if ! "${KUBECONFORM[@]}" deploy/*/flux-kustomization.yaml deploy/*/git-repository.yaml; then
	failed=1
fi

if [[ $failed -ne 0 ]]; then
	echo "✗ manifest validation FAILED" >&2
	exit 1
fi
echo "✓ all manifests valid"
