#!/usr/bin/env bash
#
# Validate everything Flux consumes, the same way Flux consumes it:
#
#   1. `kustomize build` each kustomize root under deploy/ (and standalone roots)
#   2. apply that environment's postBuild.substitute variables, parsed straight
#      from its flux-kustomization.yaml (no duplicated values — single source
#      of truth), via `flux envsubst`
#   3. validate the rendered manifests with kubeconform against upstream
#      Kubernetes schemas + the CRDs-catalog (Flux CRDs, monitoring CRDs, ...)
#   4. `helm template` every HelmRelease found in the rendered stream, with
#      the chart version, HelmRepository URL and valuesFrom-ConfigMap values
#      resolved from that same stream — this is what catches breaking chart
#      schema changes when a chart version is bumped (e.g. by Renovate).
#   5. `promtool check rules` on Prometheus alerting/recording rules embedded
#      in Helm values — a typo'd PromQL expression otherwise deploys silently
#      and the alert simply never fires.
#
# Bootstrap objects (flux-kustomization.yaml / git-repository.yaml) are
# validated directly, since they are applied out-of-band.
#
# Tripwires: the run fails if suspiciously few HelmReleases/resources were
# validated — a parsing regression must turn the build red, never silently
# validate nothing.
#
# Requirements: kustomize, flux, yq (v4), kubeconform, helm, promtool
# Run locally:  ./scripts/validate-manifests.sh
#
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

# Rough match for the cluster's Kubernetes version (helm .Capabilities).
KUBE_VERSION="${KUBE_VERSION:-1.30.0}"

# shellcheck disable=SC2054  # commas below are kubeconform list syntax
KUBECONFORM=(
	kubeconform
	-summary
	-schema-location default
	-schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json'
	# kagent CRDs have no published JSON schema (not in CRDs-catalog).
	-skip Agent,ModelConfig
)

workdir=$(mktemp -d)
trap 'rm -rf "$workdir"' EXIT
failed=0
releases_seen=0

# Render one Flux environment exactly like kustomize-controller does:
# LoadRestrictionsNone + non-strict postBuild substitution, honouring the
# `kustomize.toolkit.fluxcd.io/substitute: disabled` per-resource annotation
# (used by ConfigMaps that carry shell scripts).
SUBST_DISABLED='.metadata.annotations["kustomize.toolkit.fluxcd.io/substitute"] == "disabled"'
render_env() {
	local env_dir=$1
	(
		while IFS='=' read -r key value; do
			export "${key}=${value}"
		done < <(yq -r '.spec.postBuild.substitute // {} | to_entries[] | .key + "=" + .value' \
			"${env_dir}flux-kustomization.yaml")
		kustomize build --load-restrictor LoadRestrictionsNone "$env_dir" >"$workdir/raw.yaml"
		yq "select(${SUBST_DISABLED} | not)" "$workdir/raw.yaml" | flux envsubst
		echo "---"
		yq "select(${SUBST_DISABLED})" "$workdir/raw.yaml"
	)
}

# helm-template every HelmRelease in a rendered stream. Identical
# (repo, chart, version, values) combinations are rendered only once.
# (newline-joined list, not an assoc array: macOS ships bash 3.2)
seen_releases=""
validate_helmreleases() {
	local rendered=$1
	local repos_file=$2 # "name|type|url" lines from ALL envs: HelmRepositories
	# may be created by a sibling Flux Kustomization on the same cluster
	local name chart version src_name src_kind repo_line repo_url repo_type
	local values_files values_args vhash cm key i
	while IFS= read -r name; do
		releases_seen=$((releases_seen + 1))
		chart=$(yq "select(.kind==\"HelmRelease\" and .metadata.name==\"$name\") | .spec.chart.spec.chart" "$rendered")
		version=$(yq "select(.kind==\"HelmRelease\" and .metadata.name==\"$name\") | .spec.chart.spec.version" "$rendered")
		src_name=$(yq "select(.kind==\"HelmRelease\" and .metadata.name==\"$name\") | .spec.chart.spec.sourceRef.name" "$rendered")
		src_kind=$(yq "select(.kind==\"HelmRelease\" and .metadata.name==\"$name\") | .spec.chart.spec.sourceRef.kind" "$rendered")

		if [[ "$src_kind" != "HelmRepository" ]]; then
			echo "  skip ${name}: chart sourced from ${src_kind} '${src_name}' (no registry version to validate)"
			continue
		fi

		if [[ -z "$version" || "$version" == "null" ]]; then
			echo "✗ ${name}: chart version is not pinned (omitted version = Flux silently tracks latest)" >&2
			failed=1
			continue
		fi

		repo_line=$(grep -m1 "^${src_name}|" "$repos_file" || true)
		if [[ -z "$repo_line" ]]; then
			echo "✗ ${name}: HelmRepository '${src_name}' not found in any rendered environment" >&2
			failed=1
			continue
		fi
		repo_type=$(cut -d'|' -f2 <<<"$repo_line")
		repo_url=$(cut -d'|' -f3- <<<"$repo_line")

		# Resolve valuesFrom ConfigMaps (generated by kustomize from values.yaml
		# files) into temp files, in order.
		values_files=()
		i=0
		while IFS='|' read -r cm key; do
			[[ -z "$cm" ]] && continue
			yq "select(.kind==\"ConfigMap\" and .metadata.name==\"$cm\") | .data[\"$key\"]" \
				"$rendered" >"$workdir/${name}-values-${i}.yaml"
			if [[ ! -s "$workdir/${name}-values-${i}.yaml" ]]; then
				echo "✗ ${name}: valuesFrom ConfigMap '${cm}' (key ${key}) not found" >&2
				failed=1
				continue 2
			fi
			values_files+=("$workdir/${name}-values-${i}.yaml")
			i=$((i + 1))
		done < <(yq "select(.kind==\"HelmRelease\" and .metadata.name==\"$name\") | .spec.valuesFrom[]? | .name + \"|\" + (.valuesKey // \"values.yaml\")" "$rendered")

		# Inline .spec.values, if any.
		if [[ $(yq "select(.kind==\"HelmRelease\" and .metadata.name==\"$name\") | .spec | has(\"values\")" "$rendered") == "true" ]]; then
			yq "select(.kind==\"HelmRelease\" and .metadata.name==\"$name\") | .spec.values" \
				"$rendered" >"$workdir/${name}-values-inline.yaml"
			values_files+=("$workdir/${name}-values-inline.yaml")
		fi

		values_args=()
		vhash="none"
		if [[ ${#values_files[@]} -gt 0 ]]; then
			vhash=$(cat "${values_files[@]}" | shasum | cut -d' ' -f1)
			for f in "${values_files[@]}"; do
				values_args+=(-f "$f")
			done
		fi

		local fingerprint="${repo_url}|${chart}|${version}|${vhash}"
		if [[ "$seen_releases" == *"$fingerprint"* ]]; then
			continue
		fi
		seen_releases="${seen_releases}${fingerprint}"$'\n'

		echo "  helm template ${name} (${chart}@${version} from ${repo_url})"
		local helm_src
		if [[ "$repo_type" == "oci" ]]; then
			helm_src=("${repo_url}/${chart}")
		else
			helm_src=("$chart" --repo "$repo_url")
		fi
		if ! helm template "$name" "${helm_src[@]}" \
			--version "$version" \
			--kube-version "$KUBE_VERSION" \
			--namespace cms \
			${values_args[@]+"${values_args[@]}"} >/dev/null; then
			echo "✗ ${name}: helm template failed" >&2
			failed=1
		fi
	done < <(yq -N 'select(.kind=="HelmRelease") | .metadata.name' "$rendered")
}

# --- Flux-managed environments -------------------------------------------
# Pass 1: render everything (also builds the cross-env HelmRepository lookup).
for env_dir in deploy/*/; do
	[[ -f "${env_dir}kustomization.yaml" ]] || continue
	name=$(basename "$env_dir")
	rendered="$workdir/rendered-${name}.yaml"
	if ! render_env "$env_dir" >"$rendered"; then
		echo "✗ ${name}: kustomize build failed" >&2
		failed=1
	fi
done
# (named so the rendered-*.yaml glob can never match it: the output redirect
# creates the file before the glob expands)
for f in "$workdir"/rendered-*.yaml; do
	cat "$f"
	echo "---"
done >"$workdir/union.yaml"

# One small lookup table of every HelmRepository across all envs
# ("name|type|url" lines) — releases may reference a repo created by a
# sibling Flux Kustomization on the same cluster.
yq -N 'select(.kind=="HelmRepository") | .metadata.name + "|" + (.spec.type // "default") + "|" + .spec.url' \
	"$workdir/union.yaml" | sort -u >"$workdir/helm-repos.txt"

# Pass 2: validate.
for rendered in "$workdir"/rendered-*.yaml; do
	name=$(basename "$rendered" .yaml)
	echo "──── ${name#rendered-} ────"
	"${KUBECONFORM[@]}" <"$rendered" || failed=1
	validate_helmreleases "$rendered" "$workdir/helm-repos.txt"
done

# --- Standalone kustomize roots (applied out-of-band) --------------------
# shellcheck disable=SC2043  # single-element list: more roots may be added
for root in docker/kaniko-build-jobs; do
	echo "──── ${root} ────"
	if ! kustomize build "$root" | "${KUBECONFORM[@]}"; then
		failed=1
	fi
done

# --- Flux bootstrap objects ----------------------------------------------
echo "──── flux bootstrap objects ────"
if ! "${KUBECONFORM[@]}" deploy/*/flux-kustomization.yaml deploy/*/git-repository.yaml; then
	failed=1
fi

# --- Prometheus rules ------------------------------------------------------
echo "──── prometheus rules ────"
for values_file in $(git grep -lE "alerting_rules|recording_rules" -- 'apps/**/values.yaml'); do
	for key in alerting_rules.yml recording_rules.yml; do
		[[ $(yq ".serverFiles | has(\"$key\")" "$values_file") == "true" ]] || continue
		yq ".serverFiles[\"$key\"]" "$values_file" >"$workdir/rules.yml"
		echo "  promtool check ${values_file} → ${key}"
		if ! promtool check rules "$workdir/rules.yml" >/dev/null; then
			echo "✗ ${values_file}: ${key} failed promtool validation" >&2
			promtool check rules "$workdir/rules.yml" || true
			failed=1
		fi
	done
done

# --- Tripwires against silent pass-through --------------------------------
# Counts well below today's real numbers (~19 releases, ~230 resources) mean
# the extraction logic broke, not that the platform shrank.
total_resources=$(yq -N 'select(.kind != null) | .kind' "$workdir/union.yaml" | grep -c .)
if [[ $releases_seen -lt 10 || $total_resources -lt 100 ]]; then
	echo "✗ tripwire: only ${releases_seen} HelmReleases / ${total_resources} resources found — validator is broken" >&2
	failed=1
fi
echo "(validated ${releases_seen} HelmRelease references, ${total_resources} resources)"

if [[ $failed -ne 0 ]]; then
	echo "✗ manifest validation FAILED" >&2
	exit 1
fi
echo "✓ all manifests valid"
