apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - repository.yaml
  - helmrelease.yaml
configMapGenerator:
- name: dask-gateway-flux-config
  namespace: cms
  files:
  - values.yaml
  options:
    disableNameSuffixHash: true