apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pyroscope
  namespace: cms
spec:
  interval: 1m
  chart:
    spec:
      chart: pyroscope
      version: "1.15.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: cms
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: pyroscope-config
      valuesKey: values.yaml
