apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dask-gateway-k8s-pyroscope
  namespace: cms
spec:
  interval: 1m
  chart:
    spec:
      chart: dask-gateway
      version: "2024.1.0"
      sourceRef:
        kind: HelmRepository
        name: dask
        namespace: cms
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: dask-gateway-k8s-pyroscope-config
      valuesKey: values.yaml
