apiVersion: v1
kind: Secret
metadata:
  name: servicex-secrets-eos
type: Opaque
stringData:
  accesskey: ""
  flaskSecretKey: ENC[AES256_GCM,data:qYx9gUGDTz+xfrPhmBfVK3a//vP7CzCMDQhZht+DQpY=,iv:dcdMDqlnqhsjLkh+x9bPUk7EH0SUV1vXaZtDxmnjLFU=,tag:BORErZ2w+hRcQjlVdQeHMg==,type:str]
  jwtSecretKey: ENC[AES256_GCM,data:bzwZo3/oEuGAAn9z72AV5Px7mCRcmeZS+HMiOI9Mhl0=,iv:PanLP1JiB9/EqUhlfcPlhJ4qSoV1Y0RJUQTt9j+IHec=,tag:rJwO20NYzWiA7/GkDgC51A==,type:str]
  mailgunAPIKey: ""
  oauthClientID: ""
  oauthClientSecret: ""
  oauthMetadataURL: ""
  postgresql-password: ENC[AES256_GCM,data:P2/+i+8Uk+sLgCtLYkUxYLRcboh0BmviaMeG6SZxceM=,iv:0H4T2PQgCogRTvv831zzaKaznuEEziYPpA2z6T34NhE=,tag:PwKlYM4Tb9NmnyftoiShzw==,type:str]
  rabbitmq-password: ENC[AES256_GCM,data:WkhK3L3oQ6VFtKMOjMpRc0Ns6Xv2TZPu96FzVYNIBS0=,iv:j/5Omd7rJKYgxqcAFhJpQuBBcfaV54HwzVgCXrjC3so=,tag:PBeLTjr+uNtP5FG0zze5AQ==,type:str]
  secretkey: ""
  slackSigningSecret: ""
  slackSignupWebhook: ""
sops:
  age:
    - recipient: age1pccfws6yghzqtg5v9228nrvs23w5thsxpr7w4kmmksn435ldev5sqkpj08
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTXh4K1RWcTREbUk1VmhH
        ank2NkdlOVdia3dNczJXZVBUTnNKRDhraGhzCjZwdzVwZ1JCbEFHU2xwbTNwK2Zq
        dit4ZzdSOVRuR2d5VWxHam5xV1kxRzgKLS0tIGdVS01FUTVVRllvWFR6Q2F5SDlU
        MGFmWlZwVTVRdFlOdS8rZ3Ftdy9HV3MKaeIhA7YNNab9JrK37FP0Q7Ci/B+dBANb
        PLyF4oK5ogQvqgjR1lXtD1ot3MY9njHZ339dBwluFqftn+VRv9bNYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-10-09T14:09:33Z"
  mac: ENC[AES256_GCM,data:96eViVdU8MS4+kscIKLuYveSgoxENLbUai8QO6fZMxEYpk9Sx53DuTBRcJ0hDTwnmKVavrrxgM2DSsIvezb7+BIjxG5PdErSG+UJi/MNLTvqzlUcnt/tM4m4zY5+oWtj5j1seHqjjqFwOEYRy2ANyWiwVkch7qNsDuvNJo7nd0g=,iv:vlh+H72VJHkn48AwMu9F3OzKxlQtk6QkhqwlBL5n0S0=,tag:0Tb4V/mNsbwA3DLaYKIejg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
