apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs
  annotations:
    helm.sh/resource-policy: keep
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1
  storageClassName: cvmfs
