apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  interval: 1m
  chart:
    spec:
      chart: prometheus
      version: "27.3.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 1m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-config
      valuesKey: values.yaml
