apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - servicemonitors.yaml
  - pod-monitor-svc.yaml
  - pvc.yaml
  - rbac.yaml
configMapGenerator:
  - name: prometheus-config
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
