apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-pvc
  labels:
    app: prometheus
spec:
  storageClassName: ${multinode_storage_class}
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 40Gi
