apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-pvc
  namespace: cms
  labels:
    app: prometheus
spec:
  storageClassName: depot-cloud-filesystem
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 40Gi
