apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-sa-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["list", "watch"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-sa
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-sa-rb
subjects:
  - kind: ServiceAccount
    name: prometheus-sa
roleRef:
  kind: Role
  name: prometheus-sa-role
  apiGroup: rbac.authorization.k8s.io
