apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: purdue-af-flux
  namespace: cms-dev
spec:
  interval: 1m
  timeout: 1m
  path: "./apps/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: purdue-af
  targetNamespace: cms-dev
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  patches:
    - patch: |
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: delete-all-ingresses
        $patch: delete
      target:
        kind: Ingress
