apiVersion: batch/v1
kind: CronJob
metadata:
  name: analysis-grand-challenge
  namespace: cms
spec:
  schedule: "0 */3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector: {'cms-af-prod': 'true'}
          tolerations:
          - key: "hub.jupyter.org/dedicated"
            operator: "Equal"
            value: "cms-af"
            effect: "NoSchedule"
          containers:
          - name: agc-smoke-test
            image: geddes-registry.rcac.purdue.edu/cms/agc-smoke-test:latest
            volumeMounts:
            - name: depot
              mountPath: /depot/cms
              mountPropagation: HostToContainer
            - name: work
              mountPath: /work/
              mountPropagation: HostToContainer
            resources:
              requests:
                memory: "4Gi"
                cpu: "1"
              limits:
                memory: "4Gi"
                cpu: "1"
          restartPolicy: OnFailure
          volumes:
          - name: depot
            nfs:
              server: datadepot.rcac.purdue.edu
              path: /depot/cms
          - name: work
            persistentVolumeClaim:
              claimName: af-shared-storage
