apiVersion: v1
kind: Secret
metadata:
    name: flux-github-token
    namespace: cms
    labels:
        app.kubernetes.io/managed-by: fluxcd
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:hNSmQxXG3Ahc8M4=,iv:LpwA4lppd5tKhcPFABQ42mlTz4WT7S+Wtx01QC4k26g=,tag:buOLHF8ZnMaOkm24TVG2nQ==,type:str]
    password: ENC[AES256_GCM,data:+/3Ce376HdmYgh76YMOUKVC9bsXT1gxpOIXnGqBkkwk+pjA/mrHo/3w4ko7/Og8Zlz+WH7C7ORNp0s3cVHdo3CcHKpbwv/IXFEjGaDAFtL6fJUMnz7SchR0ocaX2,iv:ICI5qAF+MXVfDcBRaWUqa4OtV6k6c+MWh1OVSSzDFUY=,tag:0rYUqXOdRy4OOC3sDp9HEQ==,type:str]
    token: ENC[AES256_GCM,data:THqiiJqQ+PAWTJiQ+A1oLIxRokwLVGndveJmBZ3w+Vw6J/+c3K6rKZbIR2uga/FsMZ8VyDaQRPG7LA+v+vRrPau7Lz0QU0kQ3DwYjeS6B7fhkJF7nlPMWcer0VPI,iv:kIYu21vy+3QJzBT6/+3HzEjhXWtyg0dToz38jo1zvJ0=,tag:jpU4tWKuw82P7Z4oGVpn+w==,type:str]
sops:
    age:
        - recipient: age1pccfws6yghzqtg5v9228nrvs23w5thsxpr7w4kmmksn435ldev5sqkpj08
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1SUE4MzhnMkZCeXdhcHhG
            SnhDVTVnNXJzUkFmTGhRZjdPSWlwZngySGhzCk9uaFJKbVlib2EybnBYcG1qMjhR
            YUtpSDdGSVJQZlppRElZWGNFKzN0TVkKLS0tIDVHVC9oTUg0blhQTUQ4ZmZ0cktz
            RU00c1RKQmswYlZOcUpRalprekpzY2cK0JTDCioG2G8Xr4ALBUIRZn80KEodZ4Cu
            UvhxqHYzJeZB9fUrlOE8F1TC75LLqLDHBumm1mx2Mt4SW+RXsGb5ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-08T14:44:54Z"
    mac: ENC[AES256_GCM,data:lWxkKsRLn1gpmKk7Fubze51cvy6/3stW4NR28XHa73Myg0SkdRvId/mK2EaIELpt6Dy7AmraJ85meP6+6dvER5NpClABJ2HEIrjNdu28b8kDHAEoWs1q3avFKt24XhpeISmD43nI0C6wtSwdkCjIhEIMqxs6sN6ZWHRuTBMBmss=,iv:kcWJ1SnvdZWCrPoW1n+Y4HJqtySY8Jb3uT3WsjqluXM=,tag:RYAlj4qFZru8ZtriBYoATw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
