apiVersion: v1
kind: Secret
metadata:
  name: flux-purdue-af-auth
  namespace: cms
  labels:
    app.kubernetes.io/managed-by: fluxcd
type: Opaque
stringData:
  username: kondratyevd
  password: <github_token>