apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: purdue-af-flux
  namespace: cms-dev
spec:
  interval: 1m
  timeout: 1m
  path: "./apps/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: purdue-af
  targetNamespace: cms-dev
  decryption:
    provider: sops
    secretRef:
      name: sops-age

  patches:
    # Remove ALL Ingresses
    - target:
        kind: Ingress
      patch: |
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: delete-all-ingresses # dummy, required for SM patch shape
        $patch: delete

    # Suspend ALL CronJobs
    - target:
        group: batch
        version: v1
        kind: CronJob
      patch: |
        apiVersion: batch/v1
        kind: CronJob
        metadata:
          name: suspend-all-cronjobs # dummy
        spec:
          suspend: true

    # Suspend ALL Jobs
    - target:
        group: batch
        version: v1
        kind: Job
      patch: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: suspend-all-jobs # dummy
        spec:
          suspend: true
