apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: purdue-af-flux
  namespace: cms
spec:
  interval: 5m
  timeout: 5m
  path: "./dask-gateway/flux"
  prune: true
  sourceRef:
    kind: GitRepository
    name: purdue-af
    namespace: cms