apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: purdue-af-flux
  namespace: cms
spec:
  interval: 1m
  timeout: 1m
  path: "./apps/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: purdue-af
  targetNamespace: cms
  postBuild:
    substitute:
      namespace: "cms"
      jupyterhub_db_pv_selector: '{matchLabels: {purdue-af-db: "true"}}'
      jupyterhub_db_storage_class: ""
  decryption:
    provider: sops
    secretRef:
      name: sops-age
