apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conda-envs
  namespace: cms
spec:
  storageClassName: geddes-standard-multinode
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 40Gi
