singleuser:
  podNameTemplate: "purdue-af-{userid}"
  uid: 0
  cmd: 
  image:
    name: "geddes-registry.rcac.purdue.edu/cms/cmsaf-alma8"
    tag: "0.9.5"
  extraLabels:
    username_unescaped: "{legacy_escape_username}"
    docker_image_tag: "0.9.5"
  profileList:
    - display_name: "JupyterLab based on CERN Alma8"
      default: true
      description: "Container with pre-installed pythonic analysis software, as well as CVMFS and EOS mounts"
      kubespawner_override:
        node_selector: {'cms-af-dev': 'true'}
        lifecycle_hooks:
          preStop:
            exec:
              command: ["bash", "-c", "rm -f eos-cern"]
      profile_options:
        node:
          display_name: "Node"
          choices:
            0: 
              display_name: "Auto (cms-af-dev: true)"
              kubespawner_override:
                node_selector:
                  cms-af-dev: "true"
            1: 
              display_name: "geddes-b013"
              kubespawner_override:
                node_selector:
                  kubernetes.io/hostname: geddes-b013
            2: 
              display_name: "geddes-b014"
              kubespawner_override:
                node_selector:
                  kubernetes.io/hostname: geddes-b014
            3: 
              display_name: "geddes-b015"
              kubespawner_override:
                node_selector:
                  kubernetes.io/hostname: geddes-b015
            4: 
              display_name: "geddes-g000"
              kubespawner_override:
                node_selector:
                  kubernetes.io/hostname: geddes-g000
            5: 
              display_name: "geddes-g001"
              kubespawner_override:
                node_selector:
                  kubernetes.io/hostname: geddes-g001
            6: 
              display_name: "geddes-g002"
              kubespawner_override:
                node_selector:
                  kubernetes.io/hostname: geddes-g002
            7: 
              display_name: "paf-a00"
              kubespawner_override:
                node_selector:
                  kubernetes.io/hostname: paf-a00
            8: 
              display_name: "paf-a01"
              kubespawner_override:
                node_selector:
                  kubernetes.io/hostname: paf-a01
            9: 
              display_name: "paf-a02"
              kubespawner_override:
                node_selector:
                  kubernetes.io/hostname: paf-a02
            10: 
              display_name: "cms-fe00"
              kubespawner_override:
                node_selector:
                  kubernetes.io/hostname: cms-fe00
            11: 
              display_name: "cms-fe01"
              kubespawner_override:
                node_selector:
                  kubernetes.io/hostname: cms-fe01

        cpu:
          display_name: "CPUs"
          choices:
            1:
              display_name: "4"
              kubespawner_override:
                cpu_limit: 4
                cpu_guarantee: 4
            2: 
              display_name: "16"
              kubespawner_override:
                cpu_limit: 16
                cpu_guarantee: 16
            3:
              display_name: "32"
              kubespawner_override:
                cpu_limit: 32
                cpu_guarantee: 32
        gpu:
          display_name: "GPUs"
          choices:
            1:
              display_name: "0"
              kubespawner_override:
                extra_resource_limits:
                  nvidia.com/mig-2g.10gb: "0"
            2:
              display_name: "1"
              kubespawner_override:
                extra_resource_limits:
                  nvidia.com/mig-2g.10gb: "1"
        memory:
          display_name: "Memory"
          choices:
            1:
              display_name: "16 GB"
              kubespawner_override:
                mem_limit: "16G"
                mem_guarantee: "16G"
            2:
              display_name: "32 GB"
              kubespawner_override:
                mem_limit: "32G" 
                mem_guarantee: "32G"
            3:
              display_name: "64 GB"
              kubespawner_override:
                mem_limit: "64G" 
                mem_guarantee: "64G"
    # - display_name: "JupyterLab v4 (AF v0.9.0)"
    #   kubespawner_override:
    #     image: "geddes-registry.rcac.purdue.edu/cms/cmsaf-alma8:0.9.0"
    #     node_selector:
    #       'cms-af-prod': 'true'
    #       # kubernetes.io/hostname: af-a01
    #   profile_options:
    #     cpu:
    #       display_name: "CPUs"
    #       choices:
    #         1:
    #           display_name: "4"
    #           kubespawner_override:
    #             cpu_limit: 4
    #             cpu_guarantee: 4
    #     memory:
    #       display_name: "Memory"
    #       choices:
    #         1:
    #           display_name: "16 GB"
    #           kubespawner_override:
    #             mem_limit: "16G"
    #             mem_guarantee: "16G"
    - display_name: "JupyterLab based on CentOS7"
      description: "Container with pre-installed pythonic analysis software, as well as CVMFS and EOS mounts"
      kubespawner_override:
        image: "geddes-registry.rcac.purdue.edu/cms/cmsaf-centos7:0.3"
        node_selector:
          'cms-af-dev': 'true'
          # kubernetes.io/hostname: af-a01
      profile_options:
        cpu:
          display_name: "CPUs"
          choices:
            1:
              display_name: "4"
              kubespawner_override:
                cpu_limit: 4
                cpu_guarantee: 4
        memory:
          display_name: "Memory"
          choices:
            1:
              display_name: "16 GB"
              kubespawner_override:
                mem_limit: "16G"
                mem_guarantee: "16G"
    - display_name: "hls4ml tutorial"
      description: ""
      kubespawner_override:
        image: ghcr.io/fastmachinelearning/hls4ml-tutorial/hls4ml-0.7.1-vivado-2019.2:dd18adb1d3fb1ac3bf18c2b7feb37f44c10b6262
        node_selector:
          kubernetes.io/hostname: af-a02
          # 'cms-af-prod': 'true'
        lifecycle_hooks:
          postStart:
            exec:
              command: [
                "bash", "-c", "if [ ! -d hls4ml-tutorial ]; then git clone https://github.com/fastmachinelearning/hls4ml-tutorial.git; fi; chown -R $NB_USER:$NB_USER /home/$NB_USER/hls4ml-tutorial",
              ]
        extraEnv:
          XILINX_VIVADO: "/opt/Xilinx/Vivado/2019.2"
      profile_options:
        cpu:
          display_name: "CPUs"
          choices:
            1:
              display_name: "4"
              kubespawner_override:
                cpu_limit: 4
                cpu_guarantee: 4
        memory:
          display_name: "Memory"
          choices:
            1:
              display_name: "32 GB"
              kubespawner_override:
                mem_limit: "32G"
                mem_guarantee: "32G"
  extraContainers:
    - name: af-pod-metrics
      image: geddes-registry.rcac.purdue.edu/cms/cmsaf-pod-metrics-sidecar:0.1
      command: [ "python", "/app/pod-metrics-exporter.py"]
      volumeMounts:
      - name: volume-{username}
        mountPath: /home/{legacy_escape_username}
  defaultUrl: "/lab"
  extraEnv:
    JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    GRANT_SUDO: "yes"
    NAMESPACE: "cms-dev"
  networkPolicy:
    enabled: false
  storage:
    capacity: 25Gi
    dynamic:
      storageClass: geddes-standard-multinode
      storageAccessModes:
        - ReadWriteMany
    homeMountPath: /home/{legacy_escape_username}
    extraVolumes:
      - name: cvmfs
        hostPath: 
          path: /cvmfs
      - name: eos
        hostPath: 
          path: /eos
      - name: work-test
        hostPath: 
          path: /work-test
      - name: depot
        nfs:
          server: datadepot.rcac.purdue.edu
          path: /depot/cms
      - name: kernels
        persistentVolumeClaim:
          claimName: kernels
      - name: munge-key
        secret:
          secretName: munge-key
    extraVolumeMounts:
      - name: cvmfs
        mountPath: /cvmfs
        mountPropagation: HostToContainer
      - name: eos
        mountPath: /eos
        mountPropagation: HostToContainer
      - name: depot
        mountPath: /depot/cms
        mountPropagation: HostToContainer
      - name: work-test
        mountPath: /work-test
        mountPropagation: HostToContainer
      - name: kernels
        mountPath: /kernels/
        mountPropagation: HostToContainer
      - mountPath: /etc/secrets/munge/
        name: munge-key
        readOnly: false
        mountPropagation: HostToContainer
  cloudMetadata:
    blockWithIptables: false

prePuller:
  hook:
    enabled: false
  continuous:
    enabled: false
hub:
  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/address-pool: geddes-private-pool
  nodeSelector: {'cms-af-prod': 'true'}
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 1
      memory: 2Gi
  extraVolumes:
    - name: purdue-auth
      secret:
        secretName: purdue-auth
    - name: cern-auth
      secret:
        secretName: cern-auth
    - name: auth-secret
      secret:
        secretName: auth-secret
  extraVolumeMounts:
    - mountPath: /etc/secrets/purdue-auth/
      name: purdue-auth
      readOnly: true
    - mountPath: /etc/secrets/cern-auth/
      name: cern-auth
      readOnly: true
  extraEnv:
    CILOGON_CLIENT_ID:
      valueFrom:
        secretKeyRef:
          name: auth-secret
          key: cilogon_client_id
    CILOGON_CLIENT_SECRET:
      valueFrom:
        secretKeyRef:
          name: auth-secret
          key: cilogon_client_secret
  extraFiles:
    00-custom-spawner:
      mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/custom-spawner.py
    01-set-user-info:
      mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/set-user-info.py
  config:
    PurdueCILogonOAuthenticator:
      auto_login: True
      auto_login_oauth2_authorize: True
      logout_redirect_url: https://cmsdev.geddes.rcac.purdue.edu/hub
      admin_users: ['dkondra']
      oauth_callback_url: https://cmsdev.geddes.rcac.purdue.edu/hub/oauth_callback
      enable_auth_state: true
      allowed_idps:
        https://cern.ch/login:
          allow_all: true
          username_derivation:
            username_claim: eppn
        https://idp.fnal.gov/idp/shibboleth:
          allow_all: true
          username_derivation:
            username_claim: eppn
        https://idp.purdue.edu/idp/shibboleth:
          allow_all: true
          username_derivation:
            username_claim: eppn
    JupyterHub:
      authenticator_class: cilogon
      admin_access: True

  tolerations:
    - key: "hub.jupyter.org/dedicated"
      operator: "Equal"
      value: "cms-af"
      effect: "NoSchedule"

scheduling:
  userScheduler:
    enabled: false
  userPods:
      tolerations:
        - key: "hub.jupyter.org/dedicated"
          operator: "Equal"
          value: "cms-af"
          effect: "NoSchedule"
        - key: "cmsfrontend"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
ingress:
 enabled: true
 hosts:
   - cmsdev.geddes.rcac.purdue.edu
cull:
#  concurrency: 10
 enabled: true
 every: 600
#  maxAge: 0
#  removeNamedServers: false
 timeout: 1209600
#  users: false

