apiVersion: v1
kind: Secret
metadata:
  name: self-repair-genai
type: Opaque
stringData:
  api-key: ENC[AES256_GCM,data:zyaHzebVE11i8gWnWJcu6xsMqEJ6iRlcZwplnjV0Is4MSfc=,iv:7rczpZAoDVOQ48JuawNtsjODufYJzh9PvlYMBu3m218=,tag:ZIYlOHDRR2ahuAw2aRybWg==,type:str]
sops:
  age:
    - recipient: age1pccfws6yghzqtg5v9228nrvs23w5thsxpr7w4kmmksn435ldev5sqkpj08
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcUlaUEEyZ0pSUDNRRkty
        emNlQU4zY1h2dzJVanpZK2k0bkRTMkZYU0g4CmZZNXlaalNpekZ5TXU3eU4rN1VC
        Vm8wUWZDNDFEMUNOZncrd3o3M1cxZmcKLS0tIFk3YXVCVithU2VYSXZRQjRhWEdk
        VEhVVjZKWllSVU1OeERUL0RNK0dKdDAKxTCotpplZOE+AsQTJV3OY+NH5jYA3qeb
        YVfDzmMQ9k8wbfRShfCPD9RBzuQ0SkBsPL4CUsaiepWC69X3rbVgng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-16T19:04:29Z"
  mac: ENC[AES256_GCM,data:lndHwU7unyGuFQxW+pQgTHxeWLIbgMDjKl0QNH85Z7JSOWT1hBB38K1jwIYLGAb987iO9I4CoIvLtghKcmCajnKhy/RTVbctsFsWlglnRDCSqYArRY4t68IWR40n/Yi2+gsgO481lzewXPFATibiAdl0aitiFHENJTN3Yol7TZc=,iv:YJ5y1mNIL/4Rza8zTAexVSw4cW5nIyglTfuTSzo4BUs=,tag:CcaV4pcBkp6t+IY5CwSClQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
