apiVersion: v1
kind: Secret
metadata:
  name: self-repair-github
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:xzA5MdIGnG6SKAnFCLBW8deISSX51OErXl6uQmJtdyEy5iBsM161T6t3b7KnChOG16CprnZmKHI1JILNoBV4cLi7UAxcUlkphCHsBmLwrA8CZAka3R4b2gEgexe7,iv:JN6tAR4IJgmCWDQ4S48M1N09+ENdYdizXEhlKEQaRF8=,tag:Ackb8gdLeclRZ0x6fCKcEg==,type:str]
sops:
  age:
    - recipient: age1pccfws6yghzqtg5v9228nrvs23w5thsxpr7w4kmmksn435ldev5sqkpj08
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybk9DeENISnUyS0paLzJM
        VmRUeEVwUTE5UFlrMG8zamcxa0llemJPYUdnCjFSK0xmMTVMQWtQUzBBZElkZE9w
        ZGhLQ3oraFZmL1VnMzNkV1hqalgxVk0KLS0tIHV2MTR4ckJrQUZSMDl0Skt6bWM3
        aS9IOGtXYVdDY0pyOWxBSzhzOVZ0S0EKANmH3DpyQPe35kTSUKBGWU/8dLYCeBJF
        BZG0PgpOg2CYGDMpfi1HtbFXWkzvFnTU4ovrZuMVjJxXFanXUqNLQA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-16T14:56:53Z"
  mac: ENC[AES256_GCM,data:ueYuxV+bIUG8q8qfB4CQ6LI+2u6ChHfZc1zxn8FYJuKnxlAeyVe9BaHFkuoTSxEGpUB58zFHb13IAT07lKVcJDSWIt6/OFwE+n8JXsPZOY9/ZTYu1D4/Y8hJDzSee+xsJNt6qkWFiqiUEtf5t1oNQIaa/tkd0U3dMJ+3/cyj+ng=,iv:wiAL6aEBWE9rU3Eqi5YBQ6fglodN6oRIspRcE1VJdnI=,tag:WiUKffd+xO/jQkrA3D/IuQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
