apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dask-gateway-k8s
spec:
  interval: 1m
  chart:
    spec:
      chart: dask-gateway
      version: "2024.1.0"
      sourceRef:
        kind: HelmRepository
        name: dask
      interval: 1m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  valuesFrom:
    - kind: ConfigMap
      name: dask-gateway-k8s-config
      valuesKey: values.yaml
