apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: cms
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      version: "9.2.5"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: cms
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: grafana-config
      valuesKey: values.yaml
