apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepo.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: grafana-config
    namespace: cms
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true 