# Grafana Helm Chart Values
# https://github.com/grafana/helm-charts/tree/main/charts/grafana

# Persistence configuration
persistence:
  enabled: true
  type: pvc
  size: 10Gi
  accessMode: ReadWriteOnce

# Ingress configuration
ingress:
  enabled: true
  ingressClassName: public
  path: /grafana-flux
  pathType: Prefix
  hosts:
    - cms.geddes.rcac.purdue.edu
  # tls:
  #   - secretName: grafana-tls
  #     hosts:
  #       - cms.geddes.rcac.purdue.edu

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 3000

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 472
  fsGroup: 472

# Resources
resources:
  requests:
    cpu: 2000m
    memory: 4Gi
  limits:
    cpu: 2000m
    memory: 4Gi

# Grafana configuration
grafana.ini:
  server:
    root_url: https://cms.geddes.rcac.purdue.edu/grafana-flux
    serve_from_sub_path: true
  dashboards:
    default_home_dashboard_path: /var/lib/grafana/dashboards/default/default.json
  auth.anonymous:
    enabled: true
    org_name: Main Org.
    org_role: Viewer
    hide_version: true

# Dashboard and datasource provisioning
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards/default
      - name: "single-user"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards/single-user
      - name: "users-overview"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards/users-overview

# Use ConfigMap for dashboards
dashboardsConfigMaps:
  default: grafana-dashboards

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: prometheus
        type: prometheus
        url: https://prometheus-af.geddes.rcac.purdue.edu:443
        access: proxy
        isDefault: true
      - name: prometheus-rancher
        type: prometheus
        url: http://rancher-monitoring-prometheus.cattle-monitoring-system:9090
        access: proxy
        isDefault: false
