apiVersion: v1
kind: ConfigMap
metadata:
  name: announcements-nginx-conf
  namespace: cms
data:
  default.conf: |
    server {
      listen 8080;
      location / {
        root /work/projects/purdue-af;
        autoindex off;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
      }
    }
