apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      version: "9.3.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: grafana-config
      valuesKey: values.yaml
