apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: grafana-config
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
  - name: grafana-public-dashboards
    files:
      - dashboards/default.json
      - dashboards/single-user.json
      - dashboards/sonic.json
      - dashboards/alerts.json
    options:
      disableNameSuffixHash: true
  - name: grafana-private-dashboards
    files:
      - dashboards/users-overview.json
      - dashboards/pyroscope.json
    options:
      disableNameSuffixHash: true
