apiVersion: v1
kind: Secret
metadata:
  name: kagent-grafana-mcp-token
  labels:
    app.kubernetes.io/part-of: purdue-af
    purdue-af/component: kagent
type: Opaque
stringData:
  #ENC[AES256_GCM,data:xpCWwtofMoocwMJihVhnMWoAJNe4IHBdVTjFzLM/wm5G1pmHCg3UYDo0oTuhDJkacpSh6NvVl92d54RpwU/apfo29rCAFwWaRg==,iv:9NCXjfJyRHTMG7dbqCg1Osl6N2ufTPId0JKQFaaQVg0=,tag:/qBfTNfcvjKCBaeXEb3Slg==,type:comment]
  #ENC[AES256_GCM,data:R4dl+xi+dZL9Ld8352qeinqWrhNjnDqQORDvG/bZjRisdBOIloq+brg0RSFFdRFeEzJk+N5Ste1gqJosUWrqLCxF8wk6Xm+g8hCBMRw=,iv:uq4ncQv4oFeiJcq/W2orPLutOotPF74JhXgxBhXR9zk=,tag:2TtqqNSvkxaKPyJrcOupOA==,type:comment]
  #ENC[AES256_GCM,data:2CXufRvSPQUjn/fzjDFAaQb9Fav9f5/4osHMa3tQf4uBm+ru5SP9hHarN3pRKg83VIY=,iv:0ILrS41d35b/IBX+7ATK6gLxmbGZyfoGFTofP3sWpsk=,tag:yxWIFpXka64gnw8nz3/lGg==,type:comment]
  GRAFANA_SERVICE_ACCOUNT_TOKEN: ENC[AES256_GCM,data:bsnn/UeVguC7QHswQZWbXLRgvoRw0tZcv5QgwsfPp9WuFwgYkc21c53ydDXhrA==,iv:k0a77VwezqCFLnXgkFX1o8ipQxsUTS4RgLaCRXvWD50=,tag:vqdAzaqV1Dmw2/7Is3nV4Q==,type:str]
sops:
  age:
    - recipient: age1pccfws6yghzqtg5v9228nrvs23w5thsxpr7w4kmmksn435ldev5sqkpj08
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Z1VaYkF2QWRMZlhrN2pD
        VjIxTGJTSmhodXpmaUt5RjBjeFdxQWh2UFJBCkFuQXZZYzVubFd3OHdZemlVeTlN
        V3EzY1Y0cmJWNDJoUy9CQXNXLzZ0SXcKLS0tIFdZNE1jY2o4blhFNDR1QkM2TVpH
        Y1JTd243emsrSXczZndLSC9TTU9hdVkKH38wGfnp538qRBw+L4RIoJACnWYuMrR+
        yvtdqhJur9dMNAocjoPWObpo645zdnTfmZZbOsIzbvN/k8yhK/LqMQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-08T21:54:06Z"
  mac: ENC[AES256_GCM,data:kwGFQuF6zXZ9w6x4DHS1yA1ulwW49ugvrb5n58EvuepZffhToVphnpfcdGuEDzBPSMz2nvCvneS8udXXqJXwCC9MhE2lvCPWHkhqeKmi9Eqr6Z/2JwOS+HZEzYqbQvmkdfN4esUu54OelUo+SRlXd1KP4JG/GhQfDyCEbWfKWS0=,iv:eQG3WIRdXu03eloY4yeuukhtHYfG3d/KVnp+tP3eeH4=,tag:vUpaoqjwUd0idb0jWPbefw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
