apiVersion: v1
kind: Secret
metadata:
    name: kagent-openai
    labels:
        app.kubernetes.io/part-of: purdue-af
        purdue-af/component: kagent
type: Opaque
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:2y46BZUeZkg0eUvHWa8EBlCqpP8SXfemwfCjD2CD3awXg4Y=,iv:NVqui9RJiQeKhhQ8Jzx1Nfzfdnnq8Xlil+/Y3Ul9db0=,tag:NrsNB+nfDBHQ3s++popysQ==,type:str]
sops:
    age:
        - recipient: age1pccfws6yghzqtg5v9228nrvs23w5thsxpr7w4kmmksn435ldev5sqkpj08
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZM1draks2WmQvZlFOZ2xk
            RnVaNm5RNFpYV28rSmRtb1V0S0ZzVnlzUlRrCkRzYVF6aEhxamNLRlhkcTE5WURG
            UWRBc2k3dVRKZ2huQjlza3FjaVRBR28KLS0tIGtlUFdyK0JpK0hPc3BFNlNsT2dx
            cDI5blpDSit0WTdLR0pwayt3ZTZkRFEKTu63fnG3lDjTlvpGF5ZePIxBF61lYAoY
            taoxGT4JdlqME+MZrq0zHUO5C/7F67sCVKI4U5LLXAhNh2vlATHlZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T20:30:05Z"
    mac: ENC[AES256_GCM,data:vf0pj2GWgeD1uGOgDhHAS76JkQpS6WRSVsbOmxdaS50HrB9nUogYlYLKMlXf3AEjt/HxGO30z2UAci85ruiL3ulVf/ox+K/TVLnKYM26Rmr9ZnvRSJ5F3OTmfo4GoL7m8ZHyfzmTyKzgKWfMV+xTAi/0MzAJGj10kJiWC2DbkYc=,iv:pdrZVyBUfqgNeqMYoWb+C3kd2fUQIuFyZD3fG3d18W0=,tag:O+iZhrQWzdGMsPMs16t1Zw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
