apiVersion: batch/v1
kind: CronJob
metadata:
  name: af-x509-secrets
spec:
  schedule: "0 * * * *" # Run every hour at minute 0
  concurrencyPolicy: Forbid
  suspend: false
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          enableServiceLinks: false
          serviceAccountName: af-x509-secrets
          restartPolicy: Never
          nodeSelector: { "cms-af-prod": "true" }
          tolerations:
            - key: "hub.jupyter.org/dedicated"
              operator: "Equal"
              value: "cms-af"
              effect: "NoSchedule"
          initContainers:
            - name: take-data-dir-ownership
              image: alpine:3.6
              command: ["/bin/sh", "-c"]
              args:
                [
                  "cp /etc/grid-certs-ro/usercert.pem /etc/grid-certs; chmod 600 /etc/grid-certs/usercert.pem; cp /etc/grid-certs-ro/userkey.pem /etc/grid-certs; chmod 400 /etc/grid-certs/userkey.pem",
                ]
              env:
                - name: INSTANCE_NAME
                  value: af-x509-secrets
              volumeMounts:
                - name: grid-certs-rw-copy
                  mountPath: /etc/grid-certs/
                - name: grid-secret
                  mountPath: /etc/grid-certs-ro/
          containers:
            - name: x509-secrets
              image: sslhep/x509-secrets:develop
              command: ["bash", "-c"]
              args:
                [
                  "pip install --ignore-installed 'urllib3>=2.0.0,<3' 'kubernetes>=28.0.0' && python3 x509_updater.py --secret ${x509_secret_name} --voms cms",
                ]
              resources:
                requests:
                  cpu: 100m
                  memory: 1Gi
                limits:
                  cpu: 200m
                  memory: 2Gi
              env:
                - name: MY_POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: MY_POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              imagePullPolicy: Always
              volumeMounts:
                - name: grid-certs-rw-copy
                  mountPath: /etc/grid-certs/
                - name: grid-secret
                  mountPath: /etc/grid-certs-ro/
          volumes:
            # Mount the usercert, userkey, and passphrase file. These will have the
            # wrong permissions to be used for generating the voms proxy
            - name: grid-secret
              secret:
                secretName: grid-certs-secret # Installed via servicex command line

            # Create an empty dir to share between the init container and the main
            # container. The init container will copy the certs from grid-secret
            # to this dir and set the correct permissions
            - name: grid-certs-rw-copy
              emptyDir: {}

