apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: cms
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus
      version: "27.3.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: cms
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: prometheus-config
    valuesKey: values.yaml