apiVersion: v1
kind: Service
metadata:
  name: prometheus-af-pod-monitor
  namespace: cms
  labels:
    app: prometheus-af-pod-monitor
    scrape_metrics: "true"
spec:
  type: ClusterIP
  selector:
    app: jupyterhub
  ports:
    - name: pod-metrics
      port: 9090
      targetPort: 9090
