apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cms
  name: prometheus-sa-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["list", "watch"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-sa
  namespace: cms
automountServiceAccountToken: true

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: cms
  name: prometheus-sa-rb
subjects:
  - kind: ServiceAccount
    name: prometheus-sa
    namespace: cms
roleRef:
  kind: Role
  name: prometheus-sa-role
  apiGroup: rbac.authorization.k8s.io
