rbac:
  create: false

serviceAccounts:
  server:
    create: false
    name: prometheus-sa
    automountServiceAccountToken: true

configmapReload:
  prometheus:
    enabled: false

server:
  automountServiceAccountToken: true
  # securityContext:
  #   runAsUser: 0
  #   runAsNonRoot: false
  #   fsGroup: 0
  useExistingClusterRoleName: prometheus-sa-role
  releaseNamespace: true
  configPath: /etc/config/prometheus.yml
  storagePath: /prometheus

  global:
    scrape_interval: 15s
    evaluation_interval: 15s
    scrape_timeout: 15s

  extraInitContainers:
    - name: prometheus-data-permission-fix
      image: busybox
      command: ["/bin/chmod", "-R", "777", "/prometheus"]
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
      volumeMounts:
        - name: storage-volume
          mountPath: /prometheus

  ingress:
    enabled: true
    hosts: [prometheus-af.geddes.rcac.purdue.edu]
    tls:
      - hosts: [prometheus-af.geddes.rcac.purdue.edu]
    ingressClassName: public

  strategy:
    type: RollingUpdate

  tolerations:
    - key: "hub.jupyter.org/dedicated"
      operator: "Equal"
      value: "cms-af"
      effect: "NoSchedule"

  nodeSelector:
    cms-af-prod: "true"

  persistentVolume:
    enabled: true
    existingClaim: prometheus-data-pvc
    mountPath: /prometheus

  resources:
    requests:
      cpu: 4
      memory: 8Gi
    limits:
      cpu: 4
      memory: 8Gi

  service:
    enabled: true
    servicePort: 9090
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9090"

  retention: 30d

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: "jupyterhub"
        metrics_path: "/hub/metrics"
        static_configs:
          - targets:
              - "cms.geddes.rcac.purdue.edu"
              - "cmsdev.geddes.rcac.purdue.edu"
      - job_name: "kube-state-metrics"
        static_configs:
          - targets:
              - "rancher-monitoring-kube-state-metrics.cattle-monitoring-system.svc.cluster.local:8080"
      - job_name: "slurm-metrics"
        static_configs:
          - targets:
              - "hammer-osg.rcac.purdue.edu:9100"
      - job_name: "node-exporter"
        static_configs:
          - targets:
              - "geddes-b013.rcac.purdue.edu:9796"
              - "geddes-b014.rcac.purdue.edu:9796"
              - "geddes-b015.rcac.purdue.edu:9796"
              - "geddes-g000.rcac.purdue.edu:9796"
              - "geddes-g001.rcac.purdue.edu:9796"
              - "geddes-g002.rcac.purdue.edu:9796"
              - "paf-a00.cms.rcac.purdue.edu:9796"
              - "paf-a01.cms.rcac.purdue.edu:9796"
              - "paf-a02.cms.rcac.purdue.edu:9796"
              - "paf-b00.cms.rcac.purdue.edu:9796"
              - "cms-fe01.rcac.purdue.edu:9796"
              - "cms-fe00.rcac.purdue.edu:9796"
              - "vm-hammer-g000.rcac.purdue.edu:9796"
              - "vm-hammer-g001.rcac.purdue.edu:9796"
              - "vm-hammer-g002.rcac.purdue.edu:9796"
              - "vm-hammer-g003.rcac.purdue.edu:9796"
              - "vm-hammer-g004.rcac.purdue.edu:9796"
              - "vm-hammer-g005.rcac.purdue.edu:9796"
              - "vm-hammer-f000.rcac.purdue.edu:9796"
              - "vm-hammer-f001.rcac.purdue.edu:9796"
              - "vm-hammer-f002.rcac.purdue.edu:9796"
              - "vm-hammer-f003.rcac.purdue.edu:9796"
              - "vm-hammer-f004.rcac.purdue.edu:9796"
              - "vm-hammer-f005.rcac.purdue.edu:9796"
      - job_name: "af-pod-monitor"
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - "cms"
        relabel_configs:
          # - source_labels: [__meta_kubernetes_service_label_app]
          #   target_label: 'app'
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: "pod"
          - source_labels: [__meta_kubernetes_pod_label_username_unescaped]
            target_label: "username"
          - source_labels: [__meta_kubernetes_pod_label_docker_image_tag]
            target_label: "docker_image_tag"
          - source_labels: [__meta_kubernetes_namespace]
            target_label: "namespace"
            replacement: "$1"
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: "node"
          - source_labels:
              [__meta_kubernetes_service_label_app_kubernetes_io_name]
            target_label: "app"
          - source_labels:
              [__meta_kubernetes_service_label_app_kubernetes_io_instance]
            target_label: "release"
          - source_labels:
              [__meta_kubernetes_service_label_app_kubernetes_io_component]
            target_label: "component"
          - source_labels: [__meta_kubernetes_service_label_scrape_metrics]
            action: keep
            regex: "true"
      - job_name: "envoy-monitor"
        metrics_path: "/stats/prometheus"
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - "cms"
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app]
            target_label: "app"
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: "pod"
          - source_labels: [__meta_kubernetes_pod_label_username_unescaped]
            target_label: "username"
          - source_labels: [__meta_kubernetes_pod_label_docker_image_tag]
            target_label: "docker_image_tag"
          - source_labels: [__meta_kubernetes_namespace]
            target_label: "namespace"
            replacement: "$1"
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: "node"
          - source_labels: [__meta_kubernetes_service_label_envoy]
            action: keep
            regex: "true"
      - job_name: "dask-gateway-monitor"
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - "cms"
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app]
            target_label: "app"
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: "pod"
          - source_labels: [__meta_kubernetes_pod_label_user]
            target_label: "user"
          - source_labels: [__meta_kubernetes_namespace]
            target_label: "namespace"
            replacement: "$1"
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: "node"
          - source_labels:
              [__meta_kubernetes_service_label_app_kubernetes_io_name]
            action: keep
            regex: dask-gateway
      # - job_name: 'supersonic-monitor-triton'
      #   metrics_path: '/metrics'
      #   kubernetes_sd_configs:
      #     - role: endpoints
      #       namespaces:
      #         names:
      #           - 'cms'
      #   relabel_configs:
      #     - source_labels: [__meta_kubernetes_pod_name]
      #       target_label: 'pod'
      #     - source_labels: [__meta_kubernetes_namespace]
      #       target_label: 'namespace'
      #       replacement: '$1'
      #     - source_labels: [__meta_kubernetes_pod_node_name]
      #       target_label: 'node'
      #     - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
      #       target_label: 'app'
      #     - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_instance]
      #       target_label: 'instance'
      #     - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_component]
      #       target_label: 'component'
      #     - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
      #       action: keep
      #       regex: supersonic
      #     - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_component]
      #       action: keep
      #       regex: triton
      - job_name: "supersonic-monitor-envoy"
        metrics_path: "/stats/prometheus"
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - "cms"
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: "pod"
          - source_labels: [__meta_kubernetes_namespace]
            target_label: "namespace"
            replacement: "$1"
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: "node"
          - source_labels:
              [__meta_kubernetes_service_label_app_kubernetes_io_name]
            target_label: "app"
          - source_labels:
              [__meta_kubernetes_service_label_app_kubernetes_io_instance]
            target_label: "release"
          - source_labels:
              [__meta_kubernetes_service_label_app_kubernetes_io_component]
            target_label: "component"
          - source_labels:
              [__meta_kubernetes_service_label_app_kubernetes_io_name]
            action: keep
            regex: supersonic
          - source_labels:
              [__meta_kubernetes_service_label_app_kubernetes_io_component]
            action: keep
            regex: envoy
      - job_name: "seldon-monitor-envoy"
        metrics_path: "/stats/prometheus"
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - "cms"
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: "pod"
          - source_labels: [__meta_kubernetes_namespace]
            target_label: "namespace"
            replacement: "$1"
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: "node"
          - source_labels:
              [__meta_kubernetes_service_label_app_kubernetes_io_name]
            target_label: "app"
          - source_labels:
              [__meta_kubernetes_service_label_app_kubernetes_io_instance]
            target_label: "release"
          - source_labels:
              [__meta_kubernetes_service_label_app_kubernetes_io_component]
            target_label: "component"
          - source_labels:
              [__meta_kubernetes_service_label_app_kubernetes_io_name]
            action: keep
            regex: seldon-envoy

alertmanager:
  enabled: false
pushgateway:
  enabled: false
kube-state-metrics:
  enabled: false
prometheus-node-exporter:
  enabled: false
prometheus-pushgateway:
  enabled: false
