apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: servicex-dev
spec:
  interval: 1m
  url: https://github.com/ssl-hep/ServiceX
  ref:
    branch: python-codegen-compression
