apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: servicex
spec:
  interval: 1m
  url: https://github.com/ssl-hep/ServiceX
  ref:
    tag: v1.7.2-rc.1
    # branch: develop
