apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: servicex
  namespace: cms
spec:
  suspend: false
  interval: 1m
  chart:
    spec:
      chart: helm/servicex
      sourceRef:
        kind: GitRepository
        name: servicex
        namespace: cms
      # chart: servicex
      # version: "1.6.1-RC.3"
      # sourceRef:
      #   kind: HelmRepository
      #   name: ssl-hep
      #   namespace: cms
      interval: 1m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  valuesFrom:
    - kind: ConfigMap
      name: servicex-config
      valuesKey: values.yaml
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: "servicex-did-finder-xrootd"
            patch: |
              - op: add
                path: /spec/template/spec/volumes
                value: []
              - op: add
                path: /spec/template/spec/volumes/-
                value:
                  name: x509-proxy
                  secret:
                    secretName: x509-proxy
              - op: add
                path: /spec/template/spec/containers/0/volumeMounts
                value: []
              - op: add
                path: /spec/template/spec/containers/0/volumeMounts/-
                value:
                  name: x509-proxy
                  mountPath: /etc/grid-security-ro
                  mountPropagation: HostToContainer
              - op: add
                path: /spec/template/spec/containers/0/env/-
                value:
                  name: X509_USER_PROXY
                  value: /etc/grid-security-ro/x509up
