apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: servicex
  namespace: cms
spec:
  interval: 1m
  chart:
    spec:
      chart: servicex
      version: "1.6.1-rc.1"
      sourceRef:
        kind: HelmRepository
        name: ssl-hep
        namespace: cms
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: servicex-config
    valuesKey: values.yaml