apiVersion: v1
kind: Secret
metadata:
  namespace: cms
  creationTimestamp: null
  name: servicex-secrets
data:
  accesskey: VTJYNTU3R0lBQzFXUVQ3QjdYUFQ=
  secretkey: TjRjTkZnek0yS1R3MkRjQ1lHQXQwdkNRQWRQcGF0dHJPM3daRE5CSQ==
  rabbitmq-password: bGVmdGZvb3Qx
  postgresql-password: bGVmdGZvb3Qx
  oauthMetadataURL: ""
  oauthClientID: ""
  oauthClientSecret: ""
  flaskSecretKey: ""
  jwtSecretKey: ""
  slackSigningSecret: ""
  slackSignupWebhook: ""
  mailgunAPIKey: ""
