apiVersion: v1
kind: Secret
metadata:
  name: s3-prod-secrets
type: Opaque
stringData:
  access_key: ENC[BASE64,data:ODdENFkxQlVZQlRPUjVCNDhDOFU=,type:str]
  secret_key: ENC[BASE64,data:N1U0Tk55bWNpQTljUTJZWGJIRUtOZDRaVDRraXdNNm9hc0hTWmRkMg==,type:str]
