apiVersion: v1
kind: Secret
metadata:
  namespace: cms
  creationTimestamp: null
  name: servicex-secrets
data:
  accesskey: ENC[AES256_GCM,data:850jhsMKV16l67xWRFlWCJf63Nl9A0C45e60tA==,iv:WxwPNzR4dofh0nFeRuhn0NujE2lsUfl6x02iFAsM3aE=,tag:meEUd8+DNrcGFvYUulqmWA==,type:str]
  secretkey: ENC[AES256_GCM,data:4MBh722nLh9+4ErCiUNOvG2yFG7BA/pcqmY9TWmbjSD95K2pojfEqd4+kuMnVwKOA/KHxebSL6s=,iv:5R83knHXa86+YZbgN+J34atowoCXpumvnd56Y57bhFA=,tag:6yL/Jwb+gJobY3QEIfRPHA==,type:str]
  rabbitmq-password: ENC[AES256_GCM,data:DqXFwX8jfFACL4l6,iv:sfD4EBD5cDKolgc/ltQSJ4M+RMi/qZ4ChwR+lpGjZ18=,tag:ttGV+gcqDpY2v9hgJ2R2Sw==,type:str]
  postgresql-password: ENC[AES256_GCM,data:XfY26Iog9UdmSfvJ,iv:0GOEzFhg9ggbhF7BySzMhlVBr+WHze6S1uHXJDV1GCc=,tag:t+1beISUYopcg8BzTzNDRQ==,type:str]
  oauthMetadataURL: ""
  oauthClientID: ""
  oauthClientSecret: ""
  flaskSecretKey: ""
  jwtSecretKey: ""
  slackSigningSecret: ""
  slackSignupWebhook: ""
  mailgunAPIKey: ""
sops:
  age:
    - recipient: age1pccfws6yghzqtg5v9228nrvs23w5thsxpr7w4kmmksn435ldev5sqkpj08
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQnVJbks4MmhIOG1ONnBr
        S1lrV20reHNqaHdUcWFzSjFzdk81Yk9lTldRCnRyMFc3ZjdiVWNmQU9sVnJIMHBN
        ZXJ0MW0rK2o2RWF1Rzkvd3JUVnhYTEkKLS0tIEd4RVQwREM3d1JzdUtydGIvNGxl
        MVhjUFZSVGRlOEhxZi9WOHY0RHFUVTgK6Z1fHbwSHx/YQKKjNZCXRUDIHHX62pYa
        IQHvwwt3cOWjzCma0v9BRNwuGN51uxOiD48pUXJdtjlJgKMrQuOGAA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-24T19:37:44Z"
  mac: ENC[AES256_GCM,data:O0MFkvmPdWObIJ8aNcRa+Pw3C+P9TMqxt8hjNGmgwL3IPFHnMW+koLX4lTjaUicprpetBLK5HqMNZgA7qQzaNei5Y+C+GCo9HjJpdApYkBPDRG3czWmEz0+xdDOd7jOdHwICwusZJI3vCb03RV6YgRaxuaqIMlBrcbYK6gbMVvI=,iv:BSEkyEjDOcKMzWiWwbRVTypevWlaABTNVq/sFXB2Kus=,tag:TxMnAtyMTtRofGzywdZj9A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
