apiVersion: batch/v1
kind: CronJob
metadata:
  name: kernel-builder
  namespace: cms
spec:
  schedule: "*/2 * * * *" # Run every 2 minutes
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: kernel-builder
          restartPolicy: Never
          containers:
            - name: kernel-builder
              image: rockylinux:8.9
              command:
                - /bin/bash
                - -c
                - |
                  # Copy the script to the container and execute it
                  cp /scripts/build-kernels.sh /tmp/build-kernels.sh
                  chmod +x /tmp/build-kernels.sh
                  /tmp/build-kernels.sh
              resources:
                requests:
                  memory: "4Gi"
                  cpu: "2"
                limits:
                  memory: "8Gi"
                  cpu: "4"
              volumeMounts:
                - name: af-shared-storage
                  mountPath: /work/
                  mountPropagation: HostToContainer
                - name: scripts
                  mountPath: /scripts/
                  readOnly: true
          volumes:
            - name: af-shared-storage
              persistentVolumeClaim:
                claimName: af-shared-storage
            - name: scripts
              configMap:
                name: kernel-builder-scripts
          nodeSelector:
            cms-af-prod: "true"
          tolerations:
            - key: "hub.jupyter.org/dedicated"
              operator: "Equal"
              value: "cms-af"
              effect: "NoSchedule"
