apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cronjob.yaml
  - rbac.yaml

configMapGenerator:
  - name: kernel-builder-scripts
    files:
      - build-kernels.sh

namespace: cms
