apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - job-generator.yaml
  - rbac.yaml

configMapGenerator:
  - name: kernel-builder-scripts
    namespace: cms
    files:
      - generate-kernel-jobs.sh
      - build-single-kernel.sh
    options:
      disableNameSuffixHash: true

namespace: cms
