apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: a2rchi
spec:
  suspend: false
  interval: 1m
  chart:
    spec:
      chart: apps/a2rchi/helm/a2rchi
      sourceRef:
        kind: GitRepository
        name: purdue-af-experimental
      interval: 1m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  valuesFrom:
    - kind: ConfigMap
      name: a2rchi-config
      valuesKey: values.yaml
