ingress:
  enabled: ${enable_ingresses}
  class: public
  host: a2rchi.geddes.rcac.purdue.edu

image:
  repository: geddes-registry.rcac.purdue.edu/cms/a2rchi
  tag: latest
  pullPolicy: IfNotPresent

model:
  backend: openai
  openai:
    model: gpt-oss:latest
    baseUrl: "https://genai.rcac.purdue.edu/api"
    secretName: "a2rchi-openai-api-key"

postgres:
  enabled: true
  persistence:
    enabled: false
    storageClass: ${multinode_storage_class}

chromadb:
  enabled: true
  persistence:
    enabled: false
    storageClass: ${multinode_storage_class}

envSecret:
  create: false
  name: a2rchi-secrets

config:
  a2rchiConfigYaml: |
    name: a2rchi-purdue-af
    global:
      DATA_PATH: "/root/A2rchi/data/"
      ACCOUNTS_PATH: "/root/A2rchi/accounts/"
      ACCEPTED_FILES: [".txt", ".pdf"]
      LOGGING:
        input_output_filename: "chain_input_output.log"
      verbosity: 3

    data_manager:
      sources:
        links:
          input_lists:
            - examples/deployments/basic-gpu/miscellanea.list
          scraper:
            reset_data: true
            verify_urls: false
            enable_warnings: false
      utils:
        anonymizer:
          nlp_model: en_core_web_sm
      embedding_name: "OpenAIEmbeddings"
      chunk_size: 1000
      chunk_overlap: 0
      num_documents_to_retrieve: 5

    a2rchi:
      pipelines: ["QAPipeline"]
      pipeline_map:
        QAPipeline:
          max_tokens: 10000
          prompts:
            required:
              condense_prompt: "examples/deployments/basic-gpu/condense.prompt"
              chat_prompt: "examples/deployments/basic-gpu/qa.prompt"
          models:
            required:
              condense_model: "OpenAIGPT4"
              chat_model: "OpenAIGPT4"
      model_class_map:
        OpenAIGPT4:
          class: OpenAIGPT4
          kwargs:
            model_name: gpt-oss:latest

    services:
      chat_app:
        host: "0.0.0.0"
        port: 7861
        hostname: "a2rchi.geddes.rcac.purdue.edu"
        external_port: 80
        trained_on: ""
      chromadb:
        chromadb_host: "chromadb"
      redmine_mailbox:
        answer_tag: ""
