apiVersion: v1
kind: ServiceAccount
metadata:
  name: conda-env-builder
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: conda-env-builder-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: conda-env-builder-rolebinding
subjects:
  - kind: ServiceAccount
    name: conda-env-builder
roleRef:
  kind: Role
  name: conda-env-builder-role
  apiGroup: rbac.authorization.k8s.io
