apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cnpg-operator
  namespace: cms
spec:
  interval: 1m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.26.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cms
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: cnpg-operator-config
      valuesKey: values.yaml
