apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cnpg-cluster
  namespace: cms
spec:
  interval: 1m
  chart:
    spec:
      chart: cluster
      version: "0.3.1"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cms
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: cnpg-cluster-config
      valuesKey: values.yaml
