name: Purge README Cache

on:
  schedule:
    # Run every 6 hours to match the user graph update frequency
    - cron: '0 */6 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Purge README cache
      run: |
        chmod +x .github/workflows/purge-readme-cache.sh
        ./.github/workflows/purge-readme-cache.sh 